force-app/main/default/objects/CommunityOpp__c/CommunityOpp__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela las oportunidades para Comunidades.</description>
    <label>Contratación Online</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Contratación Online</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrataciones Online</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunityOpp__c/fields/ConsentimientoDatosSegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>ConsentimientoDatosSegundoTitular__c</fullName>
    <description>El contacto que está contratando el producto tiene el consentimiento para proporcionar los datos del segundo titular</description>
    <label>Consentimiento almacenar datos 2 titular</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Email2Titular__c.field-meta.xml
<CustomField>
    <fullName>Email2Titular__c</fullName>
    <description>Se guarda el email del 2º titular en la contratación online para posteriormente poder enviar la información por correo a través de una alerta de correo electrónico de los flujos</description>
    <label>Email 2º Titular</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/SegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>SegundoTitular__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo para indicar quien es el contacto que actúa como segundo titular de la contratación online</description>
    <label>2º Titular</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrataciones Online (2º Titular)</relationshipLabel>
    <relationshipName>Contrataciones_Online_Segundo_Titular</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/TieneVariosTitulares__c.field-meta.xml
<CustomField>
    <fullName>TieneVariosTitulares__c</fullName>
    <description>Campo para saber si el producto tiene varios titulares asociados</description>
    <label>Tiene varios titulares</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Sí, hay otro titular y está informado</fullName>
            </value>
            <value>
                <fullName>Hay otro titular, pero no está informado</fullName>
            </value>
            <value>
                <fullName>Hay más de dos titulares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Flow_ActualizarContratOnline.cls
/*
@author LeadClic Solutions S.L.
@date 18/06/2019
@description Clase que actualiza la contratación Online al crear 2ºTitular o encontrar ya otro contacto

<pre>
FECHA                 AUTOR           ACCION
18/06/2019			LCS - RDM		 Creación
*/
global without sharing class Flow_ActualizarContratOnline {
    /**
     *  Método invocable desde los flujos. Utilizamos una lista de una wrapper class de datos enviados desde el flujo. 
     *  
     * 
     * @param  consentimientoSegTit	valor del consentimiento del segundo titular
     * @param  emailSegTit email del segundo titular
     * @param  segTit id del segundo titular
     * @param  tieneVariosTit valor del segundo titular
     * 
     */
    @InvocableMethod(label='Llamada flujo' description='Llamada desde el flujo')
    public static void metodoInvocable (list<GetParameters> WrapperParams){
        //Actualizamos la contratación online con los datos obtenidos del flujo
        CommunityOpp__c contrOnline = new CommunityOpp__c();
            contrOnline.Id = WrapperParams[0].idContratOnline;
            contrOnline.ConsentimientoDatosSegundoTitular__c = WrapperParams[0].consentimientoSegTit;
            contrOnline.Email2Titular__c = WrapperParams[0].emailSegTit;
            contrOnline.SegundoTitular__c = WrapperParams[0].segTit;
            contrOnline.TieneVariosTitulares__c = WrapperParams[0].tieneVariosTit;
        update contrOnline;
    }
    /*
     * @descripción Wrapper class que recibe los datos de entrada del flujo
     */ 
    global class GetParameters {
        
        @InvocableVariable( label = 'IdContratOnline' description = 'Id contratación online' required=true )
        global String idContratOnline; 
        
        @InvocableVariable( label = 'Consentimiento2ºTit' description = 'Consentimiento 2º Titular' required=true )
        global String consentimientoSegTit; 
        
        @InvocableVariable( label = 'Email2ºTitular' description = 'Email 2º Titular' required=true )
        global String emailSegTit;
        
        @InvocableVariable( label = '2ºTit' description = '2º Titular' required=true )
        global Id segTit;
        
        @InvocableVariable( label = 'TieneVariosTit' description = 'Tiene Varios Titulares' required=true )
        global String tieneVariosTit;
    }
}