force-app/main/default/objects/Case/fields/AsesorCitaNoAsiste__c.field-meta.xml
<CustomField>
    <fullName>AsesorCitaNoAsiste__c</fullName>
    <description>Asesor de la cita a la cual el cliente no asistió</description>
    <label>Asesor de la cita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FechaCitaNoAsiste__c.field-meta.xml
<CustomField>
    <fullName>FechaCitaNoAsiste__c</fullName>
    <description>Fecha de la cita a la cual el cliente no asistió</description>
    <label>Fecha de la Cita</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/OficinaCitaNoAsiste__c.field-meta.xml
<CustomField>
    <fullName>OficinaCitaNoAsiste__c</fullName>
    <description>Oficna de la cita a la que el cliente no asistió</description>
    <label>Oficina de la Cita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

force-app/main/default/classes/citacionSchedule.cls
/*
@author LeadClic Solutions S.L.
@date 20/05/2019
@description Clase que realiza la lógica para la citación de citas

<pre>
FECHA             AUTOR           ACCION
20/05/2019		LCS - RDM	   	  Creación. 
10/10/2019		LCS - RDM	   	  Modificación. Se añaden los campos de Oficina del evento para añadirlos al caso 
*/
global with sharing class citacionSchedule  implements Schedulable {
    /**
     *  Método que realiza las comprobaciones de fecha para crear un caso de confirmación de cita
     *  
     * @param  lista con los eventos que se han insertado
     */
    global void execute(SchedulableContext ctx) {
        list<Case> lcasos = new list<Case>();

        //Creamos las variables que utilizaremos para el filtro de la query
        //Fecha inicial del evento que sirve para el inicio de la query
        Date inicioEventoQuery = Date.Today().addDays(2);
        //Fecha inicial del evento que sirve para el final de la query
        DateTime finEventoQuery = DateTime.newinstance(inicioEventoQuery.year(), inicioEventoQuery.month(), inicioEventoQuery.day(), 23, 59, 59);
        //Obtenemos el tipo de registro Cita del evento
        Id idRecordTypeCita = Schema.SObjectType.Event.getRecordTypeInfosByName().get('Cita').getRecordTypeId();
        //Recuperamos los eventos que esten a una fecha de inicio de 48h y que sean del tipo Cita
        list<Event> lEventosConfirmacion = [SELECT Id, Subject, Description, WhoId, Oficina__r.Name, Owner.Name, StartDateTime FROM Event 
                                            WHERE StartDateTime >= :inicioEventoQuery
                                            AND StartDateTime <= :finEventoQuery  
                                            AND recordTypeId = :idRecordTypeCita];

        //Si existen eventos en la lista, creamos un caso de confirmación de citas
        if(!lEventosConfirmacion.isEmpty()){
            for(Event e :lEventosConfirmacion){
                Case c = new Case();
                    c.Status = 'Nuevo';
                    c.Subject = system.label.AsuntoCasoConfirmacion;
                    c.Description = e.Subject + ':\n' + e.Description;
                    c.ContactId = e.WhoId;
                    c.OficinaCitaNoAsiste__c = e.Oficina__r.Name;
            		c.AsesorCitaNoAsiste__c = e.Owner.Name;
                	c.FechaCitaNoAsiste__c = e.StartDateTime;
                    c.OwnerId = system.label.idColaCasoConfirmacion;
                    c.Type = system.label.TipoConfirmacionCita;                    
                	c.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Call Center Confirmación de cita').getRecordTypeId();
                lcasos.add(c);
            }
        }

        if(!lcasos.isEmpty()) insert lcasos;

    }
}