force-app/main/default/objects/LeadProduct__c/LeadProduct__c.object-meta.xml
<CustomObject>
    <description>Productos en los que tiene interés un candidato</description>
    <label>Interés en Producto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre producto de interés</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interés en Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadProduct__c/fields/Candidato__c.field-meta.xml
<CustomField>
    <fullName>Candidato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación primaria a la entidad Candidato</description>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Productos_de_Interes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadProduct__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación secundaria a la entidad Producto</description>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Interes_en_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DuracionEntrevista__c.field-meta.xml
<CustomField>
    <fullName>DuracionEntrevista__c</fullName>
    <description>Duración de la entrevista en minutos</description>
    <inlineHelpText>Duración de la entrevista en minutos</inlineHelpText>
    <label>Duración entrevista</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo id externo, el standard de Salesforce no permite realizar operaciones de upsert al no estar definido como externalId</description>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SchProductInfoControllerTest.cls
@isTest
private class SchProductInfoControllerTest {
    
    @TestSetup
    static void setup(){
        Lead l = SchDataTest.createLead();
        insert l;

        Product2 prod = new Product2 (Name = 'Test Prod', IsActive = true, ExternalId__c = '123', DuracionEntrevista__c = 30);
        insert prod;

        LeadProduct__c leadProd = new LeadProduct__c(Candidato__c = l.Id, Producto__c = prod.Id);
        insert leadProd;
    }

    @isTest static void testRetrieveCurrentProducts() {
        
        Id leadId = [SELECT Id FROM Lead LIMIT 1].Id;

        Test.startTest();
        SchProductInfoController.retrieveCurrentProducts(leadId);
        Test.stopTest();
    }

    @isTest static void testGetAppointmentDuration() {

        Id prodId = [SELECT Id FROM Product2 LIMIT 1].Id;

        Test.startTest();
        SchProductInfoController.getAppointmentDuration(new List<String>{prodId});
        Test.stopTest();
    }
}