force-app/main/default/objects/CalendarFilter__mdt/CalendarFilter__mdt.object-meta.xml
<CustomObject>
    <description>Contains Calendar Sttings fields used as filters in appointment scheduler</description>
    <label>Calendar filter</label>
    <pluralLabel>Calendar filters</pluralLabel>
</CustomObject>

force-app/main/default/objects/CalendarFilter__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Field definition related to custom metadata filter</description>
    <label>Field</label>
    <metadataRelationshipControllingField>CalendarFilter__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>CalendarFilters</relationshipLabel>
    <relationshipName>CalendarFilters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CalendarFilter__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object definition</description>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>CalendarFilters</relationshipLabel>
    <relationshipName>CalendarFilters</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CalendarSettingMapping__mdt/CalendarSettingMapping__mdt.object-meta.xml
<CustomObject>
    <description>Contains calendar setting mapping on creation if custom fields are added.</description>
    <label>Calendar Setting Mapping</label>
    <pluralLabel>Calendar Setting Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CalendarSettingMapping__mdt/fields/CalendarFilter__c.field-meta.xml
<CustomField>
    <fullName>CalendarFilter__c</fullName>
    <description>Related calendar filter, contains a field reference to CalendarSetting</description>
    <label>Calendar filter</label>
    <referenceTo>CalendarFilter__mdt</referenceTo>
    <relationshipLabel>Calendar Setting Mappings</relationshipLabel>
    <relationshipName>CalendarSettingMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CalendarSettingMapping__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <metadataRelationshipControllingField>CalendarSettingMapping__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Calendar_Setting_Mappings</relationshipLabel>
    <relationshipName>Calendar_Setting_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CalendarSettingMapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Related object to map</description>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>CalendarSettingMappings</relationshipLabel>
    <relationshipName>CalendarSettingMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/CalendarSettingNewController.cls
/** 
 * Controller class for new calendar setting quick action or standar button override
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-09-26
 */
public with sharing class CalendarSettingNewController {
    
    /**
     * Retrieves related info and field mapping if a custom metadata is defined.
     * @param  recordId related record Id if compoenent is called via quickaction 
     * @return          mapping and related record for calendar setting creation
     */ 
    @AuraEnabled
    public static GetInitDataResponse getInitData(Id recordId){

        GetInitDataResponse response = new GetInitDataResponse();

        try {

            String objectName;
            
            if(recordId != null) {
                
                objectName = recordId.getSobjectType().getDescribe().name;
               
                // calendar mapping retrieval, retrieve only fields related to quickaction host object
                Set<String> lRelatedField = new Set<String>();
                lRelatedField.add('Id');

                Map<String, String> mMap = new Map<String, String>();

                for(CalendarSettingMapping__mdt mapping : [SELECT Id, CalendarFilter__r.Field__r.QualifiedApiName, Field__r.QualifiedApiName 
                                                            FROM CalendarSettingMapping__mdt 
                                                            WHERE Object__r.QualifiedApiName = :objectName]) {
                    
                    lRelatedField.add(mapping.Field__r.QualifiedApiName);
                    mMap.put(mapping.CalendarFilter__r.Field__r.QualifiedApiName, mapping.Field__r.QualifiedApiName);
                }

                response.mMapping = mMap;

                // record retrieval
                String queryString = 'SELECT ' + String.join(new List<String>(lRelatedField), ',') + ' FROM ' + objectName + ' WHERE Id =  \'' + recordId + '\' LIMIT 1';  
                
                List<sObject> lObj = Database.query(queryString);
                response.relatedRecord = lObj[0];
            }

          
        } catch (Exception e) {
            System.debug(e.getMessage());
            response.status = false;
            response.errorMsg = e.getMessage() + e.getStackTraceString();
        }

        return response;
    }


    public class GetInitDataResponse {

        @auraEnabled public Boolean status = true;
        @auraEnabled public String errorMsg = ''; 

        @auraEnabled public sObject relatedRecord;
        @auraEnabled public Map<String, String> mMapping {get; set;}

    }


}