force-app/main/default/objects/ConversionCandidato__c/ConversionCandidato__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos que son fijos para la conversión del candidato</description>
    <label>Conversion Candidato</label>
</CustomObject>

force-app/main/default/objects/ConversionCandidato__c/fields/EtapaOportunidad__c.field-meta.xml
<CustomField>
    <fullName>EtapaOportunidad__c</fullName>
    <description>Etapa de la oportunidad que se asigna en la conversión del candidato</description>
    <label>Etapa oportunidad</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConversionCandidato__c/fields/IdListaDePrecio__c.field-meta.xml
<CustomField>
    <fullName>IdListaDePrecio__c</fullName>
    <description>Id de la lista de precios que se asocia a la oportunidad que se crea en la conversión del candidato</description>
    <label>Id Lista de precio</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadProduct__c/LeadProduct__c.object-meta.xml
<CustomObject>
    <description>Productos en los que tiene interés un candidato</description>
    <label>Interés en Producto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre producto de interés</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interés en Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadProduct__c/fields/Candidato__c.field-meta.xml
<CustomField>
    <fullName>Candidato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación primaria a la entidad Candidato</description>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Productos_de_Interes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadProduct__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación secundaria a la entidad Producto</description>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Interes_en_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestLeadCustomConvert.cls
/*
@author LeadClic Solutions S.L.
@date 12/04/2019
@description Clase Test para la clase LeadCustomConvert

<pre>
FECHA                 AUTOR           ACCION
12/04/2019			LCS - RMG		 Creación.

*/
@isTest
public class TestLeadCustomConvert {

    @testSetup static void crearCustomSettings(){
        //Configuración personalizada  
        ConversionCandidato__c confPerConvCand = new ConversionCandidato__c();
        confPerConvCand.name = 'General';
        confPerConvCand.EtapaOportunidad__c = 'Calificación';
        confPerConvCand.IdListaDePrecio__c = Test.getStandardPricebookId();
        confPerConvCand.RolFuncionContacto__c = 'Economic Buyer';
        insert confPerConvCand;
    }

    @isTest
    static void TestConversionCandidato(){   
        //Lista con los candidatos que se van a convertir
        list<Id> lIdCand = new list<Id>();   
        
        //Candidato para su conversión
        Lead cand = new lead();
        cand.FirstName = 'Candidato';
        cand.LastName = 'Candidato Test';
        cand.PostalCode = '28914';
        cand.Phone = '965852365';
        insert cand;

        //Insertamos al candidato para su conversión
        lIdCand.add(cand.id);
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id FROM PriceBookEntry WHERE Product2Id =: prod.id];

        //Producto de interés
        LeadProduct__c prodInteres = new LeadProduct__c();
        prodInteres.Candidato__c = cand.id;
        prodInteres.Producto__c = prod.id;
        insert prodInteres;

        system.test.startTest();
            LeadCustomConvert.convertLeads(lIdCand);
        system.test.stopTest();
    }
}