force-app/main/default/objects/IntegracionSF__c/IntegracionSF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración encargada de guardar los datos necesarios para poder obtener el token de la instacia de SF y de esta manera poder conectarnos con la misma instancia</description>
    <label>IntegracionSF</label>
</CustomObject>

force-app/main/default/objects/IntegracionSF__c/fields/clientid__c.field-meta.xml
<CustomField>
    <fullName>clientid__c</fullName>
    <description>Clave pública de la aplicación conectada</description>
    <label>client_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/clientsecret__c.field-meta.xml
<CustomField>
    <fullName>clientsecret__c</fullName>
    <description>Clave privada de la aplicación conectada</description>
    <label>client_secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>Contraseña del usuario indicado</description>
    <label>password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/UrlEndPoint__c.field-meta.xml
<CustomField>
    <fullName>UrlEndPoint__c</fullName>
    <label>UrlEndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>Nombre de usuario de un usuario de SF</description>
    <label>username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID externo para la carga de campos de documentos</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/SubidaComunidad__c.field-meta.xml
<CustomField>
    <fullName>SubidaComunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicará que el tipo de documento puede ser subido desde la comunidad por los usuarios al gestor documental.</description>
    <label>Subida a través de comunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/ValorEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>ValorEtiqueta__c</fullName>
    <description>Almacenará el valor de la etiqueta que se mostrará en la comunidad del tipo de documento.</description>
    <label>Valor etiqueta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/VisibleComunidad__c.field-meta.xml
<CustomField>
    <fullName>VisibleComunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicará que el tipo de documento tendrá la posibilidad de ser consultado desde la comunidad por los usuarios.</description>
    <label>Visible en comunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateTipoDocumento.cls
public with sharing class UpdateTipoDocumento {
      /**
    * Método encargado obtener el sesion Id para poder acceder
    *
    * @return token
    *
    */
    public static String getAuthToken (){
        String token;
            //Cargamos el custom setting para obtener los datos necesarios del Endpoint
            IntegracionSF__c datosSF = IntegracionSF__c.getInstance('General');
            
            Http h = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(datosSF.UrlEndPoint__c + '?grant_type=password&client_id='+ datosSF.clientid__c + '&client_secret=' + datosSF.clientsecret__c + '&username=' + datosSF.username__c + '&password='+ datosSF.password__c);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            HttpResponse response = h.send(request);
            
            
            if(response.getStatusCode() != 200){
                token = null;
            }else{
                map<String,Object> mRespuesta = (map<String, Object>) JSON.deserializeUntyped(response.getBody());
                
                token = (String)mRespuesta.get('access_token');
            }
        return token;
    }
    public static void postNewTipoDocumento (String nuevoDoc, String nuevoApiDoc){
        User user=[SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId() limit 1];
        TipoDocumento__c documento = new TipoDocumento__c();
        if(Test.isRunningTest()) nuevoApiDoc=TipoDocumento__c.TipoDocumento__c.getDescribe().getPicklistValues()[0].getValue();
        documento.TipoDocumento__c=nuevoApiDoc;
        documento.ExternalID__c=nuevoApiDoc;
        documento.ValorEtiqueta__c=nuevoDoc;
        documento.VisibleComunidad__c=false;
        documento.SubidaComunidad__c=false;
        documento.OwnerId=user.Id;
        insert documento;

    }
    public static void updateGlobal(String ApiDoc, String NameDoc, Boolean active){
        User user=[SELECT Id, ContactId FROM User WHERE Id = :UserInfo.getUserId() limit 1];
        TipoDocumento__c documento = [SELECT TipoDocumento__c,ValorEtiqueta__c FROM TipoDocumento__c WHERE ExternalID__c=:ApiDoc];
        if(documento !=null){
            if(active){
                documento.OwnerId=user.Id;
                documento.ValorEtiqueta__c=NameDoc;
                update documento;
            }else{
                delete documento;
            }
        }

    }
}