force-app/main/default/objects/Contract/fields/EstadoExpedienteComunidad__c.field-meta.xml
<CustomField>
    <fullName>EstadoExpedienteComunidad__c</fullName>
    <description>Contendrá el valor del estado que se mostrará en la comunidad para los usuarios</description>
    <label>Estado expediente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/contractPathLayoutController.cls
/*
@author LeadClic Solutions S.L.
@date 
@description Clase que contiene el código controlador del LWC contractPathLayoutController
<pre>
FECHA             AUTOR           ACCION
09/08/2021      LCS - SRG         Creación. Obtenemos el estado del expediente en base a la custom Setting
*/
public with sharing class contractPathLayoutController {
    
    @AuraEnabled(cacheable=true)
    public static string getStatus(String recordId){
        String estado ='';
        try {
            List<EstadosComunidad__c> ec= EstadosComunidad__c.getall().values();
            
            Contract expediente=[SELECT EstadoExpedienteComunidad__c FROM Contract WHERE Id=:recordId ];
            estado=expediente.EstadoExpedienteComunidad__c;
            for (EstadosComunidad__c variable : ec) {
                if(variable.Estado__c==expediente.EstadoExpedienteComunidad__c) estado=variable.Name;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return estado;
    }
}