force-app/main/default/objects/Contract/fields/ExpedientePrincipal__c.field-meta.xml
<CustomField>
    <fullName>ExpedientePrincipal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Expediente principal con el que está relacionado</description>
    <inlineHelpText>Expediente principal con el que está relacionado</inlineHelpText>
    <label>Expediente principal</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Producto correspondiente con el expediente creado</description>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/TipoExpDerivado__c.field-meta.xml
<CustomField>
    <fullName>TipoExpDerivado__c</fullName>
    <description>Tipologia del expediente derivado</description>
    <label>Tipo de expediente derivado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demanda independiente de cláusula suelo</fullName>
            </value>
            <value>
                <fullName>Demanda independiente de IRPH</fullName>
            </value>
            <value>
                <fullName>Demanda Independiente de Gastos Hipotecarios</fullName>
            </value>
            <value>
                <fullName>Demanda independiente de Tarjeta Revolving</fullName>
            </value>
            <value>
                <fullName>Demanda independiente de Acciones Popular</fullName>
            </value>
            <value>
                <fullName>Demanda Independiente otras situaciones</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <description>Tipo de expediente común</description>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Datosexpedientederivado__c/Datosexpedientederivado__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos utilizados para la derivación del expediente</description>
    <label>Datos expediente derivado</label>
</CustomObject>

force-app/main/default/objects/Datosexpedientederivado__c/fields/TiposDeriv__c.field-meta.xml
<CustomField>
    <fullName>TiposDeriv__c</fullName>
    <description>Tipos separados por coma que utilizaremos en el componente para cargar el picklist</description>
    <label>Tipos de derivación</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ExpedienteDerivadoController.cls
/*
@author Leadclic Solutions S.L.
@date 14/05/2019 
@description    Controlador del componente ExpedienteDerivado

<pre>
FECHA                   AUTOR                   ACCION
14/05/2019              LCS - RDM               Creación
02/12/2019              LCS - RDM               Modifición. Se añade parche en la creación de los expediente derivados para los ids antiguos.
02/12/2019				      LCS - HPS				        Modificación. Se hereda Producto__c en el método creacionExpediente

*/
public with sharing class ExpedienteDerivadoController {
    /**
    * Método que se encarga de recuperar los datos de la configuración personalizada y enviarla al componente para rellenar el picklist
    *
    * @return lista de String
    */
    @AuraEnabled
    public static list<String> getTipoDerivado(){
        Datosexpedientederivado__c datosExp = Datosexpedientederivado__c.getInstance('General');
        list<String> tipoExp = datosExp.TiposDeriv__c.split(',');

        return tipoExp;
    }
    
    public class WrapperExp{
        @AuraEnabled public String NumExpediente;
        @AuraEnabled public String Oportunidad;
        @AuraEnabled public String Cuenta;
    }
    /**
    * Método que se encarga de recuperar los datos del expediente actual y enviarlo al componente para mostrarlo
    *
    * @param Id del contrato del registro
    * @return lista de String
    */
    @AuraEnabled
    public static WrapperExp getExpediente(Id contractId){
        Contract expediente = [SELECT Id, AccountId, Account.Name, ContractNumber, IdExpediente__c, Oportunidad__c, Oportunidad__r.Name FROM Contract WHERE id =: contractId];

        WrapperExp datosExp = new WrapperExp();
            datosExp.NumExpediente = expediente.IdExpediente__c;
            datosExp.Oportunidad = expediente.Oportunidad__r.Name;
            datosExp.Cuenta = expediente.Account.Name;
       
       return datosExp;
    }
    /**
    * Método que se encarga de recuperar los datos del expediente actual y enviarlo al componente para mostrarlo
    *
    * @param Id del contrato del registro
    * @return lista de String
    */
    @AuraEnabled
    public static Boolean checkExpedienteDerivado(Id contractId){
        Boolean permitirDerivar;
        Contract expediente = [SELECT Id, ExpedientePrincipal__c FROM Contract WHERE id =: contractId];

       if(String.isBlank(expediente.ExpedientePrincipal__c)) permitirDerivar = true;
       else permitirDerivar = false;
       
       return permitirDerivar;
    }
    /**
    * Método que se encarga de crear el expediente derivado y llamar al WS de Arriaga para comunicar esta situación
    *
    * @param Id del contrato del registro
    */
    @AuraEnabled
    public static String creacionExpediente(Id contractId, String tipoDerivado){
        try{
            //Guardamos una copia de la BBDD de ese momento.
            Contract expediente = [SELECT Id, AccountId, Account.Name, ContractNumber, IdExpediente__c, Oportunidad__c, Oportunidad__r.Name, Producto__c FROM Contract WHERE id =: contractId];
            //Recuperamos todos los IdExpedientes relacionados con el derivado
            list<Contract> lExpedienteSecundarios = [SELECT IdExpediente__c FROM Contract WHERE (id =: contractId) OR (ExpedientePrincipal__c =: contractId)];
            integer idexp = 0;//Variable que utilizamos para obtener el mayor
            String oldIdentificador;//Recuperamos el identificador último utilizado relacionado al contrato padre.
            for(Contract c : lExpedienteSecundarios){
                if(idexp < integer.valueOf(c.IdExpediente__c.substring(4))){
                    idexp = integer.valueOf(c.IdExpediente__c.substring(4)); 
                    oldIdentificador = c.IdExpediente__c;
                }
            }
            //Le sumamos uno al dígito de control y lo guardamos en una variable
            String newIdentificador;
            String nuevoIdExpediente;

            if(oldIdentificador.length() < 11){
                newIdentificador = '01';
                nuevoIdExpediente = oldIdentificador.substring(0,4) + newIdentificador + oldIdentificador.substring(4,oldIdentificador.length());
            } else {
                Integer identificador = integer.valueOf(oldIdentificador.substring(5,6));
                if(identificador < 9){
                    identificador = identificador + 1;
                    newIdentificador = '0'+ identificador;
                }
                else{
                    identificador = integer.valueOf(oldIdentificador.substring(4,5));
                    identificador = identificador + 1;                
                    newIdentificador = identificador + '0';
                }
                nuevoIdExpediente = oldIdentificador.substring(0,4) + newIdentificador + oldIdentificador.substring(6,oldIdentificador.length());
            }
            Contract expedienteDerivado = new Contract();
                expedienteDerivado.AccountId = expediente.AccountId;
                expedienteDerivado.IdExpediente__c = nuevoIdExpediente;
                expedienteDerivado.Oportunidad__c = expediente.Oportunidad__c;
                expedienteDerivado.ExpedientePrincipal__c = expediente.Id;
                expedienteDerivado.TipoExpDerivado__c = tipoDerivado;
                // campo heredado añadido
            	expedienteDerivado.Producto__c = expediente.Producto__c; 
            insert expedienteDerivado;

            /* FALTA LLAMADA A SU WS */


            //Si no ha ocurrido ningún error, mostramos el nuevo expediente
            String url = URL.getSalesforceBaseUrl().toExternalForm()+'/'+expedienteDerivado.id;
            return url;
        }
        catch(Exception e){
            throw e;
        }

    }
}