force-app/main/default/objects/Contract/fields/PagoConfirmado__c.field-meta.xml
<CustomField>
    <fullName>PagoConfirmado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que se marcará cuando el pago pase a estado &apos;Confirmado&apos;</description>
    <label>Pago confirmado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Pago__c/Pago__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela un pago realizado sobre un expediente. Modela los pagos telemático a través de la comunidad así como los pagos físicos en oficinas.</description>
    <label>Pago</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de Pago</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pago__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado del pago realizado a la hora de realizar una contratación de un producto</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Emitida</fullName>
                <isActive>false</isActive>
                <label>Emitida</label>
            </value>
            <value>
                <fullName>Pago parcial</fullName>
                <isActive>false</isActive>
                <label>Pago parcial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pago__c/fields/Expediente__c.field-meta.xml
<CustomField>
    <fullName>Expediente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Expediente asociado al pago</description>
    <label>Expediente</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Pagos</relationshipLabel>
    <relationshipName>Pagos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TriggerPagoHandler.cls
/*
@author LeadClic Solutions S.L.
@date 13/05/2019
@description Clase manejadora del Trigger de Pagos

FECHA                 AUTOR           ACCION
13/06/2019			LCS - RDM		 Creación.
19/06/2019			LCS - RDM		 Modificación. Actualizamos el Trigger para no llamar a la clase de Minerva. En vez de eso actualizamos
                                                el expediente si el pago ha sido confirmado
 
*/
public class TriggerPagoHandler {
	 /**
     *  Método que se llama desde el trigger de Pago
     *  
     * @param  mapa de los valores actuales
     * @param  lista con los Pagos que se han modificado
     */
    public static void afterUpdate(list<Pago__c> lNewPagos, map<Id, Pago__c> mOldPagos){
        //Lista de pagos realizados
        List<Pago__c> lPagosCompletados = new List<Pago__c>();
        //Actualizar Expedientes relacionados
        List<Contract> lActualizarExp = new List<Contract>();

        for(Pago__c pago : lNewPagos){
            Contract expediente = new Contract();
            if((mOldPagos.get(pago.Id).Estado__c != pago.Estado__c) && (pago.Estado__c == System.Label.EstadoPagoConfirmado)){
                lPagosCompletados.add(pago);
                //Actualizamos campos y los añadimos a la lista de expedientes para actualizar
                    expediente.Id = pago.Expediente__c;
                    expediente.PagoConfirmado__c = true;
                lActualizarExp.add(expediente);
            } 
        }  

        //Si la lista no esta vacía, actualizamos los expedientes
        if(!lActualizarExp.isEmpty()){
			update lActualizarExp;             
        }
    }
    
	 /**
     *  Método que se llama desde el trigger de Pago
     *  
     * @param  mapa de los valores insertados
     */
    public static void afterInsert(list<Pago__c> lNewPagos){
        //Lista de pagos realizados
        List<Pago__c> lPagosCompletados = new List<Pago__c>();
        //Actualizar Expedientes relacionados
        List<Contract> lActualizarExp = new List<Contract>();

        for(Pago__c pago : lNewPagos){            
            Contract expediente = new Contract();
            if(pago.Estado__c == System.Label.EstadoPagoConfirmado){
                lPagosCompletados.add(pago);
                //Actualizamos campos y los añadimos a la lista de expedientes para actualizar
                    expediente.Id = pago.Expediente__c;
                    expediente.PagoConfirmado__c = true;
                lActualizarExp.add(expediente);
            } 
        } 

        //Si la lista no esta vacía, actualizamos los expedientes
        if(!lActualizarExp.isEmpty()){
			update lActualizarExp;             
        }
    }
}