force-app/main/default/objects/Account/recordTypes/Oficina.recordType-meta.xml
<RecordType>
    <fullName>Oficina</fullName>
    <active>true</active>
    <label>Oficina</label>
</RecordType>

force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Oficina__c.field-meta.xml
<CustomField>
    <fullName>Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo test para los filtros</description>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La oficina no pertenece a la provincia indicada</errorMessage>
        <filterItems>
            <field>Account.ShippingState</field>
            <operation>equals</operation>
            <valueField>$Source.Provincia__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendar Settings</relationshipLabel>
    <relationshipName>CalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>La Coruña</fullName>
            </value>
            <value>
                <fullName>Álava</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Ávila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Guipúzcoa</fullName>
            </value>
            <value>
                <fullName>Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lérida</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <description>Indicates a user or resource subtype</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asesor</fullName>
            </value>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Sala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Calendar type for resource or user requesting from the meeting scheduler</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Resource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LeadProduct__c/LeadProduct__c.object-meta.xml
<CustomObject>
    <description>Productos en los que tiene interés un candidato</description>
    <label>Interés en Producto</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nombre producto de interés</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interés en Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadProduct__c/fields/Candidato__c.field-meta.xml
<CustomField>
    <fullName>Candidato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación primaria a la entidad Candidato</description>
    <label>Candidato</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Productos_de_Interes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadProduct__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación secundaria a la entidad Producto</description>
    <label>Producto</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Interés en Productos</relationshipLabel>
    <relationshipName>Interes_en_Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PerfilesCallCenter__c/PerfilesCallCenter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IDs de los perfiles de Call Center, para asignar citas sin escoger usuarios y salas manualmente</description>
    <label>Perfiles Call Center</label>
</CustomObject>

force-app/main/default/objects/PerfilesCallCenter__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>Id del perfil en formato de 18 caracteres</description>
    <label>Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DuracionEntrevista__c.field-meta.xml
<CustomField>
    <fullName>DuracionEntrevista__c</fullName>
    <description>Duración de la entrevista en minutos</description>
    <inlineHelpText>Duración de la entrevista en minutos</inlineHelpText>
    <label>Duración entrevista</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SchExtendedFeaturesImplementationTest.cls
@isTest
private class SchExtendedFeaturesImplementationTest {
    @testSetup static void setup() {

        Lead l = new Lead(LastName = 'testLNLead', FirstName = 'test', Company='Test company', PostalCode='12345', Email = 'test@test.com');
        insert l;

        Product2 prod = new Product2(Name = 'TestProduct', DuracionEntrevista__c = 15, IsActive = true);
        insert prod;

        LeadProduct__c lp = new LeadProduct__c(Candidato__c = l.Id, Producto__c = prod.Id);
        insert lp;


        Id oficinaRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Oficina').getRecordTypeId();
        Account oficina = new Account(Name = 'Test Oficina', ShippingState = 'Madrid', RecordTypeId = oficinaRecordTypeId, Phone = '6000000000');
        insert oficina;   

        // Calendar Setting
        // DML operation Insert not allowed on Calendar, so we have to query it
        Calendar cal = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() limit 1];

        Schema.DescribeFieldResult fieldSubtype = CalendarSetting__c.Subtype__c.getDescribe();
		List<Schema.PicklistEntry> lFieldSubtype = fieldSubtype.getPicklistValues();
        String subtype = (lFieldSubtype != null && !lFieldSubtype.isEmpty()) ? lFieldSubtype[0].getValue() : ''; 
        
        CalendarSetting__c cSet = new CalendarSetting__c(CalendarId__c = cal.Id, Subtype__c = subtype, Type__c = 'User', Provincia__c = 'Madrid', Oficina__c = oficina.Id);
        insert cSet;


        // Custom settings
        PerfilesCallCenter__c pcc = new PerfilesCallCenter__c(Name='ProfileUserId',Id__c = UserInfo.getProfileId());
        insert pcC;
    }

    @isTest static void testSetInitParams() {

        Id lId = [SELECT Id FROM Lead LIMIT 1].Id;

        test.startTest();
        SchExtendedFeaturesImplementation.setInitParams(lId);
        test.stopTest();
    }

    @isTest static void testSetInitFilterParams() {
        
        Account oficina = [SELECT Id FROM Account LIMIT 1];

        test.startTest();
        SchExtendedFeaturesImplementation scsEfi = new SchExtendedFeaturesImplementation();

        // Itinerantes use case
        Map<Object, Object> mParams;
        scsEfi.setInitFilterParams(mParams);

        // standard init searching current calendar setting 
        mParams = new Map<Object, Object>();
        mParams.put('Oficina__c', oficina.Id);
        scsEfi.setInitFilterParams(mParams);
        test.stopTest();
    }

    @isTest static void testSetEventParams() {

        Calendar cal = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() limit 1];

        Map<Object, Object> mAssignedTo = new Map<Object, Object>();
        mAssignedTo.put('Asesor', cal.Id);

        Account oficina = [SELECT Id FROM Account LIMIT 1];
        Map<Object, Object> mFilterValues = new Map<Object, Object>();
        mFilterValues.put('Oficina__c', oficina.Id);

        Map<Object, Object> mResource = new Map<Object, Object>();

        Map<Object, Object> mExtraParams = new Map<Object, Object>();
        mExtraParams.put('products', new List<Object>());

        Map<Object, Object> mParams = new Map<Object, Object>();
        mParams.put('assignedTo', mAssignedTo);
        mParams.put('filterValues', mFilterValues);
        mParams.put('lResource', mResource);
        mParams.put('extraParams', mExtraParams);

        Map<Id, Id> mCalendarUser = new Map<Id, Id>();   
        mCalendarUser.put(cal.Id, UserInfo.getUserId());
        

        test.startTest();
        // Asesor
        SchExtendedFeaturesImplementation scsEfi = new SchExtendedFeaturesImplementation();
        scsEfi.setEventParams(new Event(durationInMinutes=15, ActivityDateTime=system.now()), mParams, mCalendarUser);

        // Administrativo
        mAssignedTo.remove('Asesor');
        mAssignedTo.put('Administrativo', cal.Id);
        mParams.put('assignedTo', mAssignedTo);
        scsEfi.setEventParams(new Event(durationInMinutes=15, ActivityDateTime=system.now()), mParams, mCalendarUser);
        test.stopTest();
    }
}