force-app/main/default/objects/CustomerReview__c/CustomerReview__c.object-meta.xml
<CustomObject>
    <label>Reseña RRSS</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Código Reseña</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseñas RRSS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerReview__c/fields/ExternalIDReview__c.field-meta.xml
<CustomField>
    <fullName>ExternalIDReview__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External ID Reseña</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Origen Reseña</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SocialNetworks</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/ReplyText__c.field-meta.xml
<CustomField>
    <fullName>ReplyText__c</fullName>
    <label>Respuesta AA</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/ReviewText__c.field-meta.xml
<CustomField>
    <fullName>ReviewText__c</fullName>
    <label>Reseña Cliente</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/ReviewTitle__c.field-meta.xml
<CustomField>
    <fullName>ReviewTitle__c</fullName>
    <label>Título</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/Stars__c.field-meta.xml
<CustomField>
    <fullName>Stars__c</fullName>
    <label>Estrellas</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/ToProcess__c.field-meta.xml
<CustomField>
    <fullName>ToProcess__c</fullName>
    <defaultValue>true</defaultValue>
    <label>To Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/UserEmail__c.field-meta.xml
<CustomField>
    <fullName>UserEmail__c</fullName>
    <label>Email Reseña</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CustomerReview__c/fields/UserNickname__c.field-meta.xml
<CustomField>
    <fullName>UserNickname__c</fullName>
    <label>Nickname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SocialNetworks.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Trustpilot</fullName>
    </customValue>
    <customValue>
        <fullName>No Enviar</fullName>
    </customValue>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <masterLabel>Redes Sociales</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IntegrationTrustPilot.cls
@RestResource(urlMapping='/eventListener')
global without sharing class IntegrationTrustPilot {
    @HttpPost
    global static void eventListener() {
        RestRequest req = RestContext.request;

        Payload payload = (Payload) JSON.deserialize(req.requestBody.toString(), Payload.class);
        List<CustomerReview__c> reviews = new List<CustomerReview__c>();
        CustomerReview__c review;
        for(Event event : payload.events) {
            if(event.eventName != 'service-review-deleted') {
                review = new CustomerReview__c(
                    ToProcess__c = true,
                    Platform__c = 'TrustPilot',
                    Stars__c = event.eventData.stars,
                    ExternalIDReview__c = event.eventData.id,
                    ReviewTitle__c = event.eventData.title,
                    ReviewText__c = event.eventData.text,
                    UserNickname__c = event.eventData.consumer.name,
                    UserEmail__c = getPrivateInfo(event.eventData.id)
                );
            }

            reviews.add(review);
        }

        upsert reviews ExternalIDReview__c;
        // upsert reviews;
    }
    
    public static String getToken() {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Trustpilot_Get_Oauth_Token');
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
        req.setBody('grant_type=password&username=victor.sainzgimeno@mail-bip.com&password=Bipconsulting01');

        HttpResponse res = new Http().send(req);
        system.debug(res.getBody());
        Map<String,Object> responseBody = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());

        return (String) responseBody.get('access_token');
    }

    public static String getPrivateInfo(String reviewId) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Trustpilot_Get_Private_Info/' + reviewId);
        setAuthHeader(req);
        req.setMethod('GET');
        req.setTimeout( 120000 );

        HttpResponse res = new Http().send(req);
        system.debug(res.getBody());
        Map<String,Object> responseBody = (Map<String,Object>) JSON.deserializeUntyped(res.getBody());

        return (String) responseBody.get('referralEmail');
    }

    public static String postReply(List<CustomerReview__c> review) {
        HttpRequest req = new HttpRequest();
        setAuthHeader(req);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setTimeout( 120000 );

        String errorString = '';
        for(CustomerReview__c singleReview : review) {
            req.setEndpoint('callout:Trustpilot_Get_Private_Info/' + singleReview.ExternalIDReview__c + '/reply');
            req.setBody(JSON.serialize(new Map<String,String> {
                'message' => singleReview.ReplyText__c
            }));
            
            HttpResponse res = new Http().send(req);
            
            if(res.getStatusCode() != 201) {
                errorString += res.toString();
            }
        }

        return errorString == '' ? null : errorString;
    }

    public static List<String> getInvitationLink(List<Account> accounts) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:Trustpilot_Get_Invitation_Link');
        setAuthHeader(req);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setTimeout( 120000 );

        List<String> links = new List<String>();
        for(Account account : accounts) {
            if(String.isNotBlank(account.PersonEmail)) {
                req.setBody(JSON.serialize(new Map<String,String> {
                    'locationId' => 'Arriaga Associados',
                    'referenceId' => account.Id,
                    'email' => account.PersonEmail,
                    'name' => account.Name,
                    // 'tags' => null,
                    // 'redirectUri' => null,
                    'locale' => 'es-ES'
                }));
            
                HttpResponse res = new Http().send(req);

                links.add((String) ((Map<String,Object>) JSON.deserializeUntyped(res.getBody())).get('url'));
            } else {
                // TO AVOID "System.JSONException: no content to map to Object due to end of input" IN FLOW
                links.add('');
            }
        }

        return links;
    }

    private static void setAuthHeader(HttpRequest req) {
        req.setHeader('Authorization', 'Bearer ' + getToken());
    }

    private class Payload {
        List<Event> events;
    }
    
    private class Event {
        String eventName;
        String version;
        EventData eventData;
    }
    
    private class EventData {
        String id;
        String language;
        Integer stars;
        String title;
        String text;
        String locationId;
        String referenceId;
        String createdAt;
        String link;
        Boolean isVerified;
        Consumer consumer;
        List<Map<String,String>> tags;
    }
    
    private class Consumer {
        String id;
        String name;
        String link;
    }
}