force-app/main/default/objects/CampoDocumento__c/CampoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado relacionado con el objeto  tipo documento donde indicaremos los campos que tienen un tipo de documento concreto</description>
    <label>Campo del documento</label>
    <nameField>
        <label>Nombre del campo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campos del documento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampoDocumento__c/fields/TipoCampo__c.field-meta.xml
<CustomField>
    <fullName>TipoCampo__c</fullName>
    <description>Tipo del dato que se introducirá en el campo</description>
    <label>Tipo del campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
                <label>Fecha</label>
            </value>
            <value>
                <fullName>number</fullName>
                <label>Numérico</label>
            </value>
            <value>
                <fullName>text</fullName>
                <label>Texto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que pertenece el campo</description>
    <label>Tipo de Documento</label>
    <referenceTo>TipoDocumento__c</referenceTo>
    <relationshipLabel>Campos del documento</relationshipLabel>
    <relationshipName>Campos_del_documento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestGDDocumentListController.cls
/*
@author LeadClic Solutions S.L.
@date 
@description Clase Test para la clase que contiene el código controlador del LWC gdDocumentitems
<pre>
FECHA             AUTOR           ACCION
04/07/2019      LCS - RDM         Creación.
 
*/
@isTest
public class TestGDDocumentListController {
    
    @testSetup static void crearCustomSettings() {
    }
    
    @isTest static void testGetTipoDocumento(){
        List<TipoDocumento__c> lTipos = new List<TipoDocumento__c>();
        	TipoDocumento__c tipo1 = new TipoDocumento__c();
        		tipo1.TipoDocumento__c = '126';
        lTipos.add(tipo1);
        	TipoDocumento__c tipo2 = new TipoDocumento__c();
        		tipo2.TipoDocumento__c = '127';
        lTipos.add(tipo2);
        insert lTipos;
        
        list<CampoDocumento__c> lCamposDoc = new list<CampoDocumento__c>();
        	CampoDocumento__c campo1 = new CampoDocumento__c();
        		campo1.TipoDocumento__c = lTipos[0].Id;
        		campo1.TipoCampo__c = 'number';
        lCamposDoc.add(campo1);
        	CampoDocumento__c campo2 = new CampoDocumento__c();
        		campo2.TipoDocumento__c = lTipos[0].Id;
        		campo2.TipoCampo__c = 'Date';
        lCamposDoc.add(campo2);
        	CampoDocumento__c campo3 = new CampoDocumento__c();
        		campo3.TipoDocumento__c = lTipos[1].Id;
        		campo3.TipoCampo__c = 'Date';
        lCamposDoc.add(campo3);
        insert lCamposDoc;
        
        system.Test.startTest();
        	GDDocumentListController.getFieldDoc('126');
        	GDDocumentListController.getFieldDoc('216');
        	GDDocumentListController.getFieldDoc(null);
        system.Test.stopTest();
        
    }

}