force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID externo para la carga de campos de documentos</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/SubidaComunidad__c.field-meta.xml
<CustomField>
    <fullName>SubidaComunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicará que el tipo de documento puede ser subido desde la comunidad por los usuarios al gestor documental.</description>
    <label>Subida a través de comunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/ValorEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>ValorEtiqueta__c</fullName>
    <description>Almacenará el valor de la etiqueta que se mostrará en la comunidad del tipo de documento.</description>
    <label>Valor etiqueta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/VisibleComunidad__c.field-meta.xml
<CustomField>
    <fullName>VisibleComunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicará que el tipo de documento tendrá la posibilidad de ser consultado desde la comunidad por los usuarios.</description>
    <label>Visible en comunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateTipoDocumentoTest.cls
@isTest
public class UpdateTipoDocumentoTest {
    
    public static Integer prueba;
    
    @testSetup static void crearCustomSettings() {
        TestAux.crearIntegracionSF();
    }
    public class MockHttpResponseToken implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"access_token":"eyKLÑJALKDJALKlkjdkjadi5687hdajhKJDLK"}');
            res.setStatusCode(200);
            return res;
        }
    }
    public class MockHttpResponseTokenKO implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setStatusCode(400);
            return res;
        }
    }
    public class MockHttpResponseResult implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {         
            // Create a fake response          
            HttpResponse res = new HttpResponse();
                res.setHeader('Content-Type', 'application/json');  
                if(TestUpdateGlobalPicklistValue.prueba == 1){ 
                    res.setBody('{"access_token":"eyKLÑJALKDJALKlkjdkjadi5687hdajhKJDLK"}');
                    res.setStatusCode(200);                        
                }else if(TestUpdateGlobalPicklistValue.prueba == 2){  
                    res.setBody('{'
                                +    '"attributes":{'
                                +        '"type":"GlobalValueSet",'
                                +        '"url":"/services/data/v41.0/tooling/sobjects/GlobalValueSet/0Nt5E0000009KngSAE"'
                                +    '}'
                                +    ',"Metadata":{'
                                +        '"customValue":[{'
                                +            '"color":null,'
                                +            '"default":false,'
                                +            '"description":null,'
                                +            '"isActive":null,'
                                +            '"label":"CERTIFICADO DE DEFUNCIÓN",'
                                +            '"urls":null,'
                                +            '"valueName":"CERTIFICADO DE DEFUNCIÓN"'
                                +        '}]'
                                +    '}'
                                +'}');
                    res.setStatusCode(200);
                }else if(TestUpdateGlobalPicklistValue.prueba == 3){   
                    res.setStatusCode(200);
                }
            
            return res;
        }
    }
    // ---- Token ---- //
    @isTest static void testGetTokenOK(){
        System.Test.startTest();        
            // Set mock callout class 
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseToken()); 
            UpdateTipoDocumento.getAuthToken();
        System.Test.stopTest();
    }
    // ---- Post ---- //
        @isTest static void testPostTipoDocumentoValue(){
            System.Test.startTest();        
                // Set mock callout class 
                Test.setMock(HttpCalloutMock.class, new MockHttpResponseResult()); 
                UpdateTipoDocumento.postNewTipoDocumento ('nuevoDoc2', 'nuevoApiDoc');
            System.Test.stopTest();
        }
    // ---- Update ---- //
        @isTest static void testUpdTipoDocumentoValue(){
            TipoDocumento__c tipo=new TipoDocumento__c();
            tipo.TipoDocumento__c='187';
            tipo.ExternalID__c='187';
            tipo.ValorEtiqueta__c='nuevoDoc';
            tipo.VisibleComunidad__c=false;
            tipo.SubidaComunidad__c=false;
            insert tipo;
            System.Test.startTest();        
                // Set mock callout class 
                Test.setMock(HttpCalloutMock.class, new MockHttpResponseResult()); 
                UpdateTipoDocumento.updateGlobal ('187', 'NameDoc', true);
            System.Test.stopTest();
        }
}