force-app/main/default/objects/Account/fields/AccountSyncMinerva__c.field-meta.xml
<CustomField>
    <fullName>AccountSyncMinerva__c</fullName>
    <description>Estado de la sincronización con los servicios web de Minerva. Los valores que pueden venir en el campos son OK y ERROR</description>
    <label>Cuenta sincronizada Minerva</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/AccountSyncProd__c.field-meta.xml
<CustomField>
    <fullName>AccountSyncProd__c</fullName>
    <description>Estado de la sincronización con los servicios web de Producción. Los valores que pueden venir en el campos son OK y ERROR</description>
    <label>Cuenta sincronizada Producción</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <masterLabel>TipoDocumento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestTriggerAccount.cls
/*
@author LeadClic Solutions S.L.
@date 16/04/2019
@description Clase Test para el trigger de cuenta y su handler. También testea la clase ActualizarInfoUsuarioComunidad

<pre>
FECHA                 AUTOR           ACCION
16/04/2019			LCS - RMG		 Creación.
29/04/2019			LCS - RDM		 Modificación. Se crea la llamada para las comprobaciones de DNI
04/09/2019			LCS - RDM		 Modificación. Subida de % de cobertura
 
*/
@isTest
public class TestTriggerAccount {
	
    @isTest static void cambiarEmail(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@test.com';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        cuentaPersonal.EstadoCuenta__c = 'Cliente Potencial';
        insert cuentaPersonal;

        Account cuenta = [SELECT PersonContactId
                            FROM Account
                            WHERE Id = :cuentaPersonal.id LIMIT 1].get(0);
        
        //Creamos el usuario de la comunidad
        Profile p = [SELECT Id FROM Profile WHERE Name='Comunidad Arriaga'];        
        
        User u1 = new User( email='testArriaga160419@arriaga.com',
                profileid = p.id, 
                UserName='testArriaga160419@arriaga.com', 
                Alias = 'test',
                TimeZoneSidKey='America/New_York',
                EmailEncodingKey='ISO-8859-1',
                LocaleSidKey='en_US', 
                LanguageLocaleKey='en_US',
                ContactId = cuenta.PersonContactId,
                FirstName = 'Test',
                LastName = 'Test');
		
		insert u1;        
        //Cambiamos el email del contacto para que salte el trigger
        cuentaPersonal.PersonEmail = 'testMod@test.com';
        
        system.Test.startTest();
        	update cuentaPersonal;
        System.Test.stopTest();
    }
    
    @isTest static void SinDNI(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@test.com';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        cuentaPersonal.EstadoCuenta__c = 'Cliente Potencial';
        insert cuentaPersonal;
        
        cuentaPersonal.PersonEmail = 'testMod@test.com';
        system.Test.startTest();
        	update cuentaPersonal;
        System.Test.stopTest();
    }
    
    @isTest static void insertDNI(){
        try{
            //Creamos la cuenta personal
            Account cuentaPersonal = new Account();
            cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            cuentaPersonal.PersonEmail = 'test@test.com';
            cuentaPersonal.FirstName = 'Tesst';
            cuentaPersonal.LastName = 'Test';
            cuentaPersonal.EstadoCuenta__c = 'Cliente Potencial';
            cuentaPersonal.TipoDocumento__c = 'NIF';
            cuentaPersonal.DocumentoIdentidad__c = '12345677A';  
            system.Test.startTest();
            insert cuentaPersonal;
            System.Test.stopTest();
        }catch(Exception e){}
    }
    
    @isTest static void updatetDNI(){
        try{
            //Creamos la cuenta personal
            Account cuentaPersonal = new Account();
            cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            cuentaPersonal.PersonEmail = 'test@test.com';
            cuentaPersonal.FirstName = 'Tesst';
            cuentaPersonal.LastName = 'Test';
            cuentaPersonal.EstadoCuenta__c = 'Cliente';
            cuentaPersonal.AccountSyncMinerva__c = 'OK';
            cuentaPersonal.AccountSyncProd__c = 'OK';
            insert cuentaPersonal;
             
            system.Test.startTest();
            	cuentaPersonal.TipoDocumento__c = 'NIF';
            	cuentaPersonal.DocumentoIdentidad__c = '12345677A'; 
                update cuentaPersonal;
            System.Test.stopTest();
        }catch(Exception e){}
    }
}