force-app/main/default/objects/Account/fields/Activa__c.field-meta.xml
<CustomField>
    <fullName>Activa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Valor que indica si una oficina está disponible para solicitar citar en ella.</description>
    <label>Activa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Oficina.recordType-meta.xml
<RecordType>
    <fullName>Oficina</fullName>
    <active>true</active>
    <label>Oficina</label>
</RecordType>

force-app/main/default/objects/Contract/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Documentación aportada para el estado inicial</description>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/HojaEncargo__c.object-meta.xml
<CustomObject>
    <description>Plantilla de hoja de encargo para guardar los valores que se traspasan a la oferta en función de la tipología de contratación.</description>
    <label>Hoja de Encargo</label>
    <nameField>
        <label>Nombre de Hoja de Encargo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hojas de Encargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HojaEncargo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo identificador externo para realizar la carga de las hojas de encargo. También machea con un maestro de Hde suministrado via Drive por Arriaga</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFDatosArriaga__c.field-meta.xml
<CustomField>
    <fullName>PDFDatosArriaga__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <inlineHelpText>Datos de Arriaga , del Cliente y del producto</inlineHelpText>
    <label>Datos de Arriaga</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFDesistimiento__c.field-meta.xml
<CustomField>
    <fullName>PDFDesistimiento__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <label>Desistimiento</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFHonorarios__c.field-meta.xml
<CustomField>
    <fullName>PDFHonorarios__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <label>Honorarios</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Documentos que se deben aportar en el primer estado</description>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocumentosCompletadoAportado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletadoAportado__c</fullName>
    <description>Documentación aportada para el estado inicial</description>
    <label>Documentos completado básico aportado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HojaEncargo__c.field-meta.xml
<CustomField>
    <fullName>HojaEncargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación con la hoja de encargo correspondiente. Completado en el momento de la selección de la tipología de esta. De este objeto se trasladaran valores a la oportunidad.</description>
    <label>Hoja de Encargo</label>
    <referenceTo>HojaEncargo__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LossReason__c.field-meta.xml
<CustomField>
    <fullName>LossReason__c</fullName>
    <description>Motivo de la pérdida de la oportunidad</description>
    <label>Motivo pérdida</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cártel Coches</fullName>
            </value>
            <value>
                <fullName>Cártel Coches Requerimiento</fullName>
            </value>
            <value>
                <fullName>Clausula Suelo</fullName>
            </value>
            <value>
                <fullName>Divorcio</fullName>
            </value>
            <value>
                <fullName>Ficheros Acceso</fullName>
            </value>
            <value>
                <fullName>Ficheros Combinado</fullName>
            </value>
            <value>
                <fullName>Ficheros Reclamación</fullName>
            </value>
            <value>
                <fullName>Gastos Hipoteca</fullName>
            </value>
            <value>
                <fullName>Herencias</fullName>
            </value>
            <value>
                <fullName>IRPH</fullName>
            </value>
            <value>
                <fullName>Monitorio</fullName>
            </value>
            <value>
                <fullName>Multidivisa</fullName>
            </value>
            <value>
                <fullName>Oposición a Monitorio</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Plusvalía</fullName>
            </value>
            <value>
                <fullName>Préstamo Usurero</fullName>
            </value>
            <value>
                <fullName>Reclamación Cantidad RV</fullName>
            </value>
            <value>
                <fullName>Reclamación de Cantidad</fullName>
            </value>
            <value>
                <fullName>RV Diligencias</fullName>
            </value>
            <value>
                <fullName>RV Estándar</fullName>
            </value>
            <value>
                <fullName>RV Informe</fullName>
            </value>
            <value>
                <fullName>Sucesiones</fullName>
            </value>
            <value>
                <fullName>Triodos Bank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Motivo_Perdida_Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Motivo_Perdida_Descripcion__c</fullName>
    <label>Motivo Pérdida Descripción</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Confianza en el proceso</fullName>
            </value>
            <value>
                <fullName>Entidad extranjera</fullName>
                <isActive>false</isActive>
                <label>Entidad extranjera</label>
            </value>
            <value>
                <fullName>Escasa cuantía</fullName>
            </value>
            <value>
                <fullName>Honorarios Finales elevados</fullName>
            </value>
            <value>
                <fullName>Honorarios totales</fullName>
                <isActive>false</isActive>
                <label>Honorarios totales</label>
            </value>
            <value>
                <fullName>Mala opinión del despacho</fullName>
            </value>
            <value>
                <fullName>No comparece banco</fullName>
                <isActive>false</isActive>
                <label>No comparece banco</label>
            </value>
            <value>
                <fullName>No consumidor</fullName>
                <isActive>false</isActive>
                <label>No consumidor</label>
            </value>
            <value>
                <fullName>No hay oficina presencial</fullName>
                <isActive>false</isActive>
                <label>No hay oficina presencial</label>
            </value>
            <value>
                <fullName>No interesa</fullName>
            </value>
            <value>
                <fullName>No localizado</fullName>
            </value>
            <value>
                <fullName>No puede pagar</fullName>
                <isActive>false</isActive>
                <label>No puede pagar</label>
            </value>
            <value>
                <fullName>No viable ASESOR</fullName>
            </value>
            <value>
                <fullName>No viable SSJJ</fullName>
            </value>
            <value>
                <fullName>Operaciones lucrativas</fullName>
                <isActive>false</isActive>
                <label>Operaciones lucrativas</label>
            </value>
            <value>
                <fullName>Oportunidad duplicada/errónea</fullName>
            </value>
            <value>
                <fullName>Oportunidad inexistente</fullName>
                <isActive>false</isActive>
                <label>Oportunidad inexistente</label>
            </value>
            <value>
                <fullName>Otro despacho</fullName>
            </value>
            <value>
                <fullName>Otros (Rellenar Nota)</fullName>
                <isActive>false</isActive>
                <label>Otros (Rellenar Nota)</label>
            </value>
            <value>
                <fullName>Pago inicial elevado</fullName>
            </value>
            <value>
                <fullName>Redactado cláusula</fullName>
                <isActive>false</isActive>
                <label>Redactado cláusula</label>
            </value>
            <value>
                <fullName>Reparto de gastos</fullName>
                <isActive>false</isActive>
                <label>Reparto de gastos</label>
            </value>
            <value>
                <fullName>Riesgo Costas Contrarias</fullName>
            </value>
            <value>
                <fullName>Sin documentación</fullName>
            </value>
            <value>
                <fullName>TAE</fullName>
                <isActive>false</isActive>
                <label>TAE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Office__c.field-meta.xml
<CustomField>
    <fullName>Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oficina de Contratación</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Seleccionàr una Cuenta de tipo Oficina y Activa</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Oficina</value>
        </filterItems>
        <filterItems>
            <field>Account.Activa__c</field>
            <operation>notEqual</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Oficina)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Lista de documentos que debe completar el asesor</description>
    <inlineHelpText>Lista de documentos que debe completar el asesor</inlineHelpText>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo id externo, el standard de Salesforce no permite realizar operaciones de upsert al no estar definido como externalId</description>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestTriggerOpportunity.cls
/*
@author LeadClic Solutions S.L.
@date 08/05/2019
@description Clase test del trigger de oportunidad

<pre>
FECHA             AUTOR           ACCION
08/05/2019      LCS - RMG         Creación.
24/06/2019      LCS - RDM         Modificación. Se añaden los métodos que pasan por la oportunidad cerrada perdida y la aportación de documentos
04/07/2019      LCS - RDM         Modificación. Se añaden el método para pasar por cerradad ganada aportando los documentos
30/07/2019      LCS - RDM         Modificación. Se añaden los campos necesarios para pasar por el método de creación del pago
04/09/2019      LCS - RDM         Modificación. Subida de % de cobertura
16/12/2019      LCS - HPS         Modificacion. Se modifica el método 'cerrarOportunidadGanadaDocumentos' para respetar la nueva regla de validación creada para 'Oportunidad'.
27/04/2020      LCS - RAL         Modificación. Se añade la fecha de justificante de pago para actualizar la oportunidad
*/
@isTest
public class TestTriggerOpportunity {
     @testSetup static void crearCustomSettings() {
        
        EstadosComunidad__c confEstadosComunidad = new EstadosComunidad__c();
        confEstadosComunidad.Name = '00';
        confEstadosComunidad.Estado__c = 'ESTADO NO DEFINIDO';
        insert confEstadosComunidad;
    }
    static testMethod  void cerrarOportunidad(){
    
        //Creamos la oficina
        Account oficina = new Account();
        oficina.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Oficina').getRecordTypeId();
        oficina.Name = 'TestOficina';
        oficina.Activa__c = true;
        oficina.Phone = '123123123';
        insert oficina;

        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        oportunidad.Office__c = oficina.Id;
        insert oportunidad;
        
        //Añadimos documentos a la oportunidad        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test';      
        cv.PathOnClient ='test';           
        cv.VersionData =blob.valueOf('Test Adjunto');          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=oportunidad.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        insert contentlink;
        
        System.Test.startTest();
            try{
                //Cambiamos la etapa de la oportunidad a cerrada/ganada
                oportunidad.StageName = system.label.OportunidadCerragaGanada;
                update oportunidad;
            
                //Volvemos a pasar la oportunidad a abierta
                oportunidad.StageName = system.label.OportunidadCalificacion;
                update oportunidad; 
            
                //Pasamos la oportunidad a cerrada/ganada
                oportunidad.StageName = system.label.OportunidadCerragaGanada;
                update oportunidad;
            }catch(Exception e){}
        System.Test.stopTest();
    }
    
    
    @isTest static void cerrarOportunidadPerdida(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        insert oportunidad;
        
        //Añadimos documentos a la oportunidad        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test';      
        cv.PathOnClient ='test';           
        cv.VersionData =blob.valueOf('Test Adjunto');          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=oportunidad.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        insert contentlink;
        
        System.Test.startTest();
            //Cambiamos la etapa de la oportunidad a cerrada/perdida
            oportunidad.StageName = system.label.OportunidadCerragaPerdida;
            oportunidad.LossReason__c = 'Cliente no quiere contratar';
            oportunidad.Motivo_Perdida_Descripcion__c='Confianza en el proceso';
            update oportunidad;
        System.Test.stopTest();
    }
    
    @isTest static void cerrarOportunidadDocumentos(){
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        oportunidad.DocumentosCompletado__c = '118;120';
        insert oportunidad;
        
        
        Contract Exp = new Contract();
        Exp.AccountId = cuentaPersonal.Id;
        Exp.Pricebook2Id = standardPricebook.id;
        Exp.IdExpediente__c = oportunidad.NumeroExpediente__c;
        Exp.Oportunidad__c = oportunidad.id;
        insert Exp;
        
        //Añadimos documentos a la oportunidad        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test';      
        cv.PathOnClient ='test';           
        cv.VersionData =blob.valueOf('Test Adjunto');          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=oportunidad.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        insert contentlink;
        
        System.Test.startTest();
            //Cambiamos los documentos aportados
            oportunidad.DocumentosCompletadoAportado__c = '118;120';    
            update oportunidad;
        System.Test.stopTest();
    }
    
    @isTest static void cerrarOportunidadGanadaDocumentos(){
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        //Crear Hoja de encargo
        HojaEncargo__c hoja = new HojaEncargo__c();
        hoja.PDFDatosArriaga__c = 'TEST {!Name}';
        hoja.PDFDesistimiento__c = 'TEST {!Account.Name}';
        hoja.PDFHonorarios__c = 'TEST {!TEST}';
        hoja.ExternalId__c = '12345';
        insert hoja;
 
        //Asociamos el pricebook
        PriceBook2 pb = New PriceBook2(Id = test.getStandardPricebookId(), isActive = true);
        update pb;
        
        Id price = Test.getStandardPricebookId();

        //Creamos la oficina
        Account oficina = new Account();
        oficina.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Oficina').getRecordTypeId();
        oficina.Name = 'TestOficina';
        oficina.Activa__c = true;
        oficina.Phone = '123123123';
        insert oficina;
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        oportunidad.DocumentosContratacion__c = '118;120';
        oportunidad.DocumentosContratacionAportado__c = '118;120';  
        oportunidad.PrecioTotal__c = 15.2;
        oportunidad.Tipo__c = 'TPV';
        oportunidad.HojaEncargo__c = hoja.Id;     
        oportunidad.Pricebook2Id = price;
        oportunidad.Office__c = oficina.Id;
        insert oportunidad;
        
        //Añadimos documentos a la oportunidad        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test';      
        cv.PathOnClient ='test';           
        cv.VersionData =blob.valueOf('Test Adjunto');          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=oportunidad.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        insert contentlink;
       
        Opportunity testOpp = [SELECT id FROM Opportunity where name = 'test'];
        
        
        //Creamos un producto
        Product2 prod = new Product2();
            prod.IsActive = true;
            prod.Name = 'TestPrd';
            prod.DocumentosCompletado__c =  '126;127';
            prod.DocumentosContratacion__c = '126;127';
        insert prod;
        
        //Creamos un OpportunityLineItem
        OpportunityLineItem oli = new OpportunityLineItem();
            oli.OpportunityId = testOpp.Id;
            oli.Product2Id = prod.Id;
            oli.Quantity = 1;
            oli.UnitPrice = 100;
        insert oli;
        

        
        System.Test.startTest();
        
            //Pasamos la oportunidad a cerrada/ganada
            oportunidad.StageName = system.label.OportunidadCerragaGanada;
            oportunidad.ProofPaymentDate__c = system.today();
            update oportunidad;
        System.Test.stopTest();
    }
    
    @isTest static void cerrarOportunidadGanadaMenorEdad(){
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        list<Contact> lContactos = [SELECT Id FROM Contact Where AccountId = :cuentaPersonal.id];
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        oportunidad.PrecioTotal__c = 15.2;
        oportunidad.Tipo__c = 'TPV';
        insert oportunidad;
        
        //Funciones de contacto de la oportunidad
        list<OpportunityContactRole> lFuncionesContacto = new list<OpportunityContactRole>();
        OpportunityContactRole funcionContacto = new OpportunityContactRole();
        funcionContacto.OpportunityId = oportunidad.id;
        funcionContacto.ContactId = lContactos.get(0).id;
        funcionContacto.Role = system.label.MenorDeEdad;
        lFuncionesContacto.add(funcionContacto);
        
        OpportunityContactRole funcionContactoRL = new OpportunityContactRole();
        funcionContactoRL.OpportunityId = oportunidad.id;
        funcionContactoRL.ContactId = lContactos.get(0).id;
        funcionContactoRL.Role = system.label.RepresentanteLegal;
        lFuncionesContacto.add(funcionContactoRL);
        
        insert lFuncionesContacto;
        
        //Pasamos la oportunidad a cerrada/ganada
        oportunidad.StageName = system.label.OportunidadCerragaGanada;
        
        System.Test.startTest();
            //Lo ponemos en un try-catch porque estamos probando que nos falla al no tener representante legal
            try{    
                update oportunidad;
            }catch(Exception e){}
        System.Test.stopTest();
    }
    
    @isTest static void cerrarOportunidadGanadaIncapacitado(){
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        list<Contact> lContactos = [SELECT Id FROM Contact Where AccountId = :cuentaPersonal.id];
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.CloseDate = system.today();
        oportunidad.PrecioTotal__c = 15.2;
        oportunidad.Tipo__c = 'TPV';
        insert oportunidad;
        
        //Funciones de contacto de la oportunidad
        list<OpportunityContactRole> lFuncionesContacto = new list<OpportunityContactRole>();
        OpportunityContactRole funcionContacto = new OpportunityContactRole();
        funcionContacto.OpportunityId = oportunidad.id;
        funcionContacto.ContactId = lContactos.get(0).id;
        funcionContacto.Role = system.label.Incapacitado;
        lFuncionesContacto.add(funcionContacto);
        
        OpportunityContactRole funcionContactoRL = new OpportunityContactRole();
        funcionContactoRL.OpportunityId = oportunidad.id;
        funcionContactoRL.ContactId = lContactos.get(0).id;
        funcionContactoRL.Role = system.label.Tutor;
        lFuncionesContacto.add(funcionContactoRL);
        
        insert lFuncionesContacto;
        
        //Pasamos la oportunidad a cerrada/ganada
        oportunidad.StageName = system.label.OportunidadCerragaGanada;
        
        System.Test.startTest();
            //Lo ponemos en un try-catch porque estamos probando que nos falla al no tener representante legal
            try{    
                update oportunidad;
            }catch(Exception e){}
        System.Test.stopTest();
    }
}