force-app/main/default/objects/Account/fields/CorreoElectronicoSecundario__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronicoSecundario__c</fullName>
    <description>Correo electrónico secundario</description>
    <label>Correo electrónico (secundario)</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdOrigen__c.field-meta.xml
<CustomField>
    <fullName>IdOrigen__c</fullName>
    <description>Contiene el identificador del sistema de origen de Arriaga Asociados, utilizado para las cargas iniciales</description>
    <externalId>true</externalId>
    <label>Id Cliente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PoderNotarial__c.field-meta.xml
<CustomField>
    <fullName>PoderNotarial__c</fullName>
    <description>Indica el poder notarial</description>
    <label>Poder notarial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ninguno</fullName>
                <default>true</default>
                <label>Ninguno</label>
            </value>
            <value>
                <fullName>Con facultad de cobro</fullName>
            </value>
            <value>
                <fullName>Sin facultad de cobro</fullName>
            </value>
            <value>
                <fullName>Revocado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CorreoElectronicoSecundario__c.field-meta.xml
<CustomField>
    <fullName>CorreoElectronicoSecundario__c</fullName>
    <description>Correo electrónico secundario para los contactos</description>
    <label>Correo Electrónico Secundario</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto asociado a una cuenta empresarial</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PoderNotarial__c.field-meta.xml
<CustomField>
    <fullName>PoderNotarial__c</fullName>
    <description>Indica el poder notarial</description>
    <label>Poder Notarial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ninguno</fullName>
            </value>
            <value>
                <fullName>Con facultad de cobro</fullName>
            </value>
            <value>
                <fullName>Sin facultad de cobro</fullName>
            </value>
            <value>
                <fullName>Revocado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/EstadoExpedienteComunidad__c.field-meta.xml
<CustomField>
    <fullName>EstadoExpedienteComunidad__c</fullName>
    <description>Contendrá el valor del estado que se mostrará en la comunidad para los usuarios</description>
    <label>Estado expediente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio pagado por el cliente para la contratación de un producto.</description>
    <label>Importe Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio pagado por el cliente para la contratación de un producto.</description>
    <label>Importe Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pago__c/Pago__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela un pago realizado sobre un expediente. Modela los pagos telemático a través de la comunidad así como los pagos físicos en oficinas.</description>
    <label>Pago</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Número de Pago</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pagos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pago__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Estado del pago realizado a la hora de realizar una contratación de un producto</description>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendiente</fullName>
                <default>true</default>
                <label>Pendiente</label>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Emitida</fullName>
                <isActive>false</isActive>
                <label>Emitida</label>
            </value>
            <value>
                <fullName>Pago parcial</fullName>
                <isActive>false</isActive>
                <label>Pago parcial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pago__c/fields/Expediente__c.field-meta.xml
<CustomField>
    <fullName>Expediente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Expediente asociado al pago</description>
    <label>Expediente</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Pagos</relationshipLabel>
    <relationshipName>Pagos</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pago__c/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio pagado por el cliente para la contratación de un producto.</description>
    <label>Importe Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo id externo, el standard de Salesforce no permite realizar operaciones de upsert al no estar definido como externalId</description>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID externo para la carga de campos de documentos</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <masterLabel>TipoDocumento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResyncButtonControllerTest.cls
@isTest
public class ResyncButtonControllerTest {

    @testSetup static void crearCustomSettings() {
        TestAux.crearIntegracionGD();
        TestAux.crearDatosProd();
        TestAux.crearDatosMinerva();
        
        EstadosComunidad__c confEstadosComunidad = new EstadosComunidad__c();
        confEstadosComunidad.Name = '00';
        confEstadosComunidad.Estado__c = 'ESTADO NO DEFINIDO';
        insert confEstadosComunidad;
    }
    
     @isTest static void testFuturoMinervaContacto(){
                
        Account ac = new Account();
            ac.FirstName = 'Test';
            ac.LastName = 'TestII';
            ac.PersonEmail = 'Test@gmail.com';
            ac.CorreoElectronicoSecundario__c = 'TestII@gmail.com';
            ac.Phone = '698523654';
            ac.PersonMobilePhone = '654789632';
            ac.ShippingCity = 'Madrid';
            ac.ShippingCountry = 'España';
            ac.ShippingPostalCode = '28924';
            ac.ShippingState = 'Madrid';
            ac.ShippingStreet = 'Calle del Retiro';
            ac.TipoDocumento__c = 'NIF';
            ac.DocumentoIdentidad__c = '75875743P';
            ac.DeseoRecibirComunicacionesComerciales__pc = true;
            ac.AceptoPoliticaPrivacidad__pc = true;
            ac.Sexo__pc = 'Hombre';
            ac.PoderNotarial__c = 'Sin facultad de cobro';
            ac.IBAN__pc = 'ES1220393718275012191913';
            ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            ac.EstadoCuenta__c='Cliente';
        insert ac;
        
        Contact c = new Contact();
            c.FirstName = 'Test';
            c.LastName = 'TestII';
        insert c;
        
        system.Test.startTest();
            Test.setMock(HttpCalloutMock.class, new TestMinervaRestCallouts.MockHttpResponseMinCrearContacto());
            ResyncButtonController.sendData(ac.Id);
        system.Test.stopTest();                
    }
    
   	
    @isTest static void testFuturoMinervaExpediente(){
                
                Account ac = new Account();
                    ac.FirstName = 'Test';
                    ac.LastName = 'TestII';
                    ac.PersonEmail = 'Test@gmail.com';
                    ac.CorreoElectronicoSecundario__c = 'TestII@gmail.com';
                    ac.Phone = '698523654';
                    ac.PersonMobilePhone = '654789632';
                    ac.ShippingCity = 'Madrid';
                    ac.ShippingCountry = 'España';
                    ac.ShippingPostalCode = '28924';
                    ac.ShippingState = 'Madrid';
                    ac.ShippingStreet = 'Calle del Retiro';
                    ac.TipoDocumento__c = 'NIF';
                    ac.DocumentoIdentidad__c = '75875743P';
                    ac.DeseoRecibirComunicacionesComerciales__pc = true;
                    ac.AceptoPoliticaPrivacidad__pc = true;
                    ac.Sexo__pc = 'Hombre';
                    ac.PoderNotarial__c = 'Sin facultad de cobro';
                    ac.IBAN__pc = 'ES1220393718275012191913';
                    ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
                    ac.EstadoCuenta__c='Cliente';
                	ac.IdOrigen__c = '53000026';
                insert ac;
                
                Contact c = new Contact();
                    c.FirstName = 'Test';
                    c.LastName = 'TestII';
                insert c;
                
                // Se crea Pricebook2, cogiendo el Id de la lista standard
                Pricebook2 standardPricebook = new Pricebook2(
                    Id = Test.getStandardPricebookId(),
                    IsActive = true
                );
                //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
                update standardPricebook;
                
                Product2 prod = new Product2();
                    prod.Name = 'test Prod'; 
                    prod.IsActive = true;
                	prod.ExternalId__c = '52';
                insert prod;
                
                Opportunity opp = new Opportunity();
                    opp.AccountId = ac.id;
                    opp.StageName = 'Prospecting';      
                    opp.Name = 'Test';
                    opp.Pricebook2Id = standardPricebook.id;
                    Opp.CloseDate = date.valueOf(system.now());
                insert opp;
                
                OpportunityContactRole opprole = new OpportunityContactRole();
                    opprole.ContactId = c.Id;
                    opprole.Role = 'Titular';
                    opprole.IsPrimary = true;
                    opprole.OpportunityId = opp.id;
                insert opprole;
                
                OpportunityLineItem oli = new OpportunityLineItem();
                    oli.OpportunityId = opp.Id;
                    oli.Product2Id = prod.Id;
                    oli.Quantity = 1;
                    oli.UnitPrice = 100;
                insert oli;
                
                Opportunity oppNum = [SELECT Id, NumeroExpediente__c FROM Opportunity WHERE Id =:opp.Id];
                
                Contract Exp = new Contract();
                    Exp.AccountId = ac.Id;
                    Exp.Pricebook2Id = standardPricebook.id;
                    Exp.IdExpediente__c = oppNum.NumeroExpediente__c;
                    Exp.Oportunidad__c = oppNum.id;
                    Exp.Status='';
                    Exp.EstadoExpedienteComunidad__c='';                    
                insert Exp;
                
                Pago__c pago = new Pago__c();
                    pago.Expediente__c = Exp.Id;
                    pago.PrecioTotal__c = 100;
                    pago.Estado__c = Label.EstadoPagoConfirmado;
                insert pago;
                
                
                Map<String, Id> mDatosExpyCuenta = new Map<String, Id>();
                	mDatosExpyCuenta.put(Exp.IdExpediente__c, Exp.AccountId);
                
                
                system.Test.startTest();
                	Test.setMock(HttpCalloutMock.class, new TestMinervaRestCallouts.MockHttpResponseMinCrearExp());
                	ResyncButtonController.sendData(Exp.Id);
                system.Test.stopTest();                
            }
    
    		@isTest static void tetsNull(){
                
           
                system.Test.startTest();
                	Test.setMock(HttpCalloutMock.class, new TestMinervaRestCallouts.MockHttpResponseMinCrearExp());
                	ResyncButtonController.sendData(null);
                system.Test.stopTest();                
            }

    
}