force-app/main/default/objects/Account/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto asociado a una cuenta empresarial</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <masterLabel>TipoDocumento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/wrapperOpportunityContactRole.cls
/*Wrapper class con los datos de las funciones de contacto de la oportunidad

FECHA		AUTOR		DESCRIPCION
04/06/2019	LCS -RMG	Creación. Se usa en clase aparte porque sino el componente no puede llamar a la wraper class de dentro de otra clase. Se usa para la generación de la hoja de encargo.
                        No se puede usar directamente el objeto de funciones de contacto de la oportunidad porque el usuario de la comunidad no tiene acceso a esos datos
23/08/2019  LCS - RMG   Modificación. Se añade la variable de tipo de docmento de identidad

*/

public class wrapperOpportunityContactRole{
    public string idRole {get;set;}
    public string role {get;set;}
    public string contactoNombre {get;set;}
    public string contactoTipoDocumentoIdentidad {get;set;}
    public string contactoDocumentoIdentidad {get;set;}
    public string contactoCiudad {get;set;}
    public string contactoTelefono {get;set;}
    public string contactoEmail {get;set;}
    
    public wrapperOpportunityContactRole (){}
    
    public wrapperOpportunityContactRole (OpportunityContactRole oppContactRole){
        idRole = oppContactRole.id;
        role = oppContactRole.Role;
        contactoNombre = oppContactRole.Contact.Name;
        contactoTipoDocumentoIdentidad = oppContactRole.Contact.Account.TipoDocumento__c;
        contactoDocumentoIdentidad = oppContactRole.Contact.Account.DocumentoIdentidad__c;
        contactoCiudad = oppContactRole.Contact.Account.ShippingCity;
        contactoTelefono = oppContactRole.Contact.Account.Phone;
        contactoEmail = oppContactRole.Contact.email;
    }        
}