force-app/main/default/objects/Account/fields/DocumentoIdentidad__c.field-meta.xml
<CustomField>
    <fullName>DocumentoIdentidad__c</fullName>
    <complianceGroup>GDPR;LOPD</complianceGroup>
    <description>Documento de identidad (DNI) del contacto</description>
    <label>Documento Identidad</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/DatosFlujo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Datos que se utilizan en el flujo de Gastos Hipotecarios</description>
    <label>Datos Flujo</label>
</CustomObject>

force-app/main/default/objects/DatosFlujo__c/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta en la creación</description>
    <label>Estado Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IdPropietarioSegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>IdPropietarioSegundoTitular__c</fullName>
    <description>Id del usuario que va a ser el propietario de la cuenta del segundo titular</description>
    <label>IdPropietarioSegundoTitular</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IDTipoRegistroCuentaPersonal__c.field-meta.xml
<CustomField>
    <fullName>IDTipoRegistroCuentaPersonal__c</fullName>
    <description>Id del tipo de registro de las cuentas personales</description>
    <label>IDTipoRegistroCuentaPersonal</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/RolSegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>RolSegundoTitular__c</fullName>
    <description>Rol que se pone al contacto en la oportunidad que se crea como segundo titular</description>
    <label>Rol Segundo Titular</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <masterLabel>TipoDocumento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Flow_CrearSegundoTitular.cls
/*
@author LeadClic Solutions S.L.
@date 02/04/2019
@description Clase que crea una cuenta personal con la información del segundo titular

<pre>
FECHA                 AUTOR           ACCION
02/04/2019			LCS - RMG		 Creación.
22/04/2019			LCS - RDM		 Modificación. Se añade la creación del rol de la oportunidad para la nueva cuenta creada.
17/07/2019			LCS - RDM		 Modificación. Se añade el tipo de documento a la hora de crear la cuenta
26/08/2019          LCS - RMG        Modificación. Se añaden nuevos parámetros para crear los roles de las oportunidades desde código ya que se necesita que sea without sharing
                                                    para que al usuario de la comunidad no le de error.
 
*/
global without sharing class Flow_CrearSegundoTitular {
    /**
     *  Método invocable desde los flujos. Utilizamos una lista de una wrapper class de datos enviados desde el flujo. 
     *  
     * 
     * @param  dni	dato procedente del flujo con la información proporcionado por el titular de la reclamación
     * @param  nombre dato procedente del flujo con la información proporcionado por el titular de la reclamación
     * @param  email dato procedente del flujo con la información proporcionado por el titular de la reclamación
     * @param  telefono dato procedente del flujo con la información proporcionado por el titular de la reclamación
     * @return	Devuelve el Id de la cuenta personal que se ha creado
     * 
     */
    @InvocableMethod(label='Llamada flujo' description='Llamada desde el flujo')
    public static list<id> MetodoInvocable (list<GetParameters> WrapperParams){
        //Lista con los resultados que recibe el flujo
        list<Id> resultado = new list<Id>();
        //Recuperamos la configuración personalizada con los parámetros que son fijos para la creación de la cuenta
        DatosFlujo__c datosFlujo = DatosFlujo__c.getOrgDefaults();
        
        //Si nos mandan el id de la cuenta del segundo titular no se tiene que crear ninguna cuenta nueva, solo hace falta crear el rol
        if(WrapperParams[0].IdCuentaSegundoTitular != null ){
            //Nos movemos al método que inserta el Rol indicado en la configuración personalizada al segundo titular
            rolSegundoTitular(WrapperParams[0].IdCuentaSegundoTitular, datosFlujo.RolSegundoTitular__c, WrapperParams[0].IdOportunidad);
            resultado.add(WrapperParams[0].IdCuentaSegundoTitular);
        }else{
            //Cuenta que se crea para el segundo titular de la reclamación
            Account cuentaNueva = new Account();  
            cuentaNueva.TipoDocumento__c = (String) WrapperParams[0].tipoDocumento;       
            cuentaNueva.DocumentoIdentidad__c = (String) WrapperParams[0].dni;
            cuentaNueva.EstadoCuenta__c = datosFlujo.EstadoCuenta__c;
            cuentaNueva.FirstName = (String) WrapperParams[0].nombre;
            cuentaNueva.LastName = (String) WrapperParams[0].nombre;
            cuentaNueva.PersonEmail = (String) WrapperParams[0].email;
            cuentaNueva.Phone = (String) WrapperParams[0].telefono;
            cuentaNueva.RecordTypeId = datosFlujo.IDTipoRegistroCuentaPersonal__c;
            cuentaNueva.OwnerId = datosFlujo.IdPropietarioSegundoTitular__c;
            insert cuentaNueva;
            
        /* system.debug('Oportunidad : ' + WrapperParams[0].IdOportunidad);
            system.debug('CuentaNueva : ' + cuentaNueva.Id);
            system.debug('Rol : ' + datosFlujo.RolSegundoTitular__c);*/
            
            //Nos movemos al método que inserta el Rol indicado en la configuración personalizada al segundo titular
            rolSegundoTitular(cuentaNueva.Id, datosFlujo.RolSegundoTitular__c, WrapperParams[0].IdOportunidad);
            resultado.add(cuentaNueva.id);
        }
        
        return resultado;
    }
    /*
     * @descripción Wrapper class que recibe los datos de entrada del flujo
     */ 
    global class GetParameters {
        
        @InvocableVariable( label = 'tipoDocumento' description = 'tipoDocumento' required=true )
        global String tipoDocumento; 
        
        @InvocableVariable( label = 'dni' description = 'dni' required=true )
        global String dni;  
        
        @InvocableVariable( label = 'nombre' description = 'nombre' required=true )
        global String nombre;  
        
        @InvocableVariable( label = 'email' description = 'email' required=true )
        global String email;  
        
        @InvocableVariable( label = 'telefono' description = 'telefono' required=false )
        global String telefono; 
        
        @InvocableVariable( label = 'IdOportunidad' description = 'Id oportunidad que usaremos para indicar el rol del nuevo contacto' required=true )
        global String IdOportunidad;  

        @InvocableVariable( label = 'IdCuentaSegundoTitular' description = 'Id de la cuenta del segundo titular' required=false )
        global String IdCuentaSegundoTitular;  
    }
    /**
     *  Método  
     *  
     * 
     * @param  dni	dato procedente del flujo con la información proporcionado por el titular de la reclamación
     * 
     */
      public static void rolSegundoTitular (Id CuentaSegundoTit, string Rol, Id Oportunidad){          
          //Recuperamos el id y el id de personCOntact que utilizaremos para crear el rol de opp
          Account cuentaContrato = [SELECT Id, personContactId FROM Account WHERE Id =: CuentaSegundoTit];
          //system.debug('CuentaNueva : ' + cuentaContrato.personContactId);
          //Función de contacto
          OpportunityContactRole rolContacto = new OpportunityContactRole();
              rolContacto.OpportunityId = Oportunidad;
              rolContacto.ContactId = cuentaContrato.personContactId;
              rolContacto.Role = Rol;
              rolContacto.IsPrimary = false;
          insert rolContacto;
          
      }
    
}