force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrecioTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecioTotal__c</fullName>
    <description>Precio pagado por el cliente para la contratación de un producto.</description>
    <label>Importe Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestRecibiController.cls
/*
@author Leadclic Solutions S.L.
@date 02/08/2019
@description Clase test para la clase controladora para el PDF recibí

FECHA               AUTOR   
02/08/2019			LCS - RDM		Creación.
04/09/2019			LCS - RDM		 Modificación. Subida de % de cobertura

*/
@isTest
public class TestRecibiController {

    @isTest static void getParam(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        	cuentaPersonal.FirstName = 'Testss';
        cuentaPersonal.recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@email.com';
        cuentaPersonal.EstadoCuenta__c='Cliente';
        cuentaPersonal.LastName = 'Test';
        insert cuentaPersonal;
        
        //Creamos la oportunidad
        Opportunity oportunidad = new Opportunity();
        oportunidad.AccountId = cuentaPersonal.id;
        oportunidad.StageName = system.label.OportunidadCalificacion;
        oportunidad.Name = 'test';
        oportunidad.PrecioTotal__c = 150.00;
        oportunidad.Tipo__c = 'TPV';
        oportunidad.CloseDate = system.today();
        insert oportunidad;
        
        system.Test.startTest();
        
        	RecibiController recibi = new RecibiController();
        		recibi.idOpp = oportunidad.id;
        		recibi.getDatosOpp();
        
        system.Test.stopTest();        
    }
    
     @isTest static void catchParams(){        
        system.Test.startTest();
        
        	RecibiController recibi = new RecibiController();
        		recibi.idOpp = null;
        		recibi.getDatosOpp();
        
        system.Test.stopTest();        
    }
    
}