force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/DatosFlujo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Datos que se utilizan en el flujo de Gastos Hipotecarios</description>
    <label>Datos Flujo</label>
</CustomObject>

force-app/main/default/objects/DatosFlujo__c/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta en la creación</description>
    <label>Estado Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/EtapaOEtapaOportuniportunidadContrOnline__c.field-meta.xml
<CustomField>
    <fullName>EtapaOEtapaOportuniportunidadContrOnline__c</fullName>
    <description>Etapa de creación de la oportunidad</description>
    <label>EtapaOportunidadContrOnline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IdPropietarioSegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>IdPropietarioSegundoTitular__c</fullName>
    <description>Id del usuario que va a ser el propietario de la cuenta del segundo titular</description>
    <label>IdPropietarioSegundoTitular</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IDTipoRegistroCuentaPersonal__c.field-meta.xml
<CustomField>
    <fullName>IDTipoRegistroCuentaPersonal__c</fullName>
    <description>Id del tipo de registro de las cuentas personales</description>
    <label>IDTipoRegistroCuentaPersonal</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFlow_CrearSegundoTitular.cls
/*
@author LeadClic Solutions S.L.
@date 03/04/2019
@description Clase Test para la clase Flow_CrearSegundoTitular

<pre>
FECHA                 AUTOR           ACCION
03/04/2019			LCS - RMG		 Creación.
22/04/2019			LCS - RDM		 Modificación. Se añade la creación de la opp para poder pasar por las lineas de la creación del rol de la oportunidad para la nueva cuenta creada.
04/09/2019			LCS - RDM		 Modificación. Subida de % de cobertura
31/03/2020			LCS - RAL		 Modificación. Se añade el teléfono en la creación de cuenta

*/
@isTest
public class TestFlow_CrearSegundoTitular {
    
    @testSetup static void crearCustomSettings(){
        DatosFlujo__c flujo = new DatosFlujo__c();
            flujo.IDTipoRegistroCuentaPersonal__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            flujo.EstadoCuenta__c = 'Cliente Potencial';
            flujo.IdPropietarioSegundoTitular__c = system.UserInfo.getUserId();
            flujo.EtapaOEtapaOportuniportunidadContrOnline__c = 'Prospecting';
        insert flujo;  
    }

    @isTest
    static void TestCrearSegundoTitular(){         
        
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.IdClienteMinerva__c = '0000001';
        	ac.Phone = '60000000';
        insert ac;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        

        Flow_CrearSegundoTitular.GetParameters request = new Flow_CrearSegundoTitular.GetParameters();
        List<Flow_CrearSegundoTitular.GetParameters> listRequest = new List<Flow_CrearSegundoTitular.GetParameters>();
                
        request.dni = '83676973Y';
        request.nombre = 'Test';
        request.email = 'test@test.com';
        request.telefono = '666666666';
        request.IdOportunidad = opp.id;
        listRequest.add(request);
        
        system.Test.startTest();
        	Flow_CrearSegundoTitular.MetodoInvocable(listRequest);
        system.Test.stopTest();
    }

    @isTest
    static void TestExisteSegundoTitular(){         
        
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.IdClienteMinerva__c = '0000123';
        	ac.Phone = '60000000';
        insert ac;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        

        Flow_CrearSegundoTitular.GetParameters request = new Flow_CrearSegundoTitular.GetParameters();
        List<Flow_CrearSegundoTitular.GetParameters> listRequest = new List<Flow_CrearSegundoTitular.GetParameters>();
                
        request.dni = '83676973Y';
        request.nombre = 'Test';
        request.email = 'test@test.com';
        request.telefono = '666666666';
        request.IdOportunidad = opp.id;
        request.IdCuentaSegundoTitular = ac.id;
        listRequest.add(request);
        
        system.Test.startTest();
        	Flow_CrearSegundoTitular.MetodoInvocable(listRequest);
        system.Test.stopTest();
    }
}