force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/CommunityOpp__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela las oportunidades para Comunidades.</description>
    <label>Contratación Online</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Contratación Online</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrataciones Online</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunityOpp__c/fields/CantidadPagar__c.field-meta.xml
<CustomField>
    <fullName>CantidadPagar__c</fullName>
    <description>Cantidad a pagar. Campo obtenido de la lista de precios.</description>
    <label>Cantidad a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/ContrFinalizado__c.field-meta.xml
<CustomField>
    <fullName>ContrFinalizado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que indica si la contratación ha sido finalizada</description>
    <label>Contratación finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cliente asociado a la contratación online</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IdOportunidad__c.field-meta.xml
<CustomField>
    <fullName>IdOportunidad__c</fullName>
    <description>Campo donde guardamos el Id de la oportunidad para poder recogerla desde la comunidad.</description>
    <label>IdOportunidad</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IDProducto__c.field-meta.xml
<CustomField>
    <fullName>IDProducto__c</fullName>
    <description>Id del producto asignado a la contratación online. Se guarda para poder utilizarlo en comprobaciones dentro de la comunidad</description>
    <label>ID Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup que relaciona los objetos de contratacion online y oportunidad.</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/DatosFlujo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Datos que se utilizan en el flujo de Gastos Hipotecarios</description>
    <label>Datos Flujo</label>
</CustomObject>

force-app/main/default/objects/DatosFlujo__c/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta en la creación</description>
    <label>Estado Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/EtapaOEtapaOportuniportunidadContrOnline__c.field-meta.xml
<CustomField>
    <fullName>EtapaOEtapaOportuniportunidadContrOnline__c</fullName>
    <description>Etapa de creación de la oportunidad</description>
    <label>EtapaOportunidadContrOnline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IdPropietarioSegundoTitular__c.field-meta.xml
<CustomField>
    <fullName>IdPropietarioSegundoTitular__c</fullName>
    <description>Id del usuario que va a ser el propietario de la cuenta del segundo titular</description>
    <label>IdPropietarioSegundoTitular</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/IDTipoRegistroCuentaPersonal__c.field-meta.xml
<CustomField>
    <fullName>IDTipoRegistroCuentaPersonal__c</fullName>
    <description>Id del tipo de registro de las cuentas personales</description>
    <label>IDTipoRegistroCuentaPersonal</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdProducto__c.field-meta.xml
<CustomField>
    <fullName>IdProducto__c</fullName>
    <description>Id del producto en el que está  interesado para cuando se introduce un candidato a través de un formulario Web. Se guarda esta información en la oportunidad para en el trigger posteriormente crear el producto de la oportunidad</description>
    <label>Id Producto</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFlow_ActualizarContratOnline.cls
/*
@author LeadClic Solutions S.L.
@date 18/06/2019
@description Clase Test para la clase que actualiza la contratación Online al crear 2ºTitular o encontrar ya otro contacto

<pre>
FECHA                 AUTOR           ACCION
18/06/2019			LCS - RDM		 Creación
04/09/2019			LCS - RDM		 Modificación. Subida de % de cobertura
*/
@isTest
public with sharing class TestFlow_ActualizarContratOnline {
    
    @testSetup static void crearCustomSettings(){
        DatosFlujo__c flujo = new DatosFlujo__c();
            flujo.IDTipoRegistroCuentaPersonal__c = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
            flujo.EstadoCuenta__c = 'Cliente Potencial';
            flujo.IdPropietarioSegundoTitular__c = system.UserInfo.getUserId();
            flujo.EtapaOEtapaOportuniportunidadContrOnline__c = 'Prospecting';
        insert flujo;  
    }

    @isTest
    static void TestCrearSegundoTitular(){
                 
        
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.PersonEmail = 'test111@test.com';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.IdClienteMinerva__c = '12345';
        insert ac;

        Account segTit = new Account();
        	segTit.FirstName = 'Test2';
        	segTit.LastName = 'Test2';
        	segTit.PersonEmail = 'test112@test.com';
        	segTit.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	segTit.EstadoCuenta__c='Cliente';
        	segTit.IdClienteMinerva__c = '12346'; 
        insert segTit;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        Product2 prod2 = new Product2();
            prod2.Name = 'test Prod2'; 
            prod2.IsActive = true;
        insert prod2;
        
        PricebookEntry pb = [SELECT Id, Product2Id, UnitPrice FROM PricebookEntry WHERE Product2Id = :prod.id LIMIT 1];
        
        /*
        PriceBookEntry pb = new PriceBookEntry();
        	pb.Product2Id = prod.id;
        	pb.Pricebook2Id = standardPricebook.id;
        	pb.IsActive = true;
        	pb.UnitPrice = 1000;
        insert pb; 
*/
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;    
            opp.Name = 'Test';
            opp.StageName = 'Prospecting';
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        

        Flow_ActualizarContratOnline.GetParameters request = new Flow_ActualizarContratOnline.GetParameters();
        List<Flow_ActualizarContratOnline.GetParameters> listRequest = new List<Flow_ActualizarContratOnline.GetParameters>();
                
        request.idContratOnline = ContratOnline.id;
        request.consentimientoSegTit = 'SI';
        request.emailSegTit = 'test1252@test.com';
        request.segTit = segTit.Id;
        request.tieneVariosTit = 'Sí, hay otro titular y está informado';
        listRequest.add(request);
        
        system.Test.startTest();
        	Flow_ActualizarContratOnline.metodoInvocable(listRequest);
        system.Test.stopTest();
    }
    
}