force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en el expediente el id del cliente para enviárselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GDDocumentSummaryControllerTest.cls
/*
@author LeadClic Solutions S.L.
@date 17/10/2023
@description Clase GDDocumentSummaryControllerTest: test unitarios para la clase GDDocumentSummaryController.
<pre>
FECHA             AUTOR           ACCION
17/10/2023		LCS - SDF	   	  Creación.
*/
@isTest
private class GDDocumentSummaryControllerTest {
    static User communityUser;
    static Contract expedient;

    static {
        EstadosComunidad__c confEstadosComunidad = new EstadosComunidad__c();
        confEstadosComunidad.Name = '00';
        confEstadosComunidad.Estado__c = 'ESTADO NO DEFINIDO';
        insert confEstadosComunidad;
        Profile p = [SELECT Id From Profile Where Name = 'Comunidad Arriaga'];
        if (UserInfo.getUserRoleId() == null) {
            System.runAs(new User(Id = UserInfo.getUserId())) {
                User userWithRole = [SELECT Id,UserRoleId FROM User WHERE UserRoleId != null LIMIT 1];
                update new User(Id = UserInfo.getUserId(), UserRoleId = userWithRole.UserRoleId);
            }
        }
        Account ac = new Account();
        	ac.name = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.IdClienteMinerva__c = '12345';
            ac.Phone = '654987321';
        insert ac;
        Contact cont = new Contact();
        	cont.accountId = ac.Id;
            cont.FirstName = 'NombreT';
            cont.lastName = 'Test';
            cont.MailingCountry = 'ESPAÑA';
            cont.MobilePhone =  '0034123456789';
            cont.Phone = '0034123456789';
            cont.Email = 'test.sz@example.com';
        insert cont;
    	//Crear usuario
        communityUser = new User(
            ContactId = cont.Id,
            FirstName = cont.FirstName,
            LastName = cont.LastName,
            IsActive = true,
            EmailEncodingKey = 'ISO-8859-1',
            Email = cont.Email,
            Username = cont.Email,
            CommunityNickname = cont.Email,
            Phone = cont.Phone,
            Alias = cont.FirstName,
            ProfileId = p.id,
            TimeZoneSidKey = 'Europe/Paris',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es_ES'
        );
        insert communityUser; 

        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = 'Prospecting';      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        
        OpportunityContactRole opprole = new OpportunityContactRole();
            opprole.ContactId = cont.Id;
            opprole.Role = 'Titular';
            opprole.IsPrimary = true;
            opprole.OpportunityId = opp.id;
        insert opprole;
        
        //declaramos un expediente base
        expedient = new Contract();
        expedient.AccountId = ac.Id;
        expedient.Pricebook2Id = standardPricebook.id;
        expedient.IdExpediente__c = opp.NumeroExpediente__c;
        expedient.Oportunidad__c = opp.id;
        expedient.IdExpediente__c = '11111';   
    }

    @isTest
    private static void whenExpedientIdIsNullOrBlankItShouldThrowAnExceltion() {
        GDDocumentSummaryController.GDDocumentSummaryResponse response;
        String message;

        Test.startTest();
        System.runAs(communityUser) {
            response = GDDocumentSummaryController.getDocumentSumary(null);
        }
        Test.stopTest();

        Assert.areEqual(LightningDataResponse.ERROR, response.status, 'must be an error');
        Assert.areEqual(GDDocumentSummaryController.INVALID_ID, response.message, 'message should be populated with exception message');
    }

    @isTest
    private static void whenWeCallTheControllerWithInvalidSObjectItShouldThrowAnException() {
        GDDocumentSummaryController.GDDocumentSummaryResponse response;
        String message;

        Test.startTest();
        System.runAs(communityUser) {
            response = GDDocumentSummaryController.getDocumentSumary(UserInfo.getUserId());
        }
        Test.stopTest();

        Assert.areEqual(LightningDataResponse.ERROR, response.status, 'must be an error');
        Assert.areEqual(GDDocumentSummaryController.INVALID_SOBJECT_TYPE, response.message, 'message should be populated with exception message');
    }

    @isTest
    private static void whenCommunityUserCallTheControllerItShouldPopulateTheDataResponse() {
        GDDocumentSummaryController.GDDocumentSummaryResponse response;
        expedient.DocumentosRedaccion__c = '167;32;';
        expedient.DocumentosRedaccionAportados__c = '167';
        expedient.DocumentosAdicionales__c = '187';
        expedient.DocumentosAdicionalesAportados__c = '187';
        insert expedient;

        Test.startTest();
        System.runAs(communityUser) {
            response = GDDocumentSummaryController.getDocumentSumary(expedient.Id);
        }
        Test.stopTest();

        Assert.areEqual(LightningDataResponse.SUCCESS, response.status, 'must be success response');
        Assert.IsNotNull(response.data, 'data should be populated');
        Assert.areEqual(3, response.data.documentLines.size(),'there must be 3 document line');
    }
}