force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Activo__c/Activo__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela los bienes asociados a un Expediente</description>
    <label>Activo</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Número de Activo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ArrMinervDatosWS__c/ArrMinervDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Minerva de Arriaga</description>
    <label>ArriagaMinerva_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrMinervDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check de control que indica si la configuración puede o no usarse</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/ArrProdDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Producción de Arriaga</description>
    <label>ArriagaProduccion_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrProdDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que marca si el entorno esta activo para realizar peticiones</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtContc__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtContc__c</fullName>
    <label>EndpointCrear</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtExp__c</fullName>
    <description>Endpoint del entorno de producción para crear expedientes</description>
    <label>EndpointCrearExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointUpdtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointUpdtExp__c</fullName>
    <description>Endpoint del entorno de producción para actualizar un expediente</description>
    <label>EndpointActulizarExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>PrivateKey__c</fullName>
    <description>Clave privada generada por Producción de Arriaga</description>
    <label>PrivateKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PublicKey__c.field-meta.xml
<CustomField>
    <fullName>PublicKey__c</fullName>
    <description>Clave publica utilizada para llegar al WS</description>
    <label>PublicKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DocumentacinBasicaAportada__c.field-meta.xml
<CustomField>
    <fullName>DocumentacinBasicaAportada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que se marcará cuando la documentación se aportada</description>
    <label>Documentación básica aportada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Documentación aportada para el estado inicial</description>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en el expediente el id del cliente para enviárselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/PagoConfirmado__c.field-meta.xml
<CustomField>
    <fullName>PagoConfirmado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que se marcará cuando el pago pase a estado &apos;Confirmado&apos;</description>
    <label>Pago confirmado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/ParteContraria__c.field-meta.xml
<CustomField>
    <fullName>ParteContraria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Empresa o particular contra el que se actúa en este expediente</description>
    <label>Parte contraria</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos (Parte contraria)</relationshipLabel>
    <relationshipName>Contrario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <description>Tipo de expediente común</description>
    <label>General</label>
</RecordType>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/IntegracionSF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración encargada de guardar los datos necesarios para poder obtener el token de la instacia de SF y de esta manera poder conectarnos con la misma instancia</description>
    <label>IntegracionSF</label>
</CustomObject>

force-app/main/default/objects/IntegracionSF__c/fields/UsuarioIntegracionId__c.field-meta.xml
<CustomField>
    <fullName>UsuarioIntegracionId__c</fullName>
    <description>Identificador del usuario de integración de arriaga para controlar cambios que haga</description>
    <label>Usuario Integración Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Documentos que se deben aportar en el primer estado</description>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DocumentosCompletadoAportado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletadoAportado__c</fullName>
    <description>Documentación aportada para el estado inicial</description>
    <label>Documentos completado básico aportado</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/DocumentosCompletado__c.field-meta.xml
<CustomField>
    <fullName>DocumentosCompletado__c</fullName>
    <description>Lista de documentos que debe completar el asesor</description>
    <inlineHelpText>Lista de documentos que debe completar el asesor</inlineHelpText>
    <label>Documentos para completado básico</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTriggerContract.cls
/*
@author LeadClic Solutions S.L.
@date 10/04/2019
@description Trigger para el objeto Expediente(Contract)

<pre>
FECHA             AUTOR           ACCION
17/04/2019		LCS - RDM	   	  Creación.
06/05/2019		LCS - RMG		  Modificación. Se añade la parte de conflicto de interés
04/09/2019		LCS - RDM		  Modificación. Subida de % de cobertura
09/01/2020      LCS - MMV         Modificación. Arreglar errores
27/01/2020      LCS - MMV         Modificación. Añadir Custom setting
13/08/2021      LCS - DRA         Modificación. Añadir Custom setting EstadosComunidad__c en el testsetup
 
*/
@isTest
public class TestTriggerContract {
    
    @testSetup static void crearCustomSettings(){
        //Configuración personalizada  
        ArrMinervDatosWS__c confPer = new ArrMinervDatosWS__c();
        confPer.name = 'General';
        confPer.Activo__c = true;
        
        
        ArrProdDatosWS__c cs = new ArrProdDatosWS__c();
        cs.name = 'General';
        cs.Activo__c = true;
        cs.PrivateKey__c = 'XXXX';
        cs.PublicKey__c = 'XXXX';
        cs.EndpointInsrtContc__c = 'test';
        cs.EndpointInsrtExp__c = 'sad';
        cs.EndpointUpdtExp__c = 'ass';
        
        insert cs;
       	insert confPer;

        IntegracionSF__c confIntegracionSF = new IntegracionSF__c();
        confIntegracionSF.Name = 'General';
        confIntegracionSF.UsuarioIntegracionId__c = '0051t000003IpmE';
        insert confIntegracionSF;

        EstadosComunidad__c confEstadosComunidad = new EstadosComunidad__c();
        confEstadosComunidad.Name = '00';
        confEstadosComunidad.Estado__c = 'ESTADO NO DEFINIDO';
        insert confEstadosComunidad;
    }

    static testMethod  void CrearExpediente(){
        
        Account ac = new Account();
        	ac.name = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.IdClienteMinerva__c = '12345';
            ac.Phone = '654987321';
        insert ac;
        
        Contact c = new Contact();
        	c.FirstName = 'Test';
        	c.LastName = 'TestII';
        insert c;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = 'Prospecting';      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        
        OpportunityContactRole opprole = new OpportunityContactRole();
            opprole.ContactId = c.Id;
            opprole.Role = 'Titular';
            opprole.IsPrimary = true;
            opprole.OpportunityId = opp.id;
        insert opprole;
        
        list<Contract> lExp = new list<Contract>();
            Contract Exp = new Contract();
                Exp.AccountId = ac.Id;
                Exp.Pricebook2Id = standardPricebook.id;
                Exp.IdExpediente__c = opp.NumeroExpediente__c;
                Exp.Oportunidad__c = opp.id;
        		Exp.IdExpediente__c = '11111';
        		
        lExp.add(Exp);
            Contract Expediente = new Contract();
                Expediente.AccountId = ac.Id;
                Expediente.Pricebook2Id = standardPricebook.id;
                Expediente.IdExpediente__c = opp.NumeroExpediente__c;
                Expediente.Oportunidad__c = opp.id;
        		Expediente.IdExpediente__c = '22222';
        lExp.add(Expediente);
                 
        system.Test.startTest();
        	insert lExp;
        system.Test.stopTest();
        
        
    }
    
    static testMethod  void ConflictoInteres(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@test.com';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        cuentaPersonal.EstadoCuenta__c = 'Cliente Potencial';
        cuentaPersonal.IdClienteMinerva__c = '00002';
        insert cuentaPersonal;
        
        Account Personal =[SELECT PersonContactId 
                          FROM Account
                          WHERE Id =: cuentaPersonal.Id
                          LIMIT 1 ];	
        
        //Creación del expediente
        Contract Exp = new Contract();
        Exp.AccountId = cuentaPersonal.Id;
        Exp.DocumentosCompletadoAportado__c = '126;42';
        Exp.DocumentosCompletado__c = '126';
        Exp.DocumentacinBasicaAportada__c = true;
        Exp.PagoConfirmado__c = true;
        Exp.IdExpediente__c = '333333';
        insert exp;
        
        //Modificación del expediente para asignar la cuenta que es parte contraria
        exp.ParteContraria__c = cuentaPersonal.id;
        
        //Creamos la función de contacto del contrato
        ContractContactRole ccr = new ContractContactRole();
        ccr.ContractId = exp.Id;
        ccr.ContactId = Personal.PersonContactId;
        insert ccr;
        
        system.test.startTest();
        	//Actualizamos el expediente que tiene ya informado el campo de parte contraria
        	update exp;
        system.Test.stopTest();
    }
    
     static testMethod  void ConflictoInteres200(){
        //Creamos la cuenta personal
        Account cuentaPersonal = new Account();
        cuentaPersonal.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        cuentaPersonal.PersonEmail = 'test@test.com';
        cuentaPersonal.FirstName = 'Tesst';
        cuentaPersonal.LastName = 'Test';
        cuentaPersonal.EstadoCuenta__c = 'Cliente Potencial';
         cuentaPersonal.IdClienteMinerva__c = '00001';
        insert cuentaPersonal;
        
        Account Personal =[SELECT PersonContactId 
                          FROM Account
                          WHERE Id =: cuentaPersonal.Id
                          LIMIT 1 ];	
        
        //Creación del expediente
        list<Contract> lContratos = new list<Contract>();
         for(integer i=0; i<200;i++){
        	Contract Exp = new Contract();
        	Exp.AccountId = cuentaPersonal.Id;
        	lContratos.add(exp);
         }
         
         insert lContratos;
        
        //Modificación del expediente para asignar la cuenta que es parte contraria
        //Creamos la función de contacto del contrato
        list<ContractContactRole> lFuncionContacto = new list<ContractContactRole>();
         for(Contract exp :lContratos){
        	exp.ParteContraria__c = cuentaPersonal.id;
             
            ContractContactRole ccr = new ContractContactRole();
        	ccr.ContractId = exp.Id;
        	ccr.ContactId = Personal.PersonContactId;
             lFuncionContacto.add(ccr);
        }       
        
        insert lFuncionContacto;
        
        system.test.startTest();
        	//Actualizamos el expediente que tiene ya informado el campo de parte contraria
        	update lContratos;
        system.Test.stopTest();
    }
}