force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/HojaEncargo__c.object-meta.xml
<CustomObject>
    <description>Plantilla de hoja de encargo para guardar los valores que se traspasan a la oferta en función de la tipología de contratación.</description>
    <label>Hoja de Encargo</label>
    <nameField>
        <label>Nombre de Hoja de Encargo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hojas de Encargo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HojaEncargo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo identificador externo para realizar la carga de las hojas de encargo. También machea con un maestro de Hde suministrado via Drive por Arriaga</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFDatosArriaga__c.field-meta.xml
<CustomField>
    <fullName>PDFDatosArriaga__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <inlineHelpText>Datos de Arriaga , del Cliente y del producto</inlineHelpText>
    <label>Datos de Arriaga</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFDesistimiento__c.field-meta.xml
<CustomField>
    <fullName>PDFDesistimiento__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <label>Desistimiento</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/HojaEncargo__c/fields/PDFHonorarios__c.field-meta.xml
<CustomField>
    <fullName>PDFHonorarios__c</fullName>
    <description>Bloque que contiene los datos de Arriaga que se muestran en el PDF de la hoja de encargo</description>
    <label>Honorarios</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HojaEncargo__c.field-meta.xml
<CustomField>
    <fullName>HojaEncargo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contiene la relación con la hoja de encargo correspondiente. Completado en el momento de la selección de la tipología de esta. De este objeto se trasladaran valores a la oportunidad.</description>
    <label>Hoja de Encargo</label>
    <referenceTo>HojaEncargo__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestPDFHojaEncargo.cls
/*
Test de la clase de PDFHojaEncargo

FECHA		AUTOR		DESCRIPCION
14/06/2019	LCS -RMG	Creación
04/09/2019	LCS - RDM	Modificación. Subida de % de cobertura
31/03/2020  LCS - RAL   Modificación. Se añade el número de teléfono a la cuenta

*/
@isTest
public class TestPDFHojaEncargo {
    
    static testmethod void hojaEncargo(){
        //Crear Cuenta Personal
        Account ac = new Account();
        	ac.FirstName = 'Test';
        ac.LastName= 'CuentaTest';
        ac.EstadoCuenta__c='Cliente';	
        ac.IdClienteMinerva__c = '1234';
        ac.Phone = '600000000';
        ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        insert ac;
        
        Account PersonContactId= [SELECT PersonContactId
                                	FROM Account 
                                	WHERE Id =: ac.Id];
        
        //Crear Cuenta Personal
        Account tutor = new Account();
        tutor.FirstName= 'CuentasTest';
        tutor.LastName= 'CuentaTest';
        tutor.EstadoCuenta__c='Cliente';	
        tutor.IdClienteMinerva__c = '4321';
        tutor.Phone = '600000000';
        tutor.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        insert tutor;
        
        Account tutorCuentaPersonal = [SELECT PersonContactId
                                	FROM Account 
                                	WHERE Id =: tutor.Id];
        
        //Crear Hoja de encargo
        HojaEncargo__c hoja = new HojaEncargo__c();
        hoja.PDFDatosArriaga__c = 'TEST {!Name}';
        hoja.PDFDesistimiento__c = 'TEST {!Account.Name}';
        hoja.PDFHonorarios__c = 'TEST {!TEST}';
        hoja.ExternalId__c = '0003';
        insert hoja;
        
        //Crear Oportunidad
        Opportunity opp = new Opportunity();
        opp.AccountId = ac.Id;
        opp.StageName = 'Prospecting';      
        opp.Name = 'OppTest';
        Opp.CloseDate = date.valueOf(system.now());
        Opp.HojaEncargo__c = hoja.id;
        insert opp;
        
        //Crear Funcion de contacto
        OpportunityContactRole opprole = new OpportunityContactRole();
        opprole.ContactId = PersonContactId.PersonContactId;
        opprole.Role = 'Titular';
        opprole.OpportunityId = opp.Id;
        insert opprole;
        
        opprole = new OpportunityContactRole();
        opprole.ContactId = tutorCuentaPersonal.PersonContactId;
        opprole.Role = 'Tutor';
        opprole.OpportunityId = opp.Id;
        insert opprole;
               
        //Asignamos a la página el id de la oportunidad como parametro de la URL
        Test.setCurrentPageReference(new PageReference('PDFHojaEncargo'));
        System.currentPageReference().getParameters().put('id', opp.id);
        system.Test.startTest();
        	PDFHojaEncargo pdf = new PDFHojaEncargo();
        	pdf.getWOportunidad();
        	pdf.gethojaEnc();
        system.Test.stopTest();
    }
}