force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/CommunityOpp__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela las oportunidades para Comunidades.</description>
    <label>Contratación Online</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Contratación Online</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrataciones Online</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunityOpp__c/fields/CantidadPagar__c.field-meta.xml
<CustomField>
    <fullName>CantidadPagar__c</fullName>
    <description>Cantidad a pagar. Campo obtenido de la lista de precios.</description>
    <label>Cantidad a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/ContrFinalizado__c.field-meta.xml
<CustomField>
    <fullName>ContrFinalizado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que indica si la contratación ha sido finalizada</description>
    <label>Contratación finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cliente asociado a la contratación online</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IdOportunidad__c.field-meta.xml
<CustomField>
    <fullName>IdOportunidad__c</fullName>
    <description>Campo donde guardamos el Id de la oportunidad para poder recogerla desde la comunidad.</description>
    <label>IdOportunidad</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IDProducto__c.field-meta.xml
<CustomField>
    <fullName>IDProducto__c</fullName>
    <description>Id del producto asignado a la contratación online. Se guarda para poder utilizarlo en comprobaciones dentro de la comunidad</description>
    <label>ID Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup que relaciona los objetos de contratacion online y oportunidad.</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/DatosFlujo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Datos que se utilizan en el flujo de Gastos Hipotecarios</description>
    <label>Datos Flujo</label>
</CustomObject>

force-app/main/default/objects/DatosFlujo__c/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta en la creación</description>
    <label>Estado Cuenta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/EtapaOEtapaOportuniportunidadContrOnline__c.field-meta.xml
<CustomField>
    <fullName>EtapaOEtapaOportuniportunidadContrOnline__c</fullName>
    <description>Etapa de creación de la oportunidad</description>
    <label>EtapaOportunidadContrOnline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdProducto__c.field-meta.xml
<CustomField>
    <fullName>IdProducto__c</fullName>
    <description>Id del producto en el que está  interesado para cuando se introduce un candidato a través de un formulario Web. Se guarda esta información en la oportunidad para en el trigger posteriormente crear el producto de la oportunidad</description>
    <label>Id Producto</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RedsysDatosLlamada__c/RedsysDatosLlamada__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Redsys_DatosLlamada</label>
</CustomObject>

force-app/main/default/classes/TestInotificacionSISRest.cls
/*
@author Leadclic Solutions S.L.
@date 15/07/2019
@description Clase test para el tratamiento de las llamdas a Redsys mediante el merchantURL

<pre>
FECHA               AUTOR   
15/07/2019			LCS - RDM		Creación 
04/09/2019			LCS - RDM		Modificación. Subida de % de cobertura
31/03/2020			LCS - RAL		Modificación. Se añade el teléfono en la creación de cuenta

</pre>
*/
@isTest
public class TestInotificacionSISRest {
    
    @testSetup static void crearCustomSettings() {
        TestAux.crearDatosRedsys();
        TestAux.crearDatosFlujo();
        TestAux.crearProducto();
        TestAux.crearRedsysCodigoRespuesta();
    }
    
    /*******CLASES MOCK*******/
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals('http://example.com/example/test', req.getEndpoint());
            //System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"example":"test"}');
            res.setStatusCode(200);
            return res;
        }
    }    
    
    public class MockHttpResponseGeneratorFirmaok_ko implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals('http://example.com/example/test', req.getEndpoint());
            //System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('slAlBC9h2aL/dJBTunkuzHUWYf1JKzn33Ldd++4u5fM=');
            res.setStatusCode(200);
            return res;
        }
    }    
    
    public class MockHttpResponseGeneratorFirmaok_ok implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Optionally, only send a mock response for a specific endpoint
            // and method.
            //System.assertEquals('http://example.com/example/test', req.getEndpoint());
            //System.assertEquals('GET', req.getMethod());
            
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('V/KqVymKT/xW7tfuhhDz9OYKd2fuXn8+8QwL9jyTKxM=');
            res.setStatusCode(200);
            return res;
        }
    }    
    /*******FIN MOCK*******/
    @isTest static void generarFirma()
    {            
        
        String merchparams = 'eyJEU19NRVJDSEFOVF9PUkRFUiI6IjE4MDczMTEyIiwiRFNfTUVSQ0hBTlRfVEVSTUlOQUwiOiIxIiwiRFNfTUVSQ0hBTlRfVVJMT0siOiJodHRwczovL3VlbGlnaHRuaW5nLS1kZXZlbG9wMS5jczg5Lm15LnNhbGVzZm9yY2UuY29tLzgwMTBFMDAwMDAwWG5wdlFBQy9kZXRhaWw/UmVzcG9uc2U9dHJ1ZSIsIkRTX01FUkNIQU5UX1VSTEtPIjoiaHR0cHM6Ly91ZWxpZ2h0bmluZy0tZGV2ZWxvcDEuY3M4OS5teS5zYWxlc2ZvcmNlLmNvbS84MDEwRTAwMDAwMFhucHZRQUMvZGV0YWlsP1Jlc3BvbnNlPXRydWUiLCJEU19NRVJDSEFOVF9USVRVTEFSIjoiUm9zYSBMQ1MiLCJEU19NRVJDSEFOVF9DVVJSRU5DWSI6Ijk3OCIsIkRTX01FUkNIQU5UX1RSQU5TQUNUSU9OVFlQRSI6IjAiLCJEU19NRVJDSEFOVF9NRVJDSEFOVFVSTCI6Imh0dHBzOi8vdWVsaWdodG5pbmctLWRldmVsb3AxLmNzODkubXkuc2FsZXNmb3JjZS5jb20vODAxMEUwMDAwMDBYbnB2UUFDIiwiRFNfTUVSQ0hBTlRfUFJPRFVDVERFU0NSSVBUSU9OIjoiQXB0byIsIkRTX01FUkNIQU5UX01FUkNIQU5UTkFNRSI6IlVOSVZFUlNJREFEIEVVUk9QRUEgREUgTUFEUklEIFMuTC5VLiIsIkRTX01FUkNIQU5UX0FNT1VOVCI6IjUwMCIsIkRTX01FUkNIQU5UX01FUkNIQU5UREFUQSI6IjAxMjEwMTUzODAwRDcyMDE4IiwiRFNfTUVSQ0hBTlRfTUVSQ0hBTlRDT0RFIjoiMzM0ODQyOTM3In0=';
        String KeyComercio = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7';
        RedsysDatosLlamada__c DatosRedsys = RedsysDatosLlamada__c.getInstance('General');
        
        system.test.startTest();
        
        // Set mock callout class 
    	Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());        
		InotificacionSISRest.generateSignature(merchparams, KeyComercio);
        
        System.test.stopTest();
    }
    
    //*****TEST OK codigo 0000*****/
    @isTest static void okRespuesta()
    {          
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorFirmaok_ok());
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.Phone = '60000000';
        insert ac;   
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        	opp.Amount = pb.UnitPrice;
        insert opp;        
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        
        
        //Añadimos documentos a la oportunidad        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test';      
        cv.PathOnClient ='test';           
        cv.VersionData =blob.valueOf('Test Adjunto');          
        insert cv;         

        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=ContratOnline.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        insert contentlink;
        
        String idOpp = opp.Id;
        String Name = ac.Name;
        
        Blob Decodificando = EncodingUtil.base64Decode('eyJEc19EYXRlIjoiMDYlMkYwOSUyRjIwMTgiLCJEc19Ib3VyIjoiMDglM0EyMSIsIkRzX1NlY3VyZVBheW1lbnQiOiIwIiwiRHNfQW1vdW50IjoiMTAwIiwiRHNfQ3VycmVuY3kiOiI5NzgiLCJEc19PcmRlciI6Ijg4OTAwMDAwMDE2OCIsIkRzX01lcmNoYW50Q29kZSI6IjMzNDg0MjkzNyIsIkRzX1Rlcm1pbmFsIjoiMDAxIiwiRHNfUmVzcG9uc2UiOiIwMDAwIiwiRHNfVHJhbnNhY3Rpb25UeXBlIjoiMCIsIkRzX01lcmNoYW50RGF0YSI6IjAxMjEwMTUzODAwRDcyMDE4IiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIzMjY4MjQiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjcyNCIsIkRzX0NhcmRfQnJhbmQiOiIxIn0=');
        String Parametros = Decodificando.toString();
        Parametros = Parametros.substring(1, Parametros.length()-1);
        
                
        String[] keyValuePairs = Parametros.split(',');
        string pa = '';
        
        Opportunity o = [SELECT NumeroExpediente__c FROM Opportunity WHERE Id =:opp.Id];
        
        for(String pair : keyValuePairs)                        
        {
            pair = pair.replace('"','');
            String[] entry = pair.split(':');
            
            if(entry[0].trim() == 'Ds_Order') entry[1] = '0000'+o.NumeroExpediente__c;
            
            if(pa == '')pa = '{"'+entry[0].trim()+'":"'+ entry[1].trim();
            else pa += ','+entry[0].trim()+'":"'+ entry[1].trim();
        }
        pa+='"}"';
        
         Blob Codificando = Blob.valueOf(pa);		
        String ParametersCodec = EncodingUtil.base64Encode(Codificando);
        
        system.test.startTest();

           RestRequest req = new RestRequest(); 
           RestResponse res = new RestResponse();
        
            req.requestURI = URL.getSalesforceBaseUrl() + '/services/apexrest/InotificacionSIS';  //Request URL
        
            req.addParameter('Ds_MerchantParameters', ParametersCodec);
            req.addParameter('Ds_Signature','V_KqVymKT_xW7tfuhhDz9OYKd2fuXn8-8QwL9jyTKxM=');
            req.addParameter('Ds_SignatureVersion', 'HMAC_SHA256_V1');

        	req.httpMethod = 'POST';//HTTP Request Type
            RestContext.request = req;
            RestContext.response= res;
            InotificacionSISRest.notificar();
        System.Test.stopTest();
        
    }
    
    //*****TEST KO codigo 0180*****/
    @isTest static void koRespuesta()
    {        
        
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorFirmaok_ko()); 
         
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorFirmaok_ok());
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.Phone = '60000000';
        insert ac;   
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        	opp.Amount = pb.UnitPrice;
        insert opp;  
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        
        String idOpp = opp.Id;
        String Name = ac.Name;
        
        Blob Decodificando = EncodingUtil.base64Decode('eyJEc19EYXRlIjoiMDUlMkYwOSUyRjIwMTgiLCJEc19Ib3VyIjoiMTMlM0EyNSIsIkRzX1NlY3VyZVBheW1lbnQiOiIwIiwiRHNfQW1vdW50IjoiMTAwIiwiRHNfQ3VycmVuY3kiOiI5NzgiLCJEc19PcmRlciI6Ijg2OTAwMDAwMDE2NiIsIkRzX01lcmNoYW50Q29kZSI6IjMzNDg0MjkzNyIsIkRzX1Rlcm1pbmFsIjoiMDAxIiwiRHNfUmVzcG9uc2UiOiIwMTgwIiwiRHNfVHJhbnNhY3Rpb25UeXBlIjoiMCIsIkRzX01lcmNoYW50RGF0YSI6IjAxMjEwMTUzODAwRDcyMDE4IiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIrKysrKysiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjAifQ==');
        String Parametros = Decodificando.toString();
        Parametros = Parametros.substring(1, Parametros.length()-1);
        
        Opportunity o = [SELECT NumeroExpediente__c FROM Opportunity WHERE Id =:opp.Id];
                
        String[] keyValuePairs = Parametros.split(',');
        string pa = '';
        Map<String,String> mapaParametros = new Map<String,String>();
        for(String pair : keyValuePairs)                        
        {
            pair = pair.replace('"','');            
            String[] entry = pair.split(':');  
            
            if(entry[0].trim() == 'Ds_Order') entry[1] = '0000'+o.NumeroExpediente__c;
            
            if(pa == '')pa = '{"'+entry[0].trim()+'":"'+ entry[1].trim();
            else pa += ','+entry[0].trim()+'":"'+ entry[1].trim();
        }
        pa+='"}"';
        
         Blob Codificando = Blob.valueOf(pa);		
        String ParametersCodec = EncodingUtil.base64Encode(Codificando);
        
        system.test.startTest();

           RestRequest req = new RestRequest(); 
           RestResponse res = new RestResponse();
        
            req.requestURI = URL.getSalesforceBaseUrl() + '/services/apexrest/InotificacionSIS';  //Request URL
        
            req.addParameter('Ds_MerchantParameters', ParametersCodec);
            req.addParameter('Ds_Signature','slAlBC9h2aL/dJBTunkuzHUWYf1JKzn33Ldd++4u5fM=');
            req.addParameter('Ds_SignatureVersion', 'HMAC_SHA256_V1');

        	req.httpMethod = 'POST';//HTTP Request Type
            RestContext.request = req;
            RestContext.response= res;
            InotificacionSISRest.notificar();
        System.Test.stopTest();
    } 
    
    //*****TEST KO codigo 9000*****/
    @isTest static void koNoMessageRespuesta()
    {          
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorFirmaok_ko()); 
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.Phone = '60000000';
        insert ac;   
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        	opp.Amount = pb.UnitPrice;
        insert opp;        
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        
        String idOpp = opp.Id;
        String Name = ac.Name;
        
        Blob Decodificando = EncodingUtil.base64Decode('eyJEc19EYXRlIjoiMDYlMkYwOSUyRjIwMTgiLCJEc19Ib3VyIjoiMDglM0EyMSIsIkRzX1NlY3VyZVBheW1lbnQiOiIwIiwiRHNfQW1vdW50IjoiMTAwIiwiRHNfQ3VycmVuY3kiOiI5NzgiLCJEc19PcmRlciI6Ijg4OTAwMDAwMDE2OCIsIkRzX01lcmNoYW50Q29kZSI6IjMzNDg0MjkzNyIsIkRzX1Rlcm1pbmFsIjoiMDAxIiwiRHNfUmVzcG9uc2UiOiIwMDAwIiwiRHNfVHJhbnNhY3Rpb25UeXBlIjoiMCIsIkRzX01lcmNoYW50RGF0YSI6IjAxMjEwMTUzODAwRDcyMDE4IiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIzMjY4MjQiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjcyNCIsIkRzX0NhcmRfQnJhbmQiOiIxIn0=');
        String Parametros = Decodificando.toString();
        Parametros = Parametros.substring(1, Parametros.length()-1);
        
                
        String[] keyValuePairs = Parametros.split(',');
        string pa = '';
        
        Opportunity o = [SELECT NumeroExpediente__c FROM Opportunity WHERE Id =:opp.Id];
        
        for(String pair : keyValuePairs)                        
        {
            pair = pair.replace('"','');
            String[] entry = pair.split(':');
            
            if(entry[0].trim() == 'Ds_Order') entry[1] = '0000'+o.NumeroExpediente__c;
            
            if(pa == '')pa = '{"'+entry[0].trim()+'":"'+ entry[1].trim();
            else pa += ','+entry[0].trim()+'":"'+ entry[1].trim();
        }
        pa+='"}"';
        
         Blob Codificando = Blob.valueOf(pa);		
        String ParametersCodec = EncodingUtil.base64Encode(Codificando);
        
        system.test.startTest();

           RestRequest req = new RestRequest(); 
           RestResponse res = new RestResponse();
        
            req.requestURI = URL.getSalesforceBaseUrl() + '/services/apexrest/InotificacionSIS';  //Request URL
        
            req.addParameter('Ds_MerchantParameters', ParametersCodec);
            req.addParameter('Ds_Signature','V_KqVymKT_xW7tfuhhDz9OYKd2fuXn8-8QwL9jyTKxM=');
            req.addParameter('Ds_SignatureVersion', 'HMAC_SHA256_V1');

        	req.httpMethod = 'POST';//HTTP Request Type
            RestContext.request = req;
            RestContext.response= res;
            InotificacionSISRest.notificar();
        System.Test.stopTest();
        
    }
    //*****TEST ERROR FIRMA*****/
    @isTest static void koRespuestaFirma()
    {  
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator()); 
        DatosFlujo__c configDatosflujo = DatosFlujo__c.getOrgDefaults();
        
        Account ac = new Account();
        	ac.FirstName = 'Test';
        	ac.LastName = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Cuenta personal').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.Phone = '60000000';
        insert ac;   
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;
            opp.StageName = configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c;      
            opp.Name = 'Test';
            opp.Pricebook2Id = standardPricebook.id;
            Opp.CloseDate = date.valueOf(system.now());
        	opp.Amount = pb.UnitPrice;
        insert opp;        
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        
        String idOpp = opp.Id;
        String Name = ac.Name;
        
        Blob Decodificando = EncodingUtil.base64Decode('eyJEc19EYXRlIjoiMDYlMkYwOSUyRjIwMTgiLCJEc19Ib3VyIjoiMDglM0EyMSIsIkRzX1NlY3VyZVBheW1lbnQiOiIwIiwiRHNfQW1vdW50IjoiMTAwIiwiRHNfQ3VycmVuY3kiOiI5NzgiLCJEc19PcmRlciI6Ijg4OTAwMDAwMDE2OCIsIkRzX01lcmNoYW50Q29kZSI6IjMzNDg0MjkzNyIsIkRzX1Rlcm1pbmFsIjoiMDAxIiwiRHNfUmVzcG9uc2UiOiIwMDAwIiwiRHNfVHJhbnNhY3Rpb25UeXBlIjoiMCIsIkRzX01lcmNoYW50RGF0YSI6IjAxMjEwMTUzODAwRDcyMDE4IiwiRHNfQXV0aG9yaXNhdGlvbkNvZGUiOiIzMjY4MjQiLCJEc19Db25zdW1lckxhbmd1YWdlIjoiMSIsIkRzX0NhcmRfQ291bnRyeSI6IjcyNCIsIkRzX0NhcmRfQnJhbmQiOiIxIn0=');
        String Parametros = Decodificando.toString();
        Parametros = Parametros.substring(1, Parametros.length()-1);
        
                
        String[] keyValuePairs = Parametros.split(',');
        string pa = '';
        
        Opportunity o = [SELECT NumeroExpediente__c FROM Opportunity WHERE Id =:opp.Id];
        
        for(String pair : keyValuePairs)                        
        {
            pair = pair.replace('"','');
            String[] entry = pair.split(':');
            
            if(entry[0].trim() == 'Ds_Order') entry[1] = '0000'+o.NumeroExpediente__c;
            
            if(pa == '')pa = '{"'+entry[0].trim()+'":"'+ entry[1].trim();
            else pa += ','+entry[0].trim()+'":"'+ entry[1].trim();
        }
        pa+='"}"';
        
         Blob Codificando = Blob.valueOf(pa);		
        String ParametersCodec = EncodingUtil.base64Encode(Codificando);
        
        system.test.startTest();

           RestRequest req = new RestRequest(); 
           RestResponse res = new RestResponse();
        
            req.requestURI = URL.getSalesforceBaseUrl() + '/services/apexrest/InotificacionSIS';  //Request URL
        
            req.addParameter('Ds_MerchantParameters', ParametersCodec);
            req.addParameter('Ds_Signature','V_KqVymKT_xW7tfuhhDz9OYKd2fuXn8-8QwL9jyTKxM=');
            req.addParameter('Ds_SignatureVersion', 'HMAC_SHA256_V1');

        	req.httpMethod = 'POST';//HTTP Request Type
            RestContext.request = req;
            RestContext.response= res;
            InotificacionSISRest.notificar();
        System.Test.stopTest();
    }
}