force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Oficina.recordType-meta.xml
<RecordType>
    <fullName>Oficina</fullName>
    <active>true</active>
    <label>Oficina</label>
</RecordType>

force-app/main/default/objects/Activo__c/Activo__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela los bienes asociados a un Expediente</description>
    <label>Activo</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Número de Activo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ArrMinervDatosWS__c/ArrMinervDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Minerva de Arriaga</description>
    <label>ArriagaMinerva_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrMinervDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check de control que indica si la configuración puede o no usarse</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/ArrProdDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Producción de Arriaga</description>
    <label>ArriagaProduccion_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrProdDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que marca si el entorno esta activo para realizar peticiones</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtContc__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtContc__c</fullName>
    <label>EndpointCrear</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtExp__c</fullName>
    <description>Endpoint del entorno de producción para crear expedientes</description>
    <label>EndpointCrearExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointUpdtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointUpdtExp__c</fullName>
    <description>Endpoint del entorno de producción para actualizar un expediente</description>
    <label>EndpointActulizarExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>PrivateKey__c</fullName>
    <description>Clave privada generada por Producción de Arriaga</description>
    <label>PrivateKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PublicKey__c.field-meta.xml
<CustomField>
    <fullName>PublicKey__c</fullName>
    <description>Clave publica utilizada para llegar al WS</description>
    <label>PublicKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en el expediente el id del cliente para enviárselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdExpediente__c.field-meta.xml
<CustomField>
    <fullName>IdExpediente__c</fullName>
    <description>Número autogenerado en la oportunidad que se utiliza para realizar pagos y identificar el Expediente</description>
    <externalId>true</externalId>
    <label>IdExpediente</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Oportunidad asociada al expediente</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Expedientes</relationshipLabel>
    <relationshipName>Expedientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <description>Tipo de expediente común</description>
    <label>General</label>
</RecordType>

force-app/main/default/objects/EstadosComunidad__c/EstadosComunidad__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Estados que se mostrarán en la comunidad y su prefijo</description>
    <label>Estados Comunidad</label>
</CustomObject>

force-app/main/default/objects/EstadosComunidad__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <description>Valor del estado que se mostrará en la comunidad</description>
    <label>Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

force-app/main/default/objects/IntegracionSF__c/IntegracionSF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración encargada de guardar los datos necesarios para poder obtener el token de la instacia de SF y de esta manera poder conectarnos con la misma instancia</description>
    <label>IntegracionSF</label>
</CustomObject>

force-app/main/default/objects/IntegracionSF__c/fields/UsuarioIntegracionId__c.field-meta.xml
<CustomField>
    <fullName>UsuarioIntegracionId__c</fullName>
    <description>Identificador del usuario de integración de arriaga para controlar cambios que haga</description>
    <label>Usuario Integración Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/NotificationBellLayoutControllerTest.cls
@isTest
public class NotificationBellLayoutControllerTest {
    public static String account;
    @testSetup static void crearCustomSettings() {
        TestAux.crearIntegracionGD();
        ArrMinervDatosWS__c confPer = new ArrMinervDatosWS__c();
        confPer.name = 'General';
        confPer.Activo__c = true;
        
        
        ArrProdDatosWS__c cs = new ArrProdDatosWS__c();
        cs.name = 'General';
        cs.Activo__c = true;
        cs.PrivateKey__c = 'XXXX';
        cs.PublicKey__c = 'XXXX';
        cs.EndpointInsrtContc__c = 'test';
        cs.EndpointInsrtExp__c = 'sad';
        cs.EndpointUpdtExp__c = 'ass';
        
        insert cs;
       	insert confPer;

        IntegracionSF__c confIntegracionSF = new IntegracionSF__c();
        confIntegracionSF.Name = 'General';
        confIntegracionSF.UsuarioIntegracionId__c = '0051t000003IpmE';
        insert confIntegracionSF;


        EstadosComunidad__c confEstadosComunidad = new EstadosComunidad__c();
        confEstadosComunidad.Name = '00';
        confEstadosComunidad.Estado__c = 'ESTADO NO DEFINIDO';
        insert confEstadosComunidad;
        EstadosComunidad__c confEstadosComunidad2 = new EstadosComunidad__c();
        confEstadosComunidad2.Name = '01';
        confEstadosComunidad2.Estado__c = 'ESTADO NO DEFINIDO2';
        insert confEstadosComunidad2;
        EstadosComunidad__c confEstadosComunidad3 = new EstadosComunidad__c();
        confEstadosComunidad3.Name = '08';
        confEstadosComunidad3.Estado__c = 'ESTADO NO DEFINIDO3';
        insert confEstadosComunidad3;
    }
    
    
    @isTest public static void testGetNotifications(){
        Account ac = new Account();
        	ac.name = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        	ac.EstadoCuenta__c='Cliente';
        	ac.Phone = '600000000';
        insert ac;
        Contact cont = new Contact();
            cont.accountId = ac.Id;
            cont.FirstName = 'NombreT';
            cont.lastName = 'Test';
            cont.MailingCountry = 'ESPAÑA';
            cont.MobilePhone =  '0034123456789';
            cont.Phone = '0034123456789';
            cont.Email = 'test.sz@example.com';
        insert cont;
        account=ac.Id;
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
      
        Opportunity opp = new Opportunity();
        opp.AccountId = ac.id;
        opp.StageName = 'Prospecting';   
        opp.Pricebook2Id = standardPricebook.id;   
        opp.Name = 'Test';
        Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        
        Contract Expediente = new Contract();
            Expediente.AccountId = ac.Id;
            Expediente.Pricebook2Id = standardPricebook.id;
            Expediente.IdExpediente__c = opp.NumeroExpediente__c;
            Expediente.Oportunidad__c = opp.id;
            Expediente.Status='Contratado';
        insert Expediente;

        Task tareaNueva = new Task();
        tareaNueva.Description = 'Pruebas';
        tareaNueva.Subject = 'Pruebas';
        tareaNueva.Status =  'Pruebas';
        tareaNueva.ActivityDate = system.today();
        tareaNueva.IsVisibleInSelfService=true;
        tareaNueva.WhatId = Expediente.Id;
        insert tareaNueva;
        
        Account oficina = new Account(Name = 'Test Oficina Notificacion', 
        ShippingState = 'Madrid',
        IdClienteMinerva__c='111',
        RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Oficina').getRecordTypeId(),
         Phone = '6000000000');
        insert oficina;

        Event evt = new Event();
        evt.WhatId =  ac.Id;
        evt.Subject = 'Cita';
        evt.Oficina__c=oficina.Id;
        evt.StartDateTime = DateTime.now();
        evt.EndDateTime =  DateTime.now();
        insert evt;

        FeedItem tpost= new FeedItem();
        tpost.ParentId=Expediente.Id;
        tpost.Body = 'Enter post text here';
        insert tpost;
        
    	Profile p = [select id From Profile where Name ='Comunidad Arriaga'];
        User u = new User(
	     		ContactId = cont.Id,
				FirstName = cont.FirstName,
				LastName = cont.LastName,
				IsActive = true,
				EmailEncodingKey = 'ISO-8859-1',
				Email = cont.Email,
				Username = cont.Email,
				CommunityNickname = cont.Email,
				Phone = cont.Phone,
				Alias = cont.FirstName,
				ProfileId = p.id,
				TimeZoneSidKey = 'Europe/Paris',
				LanguageLocaleKey = 'es',
				LocaleSidKey = 'es_ES'
	     	);
	     	insert u; 
        System.Test.startTest();        
                NotificationBellLayoutController.getNotifications(false,'');
                NotificationBellLayoutController.getNotifications(true,'');
            
        System.Test.stopTest();
    }
}