force-app/main/default/objects/Account/fields/EstadoCuenta__c.field-meta.xml
<CustomField>
    <fullName>EstadoCuenta__c</fullName>
    <description>Estado de la cuenta. Sera cliente potencial cuando aun no tenga ningún expediente creado.</description>
    <label>Estado de la Cuenta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente potencial</fullName>
                <default>true</default>
                <label>Cliente potencial</label>
            </value>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Inactivo</fullName>
            </value>
            <value>
                <fullName>Fallecido</fullName>
            </value>
            <value>
                <fullName>Recaptura</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activo__c/Activo__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela los bienes asociados a un Expediente</description>
    <label>Activo</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Número de Activo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunityOpp__c/CommunityOpp__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela las oportunidades para Comunidades.</description>
    <label>Contratación Online</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>Nombre de Contratación Online</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contrataciones Online</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommunityOpp__c/fields/CantidadPagar__c.field-meta.xml
<CustomField>
    <fullName>CantidadPagar__c</fullName>
    <description>Cantidad a pagar. Campo obtenido de la lista de precios.</description>
    <label>Cantidad a Pagar</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/ContrFinalizado__c.field-meta.xml
<CustomField>
    <fullName>ContrFinalizado__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check que indica si la contratación ha sido finalizada</description>
    <label>Contratación finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Cliente asociado a la contratación online</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Gratis__c.field-meta.xml
<CustomField>
    <fullName>Gratis__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que indica si el producto ha sido contratado gratis</description>
    <label>Producto Gratis</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IdOportunidad__c.field-meta.xml
<CustomField>
    <fullName>IdOportunidad__c</fullName>
    <description>Campo donde guardamos el Id de la oportunidad para poder recogerla desde la comunidad.</description>
    <label>IdOportunidad</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/IDProducto__c.field-meta.xml
<CustomField>
    <fullName>IDProducto__c</fullName>
    <description>Id del producto asignado a la contratación online. Se guarda para poder utilizarlo en comprobaciones dentro de la comunidad</description>
    <label>ID Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommunityOpp__c/fields/Oportunidad__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup que relaciona los objetos de contratacion online y oportunidad.</description>
    <label>Oportunidad</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contrataciones Online</relationshipLabel>
    <relationshipName>Contrataciones_Online</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdProducto__c.field-meta.xml
<CustomField>
    <fullName>IdProducto__c</fullName>
    <description>Id del producto en el que está  interesado para cuando se introduce un candidato a través de un formulario Web. Se guarda esta información en la oportunidad para en el trigger posteriormente crear el producto de la oportunidad</description>
    <label>Id Producto</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/ProductosContrt__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración donde se indicarán los productos que están activos para realizar la contratación. En esta configuración se añadirán aquellos productos que siguen el patrón de gratuitos</description>
    <label>Productos a contratar</label>
</CustomObject>

force-app/main/default/objects/ProductosContrt__c/fields/IdProduct__c.field-meta.xml
<CustomField>
    <fullName>IdProduct__c</fullName>
    <label>Id Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/NameProduct__c.field-meta.xml
<CustomField>
    <fullName>NameProduct__c</fullName>
    <label>Nombre Producto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/URLArriaga__c.field-meta.xml
<CustomField>
    <fullName>URLArriaga__c</fullName>
    <description>Url donde se encuentra la información del producto que se quiere contratar dentro de la web de Arriaga</description>
    <label>URLArriaga</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/URLContratacion__c.field-meta.xml
<CustomField>
    <fullName>URLContratacion__c</fullName>
    <label>URL Pagina contratacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFlow_ComprobacionPagos.cls
/*
@author LeadClic Solutions S.L.
@date 14/03/2019
@description Clase Test para la clase Aque comprueba si se debe realizar un pago

<pre>
FECHA                 AUTOR           ACCION
15/03/2019			LCS - RDM		 Creación.
31/03/2020			LCS - RAL		 Modificación. Se añade el teléfono en la creación de cuenta

*/
@isTest
public class TestFlow_ComprobacionPagos {
    
    @testSetup static void crearCustomSettings(){
        
    }

    @isTest static void TestContratacionOnline(){ 
        
        Account ac = new Account();
        	ac.name = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        	ac.EstadoCuenta__c = 'Cliente';
        	ac.Phone = '60000000';
        insert ac;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pb = [SELECT Id FROM PriceBookEntry WHERE Product2Id =: prod.id];      
        
        
        ProductosContrt__c lConfigProd = new ProductosContrt__c();
            lConfigProd.Name = prod.Name;
            lConfigProd.Activo__c = true;
            lConfigProd.IdProduct__c = prod.id;
            lConfigProd.NameProduct__c = prod.Name;
            lConfigProd.URLArriaga__c = 'www.test.com';
            lConfigProd.URLContratacion__c = '';
        insert lConfigProd;

        Flow_ComprobacionPagos.GetParameters request = new Flow_ComprobacionPagos.GetParameters();
        List<Flow_ComprobacionPagos.GetParameters> listRequest = new List<Flow_ComprobacionPagos.GetParameters>();
                                
        request.productoGratis = true;
        request.IdCuenta = ac.id;
        request.IdProducto = prod.id;
        listRequest.add(request);
        
        system.Test.startTest();
        	Flow_ComprobacionPagos.MetodoInvocable(listRequest);
        system.Test.stopTest();
    }
    
    @isTest static void TestContratacionOnlineExistente(){        
        
        Account ac = new Account();
        	ac.name = 'Test';
        	ac.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        	ac.EstadoCuenta__c = 'Cliente';
        	ac.Phone = '60000000';
        insert ac;
        
        // Se crea Pricebook2, cogiendo el Id de la lista standard
        Pricebook2 standardPricebook = new Pricebook2(
            Id = Test.getStandardPricebookId(),
            IsActive = true
        );
        //Como workarround para crear la lista de precios standard, se ejecuta un update sobre el registro de Pricebook2, para que se active a true IsStandard
        update standardPricebook;
        
        Product2 prod = new Product2();
            prod.Name = 'test Prod'; 
            prod.IsActive = true;
        insert prod;
        
        Product2 prod2 = new Product2();
            prod2.Name = 'test Prod2'; 
            prod2.IsActive = true;
        insert prod2;
        
        PriceBookEntry pb = [SELECT Id, UnitPrice FROM PriceBookEntry WHERE Product2Id =: prod.id];
        
        Opportunity opp = new Opportunity();
            opp.AccountId = ac.id;    
            opp.Name = 'Test';
            opp.StageName = 'Prospecting';
            Opp.CloseDate = date.valueOf(system.now());
        insert opp;
        
        CommunityOpp__c ContratOnline = new CommunityOpp__c();
            ContratOnline.Cuenta__c = ac.id;
            ContratOnline.Oportunidad__c = opp.Id;  
            ContratOnline.IdOportunidad__c = opp.Id; 
        	ContratOnline.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline.IDProducto__c = prod.id;
        	ContratOnline.ContrFinalizado__c = true;
        insert ContratOnline;
        
        CommunityOpp__c ContratOnline2 = new CommunityOpp__c();
            ContratOnline2.Cuenta__c = ac.id;
            ContratOnline2.Oportunidad__c = opp.Id;  
            ContratOnline2.IdOportunidad__c = opp.Id; 
        	ContratOnline2.CantidadPagar__C = pb.UnitPrice;
        	ContratOnline2.IDProducto__c = prod2.id;
        	ContratOnline2.ContrFinalizado__c = true;
        	ContratOnline2.Gratis__c = true;
        insert ContratOnline2;
        
        list<ProductosContrt__c> lConfigProd = new list<ProductosContrt__c>();
            ProductosContrt__c ConfigProd = new ProductosContrt__c();
                ConfigProd.Name = prod.Name;
                ConfigProd.Activo__c = true;
                ConfigProd.IdProduct__c = prod.id;
                ConfigProd.NameProduct__c = prod.Name;
                ConfigProd.URLArriaga__c = 'www.test.com';
                ConfigProd.URLContratacion__c = '';
            lConfigProd.add(ConfigProd);
            ProductosContrt__c ConfigProd2 = new ProductosContrt__c();
                ConfigProd2.Name = prod2.Name;
                ConfigProd2.Activo__c = true;
                ConfigProd2.IdProduct__c = prod2.id;
                ConfigProd2.NameProduct__c = prod2.Name;
                ConfigProd2.URLArriaga__c = 'www.test.com';
                ConfigProd2.URLContratacion__c = '';
            lConfigProd.add(ConfigProd2);
        insert lConfigProd;

        Flow_ComprobacionPagos.GetParameters request = new Flow_ComprobacionPagos.GetParameters();
        List<Flow_ComprobacionPagos.GetParameters> listRequest = new List<Flow_ComprobacionPagos.GetParameters>();
               
        request.productoGratis = true; 
        request.IdCuenta = ac.id;
        request.IdProducto = prod.id;
        listRequest.add(request);
        
        system.Test.startTest();
        	Flow_ComprobacionPagos.MetodoInvocable(listRequest);
        system.Test.stopTest();
    }

}