force-app/main/default/objects/Account/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Id que pasaremos a la hora de crear el cliente.</description>
    <externalId>true</externalId>
    <label>Id Cliente Minerva</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdOrigen__c.field-meta.xml
<CustomField>
    <fullName>IdOrigen__c</fullName>
    <description>Contiene el identificador del sistema de origen de Arriaga Asociados, utilizado para las cargas iniciales</description>
    <externalId>true</externalId>
    <label>Id Cliente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación, implementa una lista de valores globales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoDocumento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampoDocumento__c/CampoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado relacionado con el objeto  tipo documento donde indicaremos los campos que tienen un tipo de documento concreto</description>
    <label>Campo del documento</label>
    <nameField>
        <label>Nombre del campo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campos del documento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampoDocumento__c/fields/NombreAPI__c.field-meta.xml
<CustomField>
    <fullName>NombreAPI__c</fullName>
    <description>Etiqueta de cómo será enviado el campo al gestor documental</description>
    <label>Nombre API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampoDocumento__c/fields/TipoCampo__c.field-meta.xml
<CustomField>
    <fullName>TipoCampo__c</fullName>
    <description>Tipo del dato que se introducirá en el campo</description>
    <label>Tipo del campo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
                <label>Fecha</label>
            </value>
            <value>
                <fullName>number</fullName>
                <label>Numérico</label>
            </value>
            <value>
                <fullName>text</fullName>
                <label>Texto</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que pertenece el campo</description>
    <label>Tipo de Documento</label>
    <referenceTo>TipoDocumento__c</referenceTo>
    <relationshipLabel>Campos del documento</relationshipLabel>
    <relationshipName>Campos_del_documento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en el expediente el id del cliente para enviárselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/IdOrigenMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdOrigenMinerva__c</fullName>
    <label>IdOrigenMinerva</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdClienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>IdClienteMinerva__c</fullName>
    <description>Se informa en la oportunidad el id del cliente para enviarselo a minerva al cargar documentos</description>
    <formula>Account.IdClienteMinerva__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Id Cliente Minerva</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpediente__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpediente__c</fullName>
    <description>Número de expediente único que se usa para enviar a Redsys como identificador del pago que se va a realizar</description>
    <externalId>true</externalId>
    <label>Número Expediente</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumeroExpedienteMinerva__c.field-meta.xml
<CustomField>
    <fullName>NumeroExpedienteMinerva__c</fullName>
    <label>NumeroExpedienteMinerva</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <description>Objeto personalizado donde indicaremos los tipos de documentos que tendrán campos extra para el metadato.</description>
    <label>Tipo de Documento</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Tipo de Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tipos de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/ExternalID__c.field-meta.xml
<CustomField>
    <fullName>ExternalID__c</fullName>
    <description>ID externo para la carga de campos de documentos</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/SubidaComunidad__c.field-meta.xml
<CustomField>
    <fullName>SubidaComunidad__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicará que el tipo de documento puede ser subido desde la comunidad por los usuarios al gestor documental.</description>
    <label>Subida a través de comunidad</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento al que se le añaden campos adicionales</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/fields/ValorEtiqueta__c.field-meta.xml
<CustomField>
    <fullName>ValorEtiqueta__c</fullName>
    <description>Almacenará el valor de la etiqueta que se mostrará en la comunidad del tipo de documento.</description>
    <label>Valor etiqueta</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/TipoDocumento.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NIF</fullName>
    </customValue>
    <customValue>
        <fullName>CIF</fullName>
    </customValue>
    <customValue>
        <fullName>NIE</fullName>
    </customValue>
    <customValue>
        <fullName>Pasaporte</fullName>
    </customValue>
    <masterLabel>TipoDocumento</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GDDocumentListController.cls
/*
@author LeadClic Solutions S.L.
@date 
@description Clase que contiene el código controlador del LWC gdDocumentitems
<pre>
FECHA             AUTOR           ACCION
29/05/2019      LCS - RDM         Modificación. 
01/07/2019      LCS - RMG         Modificación. Se cambia para que al buscar los tipos de documentos se busque por el tipo de documento y no por el nombre
 
*/
public without sharing class GDDocumentListController {

    @AuraEnabled
    public static getFieldListResponse getFieldDoc(String nameDocType){
        getFieldListResponse response = new getFieldListResponse();

        try{
            // Obtenemos el id y nombre del tipo de documento correspondiente al nombre del documento enviado desde el componente
            //list<TipoDocumento__c> lTipoDoc = [SELECT Id, Name FROM TipoDocumento__c WHERE Name =:nameDocType];
            list<TipoDocumento__c> lTipoDoc = [SELECT Id, Name FROM TipoDocumento__c WHERE TipoDocumento__c =:nameDocType];

            //Si en la lista existe el valor, es decir, el tamaño de la lista es mayor a 0, realizamos la query para obtener todos los campos y tipos de la misma.
            if(lTipoDoc.size() > 0){
                list<CampoDocumento__c> lCamposDoc = [SELECT Id, Name, NombreAPI__c, TipoCampo__c FROM CampoDocumento__c WHERE TipoDocumento__c =:lTipoDoc[0].Id];
                list<FieldItem> lItems = new list<FieldItem>(); 
                for(CampoDocumento__c campos : lCamposDoc){
                    FieldItem fieldsResp = new FieldItem();   
                        fieldsResp.id = campos.Id;
                        fieldsResp.nameField = campos.Name;
                        fieldsResp.nameAPIField = campos.NombreAPI__c;
                        fieldsResp.typeField = campos.TipoCampo__c;
                    lItems.add(fieldsResp);
                }

                if(!lItems.isEmpty()) response.lFieldsItem = lItems;
                else  response.errorMsg = 'No existen campos para ese producto.';
            }
            else{
                response.errorMsg = 'No existen campos para ese producto.';
            }
        }catch(Exception e){
            response.status = false;
            response.errorMsg = 'Error : ' + e.getMessage();
        }
        return response;
    }

    @AuraEnabled(cacheable=true)
    public static List<TipoDocumento__c> getDocTypes(){
        List<TipoDocumento__c> tipoDocumento = new List<TipoDocumento__c>();
        try {
            tipoDocumento= [SELECT ValorEtiqueta__c, ExternalID__c FROM TipoDocumento__c WHERE SubidaComunidad__c= true];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return tipoDocumento;
    }

    public class getFieldListResponse {

        @AuraEnabled public Boolean status = true;
        @AuraEnabled public String errorMsg = '';
        @AuraEnabled public List<FieldItem> lFieldsItem;

    }
   
    @AuraEnabled
    public static void getIdOrigenMin(String thisidCliente, String thisidExpediente){ 
		List<Account> laccToUp = new List<Account>();
        List<Contract> lexpToUp = new List<Contract>();
        List<Opportunity> lOppToUp = new List<Opportunity>();
        system.debug('thisidExpediente '+thisidExpediente);
        List<Contract> lExp = [SELECT id, IdOrigenMinerva__c, AccountId, IdClienteMinerva__c FROM Contract WHERE IdClienteMinerva__c =: thisidCliente LIMIT 1];
        List<Opportunity> lOpp = [SELECT id, NumeroExpediente__c,NumeroExpedienteMinerva__c  FROM Opportunity WHERE NumeroExpediente__c =: thisidExpediente LIMIT 1];
        system.debug('lExp.size() '+lOpp.size());
        if(lExp.size()!=0){
            for(Contract exp :lExp){
               exp.IdOrigenMinerva__c= exp.IdClienteMinerva__c;
               lexpToUp.add(exp);
               system.debug('exp.IdOrigenMinerva__c '+exp.IdOrigenMinerva__c);
              

            }
           
            update lexpToUp;  
        }
         if(lOpp.size()!=null){
            for(Opportunity opp :lOpp){
                opp.NumeroExpedienteMinerva__c = opp.NumeroExpediente__c;
                lOppToUp.add(opp);
            }
             List<Account> lacc = [SELECT id,IdClienteMinerva__c,IdOrigen__c FROM Account WHERE IdClienteMinerva__c =: thisidCliente LIMIT 1]; 
             for(Account acc :lacc){
                 acc.IdOrigen__c=acc.IdClienteMinerva__c;
                 system.debug('acc.IdOrigen__c '+acc.IdOrigen__c);
                 laccToUp.add(acc);
             }
             system.debug('lOpp.size()' +lOpp.size());
             update laccToUp;
             update lOppToUp; 
            
        }
    }
    public class FieldItem{
         @AuraEnabled public String id;
         @AuraEnabled public String nameField;
         @AuraEnabled public String nameAPIField;
         @AuraEnabled public String typeField;
    }
}