force-app/main/default/objects/Account/fields/IdExternoOficina__c.field-meta.xml
<CustomField>
    <fullName>IdExternoOficina__c</fullName>
    <description>Id externo utilizado para las cargas de oficinas</description>
    <externalId>true</externalId>
    <label>Id Externo Oficina</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Oficina.recordType-meta.xml
<RecordType>
    <fullName>Oficina</fullName>
    <active>true</active>
    <label>Oficina</label>
</RecordType>

force-app/main/default/objects/CustomerReview__c/CustomerReview__c.object-meta.xml
<CustomObject>
    <label>Reseña RRSS</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Código Reseña</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reseñas RRSS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationGoogle_Test.cls
@isTest
public with sharing class IntegrationGoogle_Test {
    // @TestSetup
    // static void makeData(){
    //     insert new Account(
    //         Name = 'Oficina',
    //         Phone = '1231231231',
    //         IdExternoOficina__c = 'id_externo'
    //     );
    // }

    @isTest
    public static void eventListener_test() {
        RestRequest request = new RestRequest();
        request.httpMethod = 'GET';
        request.requestBody = Blob.valueOf(JSON.serialize(new Map<String,Object>{
            'message' => new Map<String,String>{
                'data' => EncodingUtil.base64Encode(Blob.valueOf(JSON.serialize(new Map<String,Object> {
                    // 'location' => 'id_externo'
                })))
            }
        }));
        RestContext.request = request;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IntegrationGoogle_Mock());

        IntegrationGoogle.eventListener();

        Test.stopTest();
    }

    @isTest
    public static void getToken_test() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IntegrationGoogle_Mock());
        String token = IntegrationGoogle.getToken();

        System.assertEquals('access_token_value', token, 'ERROR - wrong token received');
        Test.stopTest();
    }

    @isTest
    public static void postReply_test() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IntegrationGoogle_Mock());
        List<String> responses = GooglePostReplyInvocable.postReplyInvocable((new List<CustomerReview__c>{new CustomerReview__c()}));

        Test.stopTest();
    }
}