force-app/main/default/objects/Ayuda_Portal__c/Ayuda_Portal__c.object-meta.xml
<CustomObject>
    <label>Ayuda Portal</label>
    <nameField>
        <label>Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ayuda Portal</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ayuda_Portal__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ayuda_Portal__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DocumentosRequeridos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ayuda_Portal__c/fields/InlineHelp__c.field-meta.xml
<CustomField>
    <fullName>InlineHelp__c</fullName>
    <label>Ayuda inline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ayuda_Portal__c/fields/Producto__c.field-meta.xml
<CustomField>
    <fullName>Producto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Ayuda Portal</relationshipLabel>
    <relationshipName>Ayuda_Portal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ayuda_Portal__c/fields/Respuesta__c.field-meta.xml
<CustomField>
    <fullName>Respuesta__c</fullName>
    <label>Respuesta</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ayuda_Portal__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <formula>HYPERLINK(  Link__c  ,  T_tulo_Link__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Video</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PortalHelpRepository.cls
/*
@author LeadClic Solutions S.L.
@date 13/10/2023
@description Clase PortalHelpRepository: define una interfaz util para obtener 
los registros de Ayuda_Portal__c
<pre>
FECHA             AUTOR           ACCION
13/10/2023		LCS - SDF	   	  Creación.
*/
public with sharing class PortalHelpRepository {
    
    public static List<Ayuda_Portal__c> getHelpFromProductId(Id productId) {
        return [
            SELECT 
                Name,Producto__c,Documento__c,Descripcion__c,
                Link__c,Video__c,InlineHelp__c,Respuesta__c
            FROM Ayuda_Portal__c
            WHERE Producto__c =:productId
        ];
    }
}