force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>From what time this setting is effective for meeting scheduling</description>
    <label>Effective - From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>To what time this setting is effective for meeting scheduling</description>
    <label>Effective - To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/CalendarTimetable__c.object-meta.xml
<CustomObject>
    <description>Junction object related to Calendar Setting and Timetable. Allows many-to.may relations.</description>
    <label>Relación de Horarios y Calendarios</label>
    <nameField>
        <displayFormat>CT-{000000000}</displayFormat>
        <label>Calendar Timetable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones de Horarios y Calendarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarTimetable__c/fields/CalendarSetting__c.field-meta.xml
<CustomField>
    <fullName>CalendarSetting__c</fullName>
    <label>Calendar Setting</label>
    <referenceTo>CalendarSetting__c</referenceTo>
    <relationshipLabel>Calendars Timetable</relationshipLabel>
    <relationshipName>CalendarTimetables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TriggerCalendarTimeTableHandler.cls
/** 
 * CalendarTimetable handle trigger
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-10-08
 */
public class TriggerCalendarTimeTableHandler {
   
    public static void beforeInsert (List<CalendarTimetable__c> lNewCalendarTimetable) {
        checkEffectiveDatesOverlapping(lNewCalendarTimetable, null);                                  
    }

    public static void beforeUpdate (List<CalendarTimetable__c> lNewCalendartimetable, Map<Id, CalendarTimetable__c> mOldCalendarTimetable) {
        checkEffectiveDatesOverlapping(lNewCalendarTimetable, mOldCalendarTimetable);
    }


    private static void checkEffectiveDatesOverlapping (List<CalendarTimetable__c> lNewCalendartimetable, Map<Id, CalendarTimetable__c> mOldCalendarTimetable) {

        Map<Id, List<CalendarTimeTable__c>> mCalendarSetting_lCalendarTT = new Map<Id, List<CalendarTimeTable__c>>(); // Key: CalendarSetting Id, Value: List of CalendarTimetable 
        for (CalendarTimetable__c calendarTT : lNewCalendarTimetable){        
            // If it's an update and Effective Dates changes, or it's an insert
            if ( (mOldCalendarTimetable != null 
                && (mOldCalendarTimetable.get(calendarTT.Id).EffectiveFrom__c != calendarTT.EffectiveFrom__c || mOldCalendarTimetable.get(calendarTT.Id).EffectiveTo__c != calendarTT.EffectiveTo__c) )
                || mOldCalendarTimetable == null){

                List<CalendarTimetable__c> lCalendarTTMap = new List<CalendarTimetable__c>();
                if (mCalendarSetting_lCalendarTT.containsKey(calendarTT.CalendarSetting__c)){
                    lCalendarTTMap = mCalendarSetting_lCalendarTT.get(calendarTT.CalendarSetting__c);
                }
                lCalendarTTMap.add(calendarTT);

                mCalendarSetting_lCalendarTT.put(calendarTT.CalendarSetting__c, lCalendarTTMap);
            }
        }

        Set<Id> sCurrentId = mOldCalendarTimetable != null ? mOldCalendarTimetable.keySet() : new Set<Id>();
        
        List<CalendarTimeTable__c> lCalendarTT = [SELECT Id, CalendarSetting__c, EffectiveFrom__c, EffectiveTo__c 
                                                    FROM CalendarTimeTable__c 
                                                    WHERE CalendarSetting__c IN :mCalendarSetting_lCalendarTT.keySet() AND Id NOT IN :sCurrentId];

        for (CalendarTimetable__c calendarTT : lCalendarTT){
            if (mCalendarSetting_lCalendarTT.containsKey(calendarTT.CalendarSetting__c)){
                for (CalendarTimetable__c calendarTTFromTrigger: mCalendarSetting_lCalendarTT.get(calendarTT.CalendarSetting__c)){
                    if ((calendarTTFromTrigger.EffectiveFrom__c <= calendarTT.EffectiveFrom__c && calendarTTFromTrigger.EffectiveTo__c >= calendarTT.EffectiveFrom__c)  
                        || (calendarTTFromTrigger.EffectiveFrom__c >= calendarTT.EffectiveFrom__c && calendarTTFromTrigger.EffectiveFrom__c <= calendarTT.EffectiveTo__c)){
                        
                        calendarTTFromTrigger.addError(Label.overlappingCalendarTimetableDates);
                    }
                }
            }
        }       

    }


}