force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/HolidayAbsence__c.object-meta.xml
<CustomObject>
    <description>Object related with a Calendar Id, indicates the unavailable dates of an user or resource</description>
    <label>Vacaciones / Bloqueos</label>
    <nameField>
        <displayFormat>HA-{000000}</displayFormat>
        <label>Absence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacaciones / Bloqueos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HolidayAbsence__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Calendar Id of user or resource</description>
    <label>Calendar Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HolidayAbsenceRelatedListControllerTest.cls
@isTest
private class HolidayAbsenceRelatedListControllerTest {

    @isTest static void testGetHolidayAbsenceByCalendarId() {
        CalendarSetting__c calSetting = SchDataTest.createCalendarSetting('User');
        insert calSetting;

        HolidayAbsence__c holidayAbsence = SchDataTest.createHolidayAbsence(calSetting.CalendarId__c);
        insert holidayAbsence;

        Test.startTest();
        HolidayAbsenceRelatedListController.getHolidayAbsenceByCalendarId(calSetting.Id);
        Test.stopTest();
    }

    @isTest static void testCatch () {
        Test.startTest();
        HolidayAbsenceRelatedListController.getHolidayAbsenceByCalendarId(null);
        Test.stopTest();
    }
}