force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>From what time this setting is effective for meeting scheduling</description>
    <label>Effective - From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>To what time this setting is effective for meeting scheduling</description>
    <label>Effective - To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/HolidayCalendar__c.field-meta.xml
<CustomField>
    <fullName>HolidayCalendar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holiday Calendar</label>
    <referenceTo>HolidayCalendar__c</referenceTo>
    <relationshipLabel>Calendar Settings</relationshipLabel>
    <relationshipName>Calendar_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <description>Indicates a user or resource subtype</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asesor</fullName>
            </value>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Sala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Calendar type for resource or user requesting from the meeting scheduler</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Resource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/CalendarTimetable__c.object-meta.xml
<CustomObject>
    <description>Junction object related to Calendar Setting and Timetable. Allows many-to.may relations.</description>
    <label>Relación de Horarios y Calendarios</label>
    <nameField>
        <displayFormat>CT-{000000000}</displayFormat>
        <label>Calendar Timetable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones de Horarios y Calendarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarTimetable__c/fields/CalendarSetting__c.field-meta.xml
<CustomField>
    <fullName>CalendarSetting__c</fullName>
    <label>Calendar Setting</label>
    <referenceTo>CalendarSetting__c</referenceTo>
    <relationshipLabel>Calendars Timetable</relationshipLabel>
    <relationshipName>CalendarTimetables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/Timetable__c.field-meta.xml
<CustomField>
    <fullName>Timetable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timetable</label>
    <referenceTo>Timetable__c</referenceTo>
    <relationshipLabel>Calendars Timetable</relationshipLabel>
    <relationshipName>CalendarTimetables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day__c/Day__c.object-meta.xml
<CustomObject>
    <description>Day of a Holiday Calendar</description>
    <label>Día Festivo</label>
    <nameField>
        <label>Day Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Días Festivos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Day__c/fields/HolidayZone__c.field-meta.xml
<CustomField>
    <fullName>HolidayZone__c</fullName>
    <description>Parent holiday zone, used for holidays grouping</description>
    <label>Holiday Zone</label>
    <referenceTo>HolidayZone__c</referenceTo>
    <relationshipLabel>Days</relationshipLabel>
    <relationshipName>Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/HolidayAbsence__c.object-meta.xml
<CustomObject>
    <description>Object related with a Calendar Id, indicates the unavailable dates of an user or resource</description>
    <label>Vacaciones / Bloqueos</label>
    <nameField>
        <displayFormat>HA-{000000}</displayFormat>
        <label>Absence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacaciones / Bloqueos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HolidayAbsence__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Calendar Id of user or resource</description>
    <label>Calendar Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HolidayCalendarZone__c/HolidayCalendarZone__c.object-meta.xml
<CustomObject>
    <description>Junction object related to Calendar Holiday and Zone.</description>
    <label>Relación de Zonas y Calendario</label>
    <nameField>
        <displayFormat>CZ-{00000}</displayFormat>
        <label>Holiday Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones de Zonas y Calendario</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HolidayCalendarZone__c/fields/HolidayCalendar__c.field-meta.xml
<CustomField>
    <fullName>HolidayCalendar__c</fullName>
    <label>Holiday Calendar</label>
    <referenceTo>HolidayCalendar__c</referenceTo>
    <relationshipLabel>Relaciones de Zonas y Calendario</relationshipLabel>
    <relationshipName>HolidayCalendarZones</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timetable__c/Timetable__c.object-meta.xml
<CustomObject>
    <label>Horario</label>
    <nameField>
        <label>Time Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Horarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetable__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <label>Effective - From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <label>Effective - To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/FridayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>FridayAfterFrom__c</fullName>
    <label>Friday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/FridayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>FridayAfterTo__c</fullName>
    <label>Friday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/FridayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>FridayMorningFrom__c</fullName>
    <label>Friday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/FridayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>FridayMorningTo__c</fullName>
    <label>Friday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/MondayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>MondayAfterFrom__c</fullName>
    <label>Monday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/MondayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>MondayAfterTo__c</fullName>
    <label>Monday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/MondayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>MondayMorningFrom__c</fullName>
    <label>Monday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/MondayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>MondayMorningTo__c</fullName>
    <label>Monday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SaturdayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>SaturdayAfterFrom__c</fullName>
    <label>Saturday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SaturdayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>SaturdayAfterTo__c</fullName>
    <label>Saturday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SaturdayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>SaturdayMorningFrom__c</fullName>
    <label>Saturday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SaturdayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>SaturdayMorningTo__c</fullName>
    <label>Saturday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SundayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>SundayAfterFrom__c</fullName>
    <label>Sunday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SundayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>SundayAfterTo__c</fullName>
    <label>Sunday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SundayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>SundayMorningFrom__c</fullName>
    <label>Sunday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/SundayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>SundayMorningTo__c</fullName>
    <label>Sunday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/ThursdayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>ThursdayAfterFrom__c</fullName>
    <label>Thursday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/ThursdayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>ThursdayAfterTo__c</fullName>
    <label>Thursday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/ThursdayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>ThursdayMorningFrom__c</fullName>
    <label>Thursday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/ThursdayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>ThursdayMorningTo__c</fullName>
    <label>Thursday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/TuesdayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>TuesdayAfterFrom__c</fullName>
    <label>Tuesday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/TuesdayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>TuesdayAfterTo__c</fullName>
    <label>Tuesday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/TuesdayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>TuesdayMorningFrom__c</fullName>
    <label>Tuesday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/TuesdayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>TuesdayMorningTo__c</fullName>
    <label>Tuesday Mor (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/WednesdayAfterFrom__c.field-meta.xml
<CustomField>
    <fullName>WednesdayAfterFrom__c</fullName>
    <label>Wednesday Aft. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/WednesdayAfterTo__c.field-meta.xml
<CustomField>
    <fullName>WednesdayAfterTo__c</fullName>
    <label>Wednesday Aft. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/WednesdayMorningFrom__c.field-meta.xml
<CustomField>
    <fullName>WednesdayMorningFrom__c</fullName>
    <label>Wednesday Mor. (from)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/WednesdayMorningTo__c.field-meta.xml
<CustomField>
    <fullName>WednesdayMorningTo__c</fullName>
    <label>Wednesday Mor. (to)</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/SchDataTest.cls
/** 
 * Clic2Meet data factory to Test classes
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-09-17
 */
public class SchDataTest {

    public static List<String> getSubtypesFromType (String resourcetype) {
        // Get subtypes from Schema
		Schema.DescribeFieldResult fieldSubtype = CalendarSetting__c.Subtype__c.getDescribe();
		List<Schema.PicklistEntry> lFieldSubtype = fieldSubtype.getPicklistValues();


/*
        for (Integer i=0; i<lFieldSubtype.size() && subtypeLabel =='' && subtypeValue==''; i++){
            System.debug('<<getSubtypesFromType FOR VALUE>>  '+lFieldSubtype[i].getValue() );
            System.debug('<<getSubtypesFromType FOR LABEL>>  '+lFieldSubtype[i].getLabel() );
            if (lFieldSubtype[i].getValue().containsIgnoreCase(resourcetype)){
                subtypeLabel = lFieldSubtype[i].getLabel(); 
                subtypeValue = lFieldSubtype[i].getValue();
            }
        }
		*/
        List<String> lSubtype = new List<String>();
        
        if (resourcetype == 'Resource'){
            
            String subtypeLabel = 'Sala';
        	String subtypeValue = 'Sala';
            
            lSubtype.add(subtypeLabel);
        	lSubtype.add(subtypeValue);
        }
        
        if (resourcetype == 'User'){
            
            String subtypeLabel = 'Administrativo';
        	String subtypeValue = 'Administrativo';
            
            lSubtype.add(subtypeLabel);
        	lSubtype.add(subtypeValue);
        }
        
        
        
        //List<String> lSubtype = new List<String>();
        //lSubtype.add(subtypeLabel);
        //lSubtype.add(subtypeValue);

        return lSubtype;
    }

    /*public static List<String> getLastSubtypesFromType (String resourcetype) {
        // Get subtypes from Schema
		Schema.DescribeFieldResult fieldSubtype = CalendarSetting__c.Subtype__c.getDescribe();
		List<Schema.PicklistEntry> lFieldSubtype = fieldSubtype.getPicklistValues();

        String subtypeLabel = '';
        String subtypeValue = '';

        for (Integer i=0; i<lFieldSubtype.size(); i++){
            if (lFieldSubtype[i].getValue().containsIgnoreCase(resourcetype)){
                subtypeLabel = lFieldSubtype[i].getLabel(); 
                subtypeValue = lFieldSubtype[i].getValue();
            }
        }

        List<String> lSubtype = new List<String>();
        lSubtype.add(subtypeLabel);
        lSubtype.add(subtypeValue);

        return lSubtype;
    }*/

    public static CalendarSetting__c createCalendarSetting (String resourcetype) {

        List<String> lSubtype = getSubtypesFromType(resourcetype);
        String subtypeValue = lSubtype.size() >= 1 ? lSubtype[1] : '';

        // DML operation Insert not allowed on Calendar, so we have to query it
        Calendar cal = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() limit 1];
        CalendarSetting__c cSet = new CalendarSetting__c(CalendarId__c = cal.Id, Subtype__c = subtypeValue, Type__c = resourcetype);

        return cSet;
    }

    /*public static CalendarSetting__c createCalendarSettingDiffSubtype (String resourcetype) {

        List<String> lSubtype = getLastSubtypesFromType(resourcetype);
        String subtypeValue = lSubtype.size() >= 1 ? lSubtype[1] : '';

        // DML operation Insert not allowed on Calendar, so we have to query it
        Calendar cal = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() limit 1];
        CalendarSetting__c cSet = new CalendarSetting__c(CalendarId__c = cal.Id, Subtype__c = subtypeValue, Type__c = resourcetype);

        return cSet;
    }*/

    public static Lead createLead () {
        Lead l = new Lead(LastName = 'testLNLead', FirstName = 'test', Company='Test company', PostalCode='12345', Email = 'test@test.com', Phone= '666666666');
        return l;
    }

    public static Event createEvent (Id leadId, Datetime startEvent, Datetime endEvent) {
        Event evt = new Event();
        evt.WhoId = leadId;
        evt.Subject = 'Test Subject';
        evt.StartDateTime = startEvent;
        evt.EndDateTime = endEvent;

        return evt;
    }

    public static Timetable__c createTimetable () {

        Timetable__c tt = new Timetable__c();

        tt.MondayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.MondayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.MondayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.MondayAfterTo__c = Time.newInstance(19, 00, 0, 0);
        
        tt.TuesdayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.TuesdayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.TuesdayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.TuesdayAfterTo__c = Time.newInstance(19, 00, 0, 0);
        
        tt.WednesdayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.WednesdayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.WednesdayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.WednesdayAfterTo__c = Time.newInstance(19, 00, 0, 0);
        
        tt.ThursdayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.ThursdayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.ThursdayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.ThursdayAfterTo__c = Time.newInstance(19, 00, 0, 0);
        
        tt.FridayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.FridayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.FridayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.FridayAfterTo__c = Time.newInstance(19, 00, 0, 0);

        tt.SaturdayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.SaturdayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.SaturdayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.SaturdayAfterTo__c = Time.newInstance(19, 00, 0, 0);

        tt.SundayMorningFrom__c = Time.newInstance(9, 30, 0, 0);
        tt.SundayMorningTo__c = Time.newInstance(14, 30, 0, 0);
        tt.SundayAfterFrom__c = Time.newInstance(15, 30, 0, 0);
        tt.SundayAfterTo__c = Time.newInstance(19, 00, 0, 0);

        return tt;  
    }

    public static CalendarTimetable__c createCalendarTimetable (Id calendarSettingId, Id timetableId) {

        CalendarTimetable__c calTt = new CalendarTimetable__c();
        calTt.EffectiveFrom__c = System.now().addDays(-30);
        calTt.EffectiveTo__c = System.now().addDays(30);
        calTt.CalendarSetting__c = calendarSettingId;
        calTt.Timetable__c = timetableId;

        return calTt;
    }

    public static CalendarTimetable__c createCalendarTimetable (Id calendarSettingId, Id timetableId, Datetime effectiveFrom, Datetime effectiveTo) {

        CalendarTimetable__c calTt = new CalendarTimetable__c();
        calTt.EffectiveFrom__c = effectiveFrom;
        calTt.EffectiveTo__c = effectiveTo;
        calTt.CalendarSetting__c = calendarSettingId;
        calTt.Timetable__c = timetableId;

        return calTt;
    }

    public static HolidayCalendar__c createHolidayCalendar () {

        HolidayZone__c zone = new HolidayZone__c(Name = 'Test holiday');
        insert zone;

        Day__c holiday = new Day__c (Holiday__c = System.today().addDays(1), HolidayZone__c = zone.Id);
        insert holiday;

        HolidayCalendar__c holidayCalendar = new HolidayCalendar__c(Name = 'Test Holiday calendar');
        insert holidaycalendar;

        HolidayCalendarZone__c calendarZone = new HolidayCalendarZone__c(HolidayCalendar__c = holidayCalendar.Id, HolidayZone__c = zone.Id);
        insert calendarZone;

        return holidaycalendar;
    }

    public static HolidayAbsence__c createHolidayAbsence (Id calendarId) {
        HolidayAbsence__c holidayAbsence = new HolidayAbsence__c( CalendarId__c = calendarId,
                                                                StartDate__c = system.now().addDays(-2), 
                                                                EndDate__c = system.now().addDays(-1), 
                                                                Comments__c = 'Test comments');

        return holidayAbsence;                                                           
    }


}