force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>From what time this setting is effective for meeting scheduling</description>
    <label>Effective - From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>To what time this setting is effective for meeting scheduling</description>
    <label>Effective - To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/CalendarTimetable__c.object-meta.xml
<CustomObject>
    <description>Junction object related to Calendar Setting and Timetable. Allows many-to.may relations.</description>
    <label>Relación de Horarios y Calendarios</label>
    <nameField>
        <displayFormat>CT-{000000000}</displayFormat>
        <label>Calendar Timetable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relaciones de Horarios y Calendarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarTimetable__c/fields/CalendarSetting__c.field-meta.xml
<CustomField>
    <fullName>CalendarSetting__c</fullName>
    <label>Calendar Setting</label>
    <referenceTo>CalendarSetting__c</referenceTo>
    <relationshipLabel>Calendars Timetable</relationshipLabel>
    <relationshipName>CalendarTimetables</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <description>Calendar Setting and time table intersection date</description>
    <label>Effective - To</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CalendarTimetable__c/fields/Timetable__c.field-meta.xml
<CustomField>
    <fullName>Timetable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Timetable</label>
    <referenceTo>Timetable__c</referenceTo>
    <relationshipLabel>Calendars Timetable</relationshipLabel>
    <relationshipName>CalendarTimetables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SearchSetup__c/SearchSetup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains search setup values</description>
    <label>Search Setup</label>
</CustomObject>

force-app/main/default/objects/SearchSetup__c/fields/EffectiveDatesOverlappingControl__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDatesOverlappingControl__c</fullName>
    <defaultValue>true</defaultValue>
    <description>To avoid effective dates overlapping in CalendarTimetable object</description>
    <label>Effective Dates Overlapping Control</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Timetable__c/Timetable__c.object-meta.xml
<CustomObject>
    <label>Horario</label>
    <nameField>
        <label>Time Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Horarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timetable__c/fields/EffectiveFrom__c.field-meta.xml
<CustomField>
    <fullName>EffectiveFrom__c</fullName>
    <label>Effective - From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Timetable__c/fields/EffectiveTo__c.field-meta.xml
<CustomField>
    <fullName>EffectiveTo__c</fullName>
    <label>Effective - To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TriggerCalendarTimetableTest.cls
/** 
 * Test class of CalendarTimetable handler trigger
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-10-08
 */
@isTest
private class TriggerCalendarTimetableTest {

    @TestSetup
    static void setup(){
        SearchSetup__c cs = new SearchSetup__c();
        cs.EffectiveDatesOverlappingControl__c = true;
        insert cs;
    }

    @isTest
    private static void testTriggerCalendartimetable(){      

        CalendarSetting__c calSet = SchDataTest.createCalendarSetting('User');
        insert calSet;

        Timetable__c timetable = SchDataTest.createTimetable();
        insert timetable;    

        List<CalendarTimetable__c> lInsertCalTT = new List<CalendarTimetable__c>();

        CalendarTimetable__c calTT1 = SchDataTest.createCalendarTimetable(calSet.Id, timetable.Id, System.now().addDays(-30), System.now().addDays(30));
        lInsertCalTT.add(calTT1);

        CalendarTimetable__c calTT2 = SchDataTest.createCalendarTimetable(calSet.Id, timetable.Id, System.now().addDays(45), System.now().addDays(50));
        lInsertCalTT.add(calTT2);

        insert lInsertCalTT;

        Test.startTest();

        // Overlapping insert
        CalendarTimetable__c calTT3 = SchDataTest.createCalendarTimetable(calSet.Id, timetable.Id, System.now().addDays(-15), System.now().addDays(25));
        try{
            insert calTT3;
        }catch(Exception e){      
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.overlappingCalendarTimetableDates);
            System.AssertEquals(expectedExceptionThrown, true);
        }

        // Overlapping update
        calTT2.EffectiveFrom__c = System.now().addDays(-15);
        calTT2.EffectiveTo__c = System.now().addDays(25);
        try{
            update calTT2;
        }catch(Exception e){      
            Boolean expectedExceptionThrown =  e.getMessage().contains(Label.overlappingCalendarTimetableDates);
            System.AssertEquals(expectedExceptionThrown, true);
        }

        Test.stopTest();
    }
}