force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Oficina__c.field-meta.xml
<CustomField>
    <fullName>Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo test para los filtros</description>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La oficina no pertenece a la provincia indicada</errorMessage>
        <filterItems>
            <field>Account.ShippingState</field>
            <operation>equals</operation>
            <valueField>$Source.Provincia__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendar Settings</relationshipLabel>
    <relationshipName>CalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Provincia__c.field-meta.xml
<CustomField>
    <fullName>Provincia__c</fullName>
    <label>Provincia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>La Coruña</fullName>
            </value>
            <value>
                <fullName>Álava</fullName>
            </value>
            <value>
                <fullName>Albacete</fullName>
            </value>
            <value>
                <fullName>Alicante</fullName>
            </value>
            <value>
                <fullName>Almería</fullName>
            </value>
            <value>
                <fullName>Asturias</fullName>
            </value>
            <value>
                <fullName>Ávila</fullName>
            </value>
            <value>
                <fullName>Badajoz</fullName>
            </value>
            <value>
                <fullName>Baleares</fullName>
            </value>
            <value>
                <fullName>Barcelona</fullName>
            </value>
            <value>
                <fullName>Vizcaya</fullName>
            </value>
            <value>
                <fullName>Burgos</fullName>
            </value>
            <value>
                <fullName>Cáceres</fullName>
            </value>
            <value>
                <fullName>Cádiz</fullName>
            </value>
            <value>
                <fullName>Cantabria</fullName>
            </value>
            <value>
                <fullName>Castellón</fullName>
            </value>
            <value>
                <fullName>Ciudad Real</fullName>
            </value>
            <value>
                <fullName>Córdoba</fullName>
            </value>
            <value>
                <fullName>Cuenca</fullName>
            </value>
            <value>
                <fullName>Guipúzcoa</fullName>
            </value>
            <value>
                <fullName>Gerona</fullName>
            </value>
            <value>
                <fullName>Granada</fullName>
            </value>
            <value>
                <fullName>Guadalajara</fullName>
            </value>
            <value>
                <fullName>Huelva</fullName>
            </value>
            <value>
                <fullName>Huesca</fullName>
            </value>
            <value>
                <fullName>Jaén</fullName>
            </value>
            <value>
                <fullName>La Rioja</fullName>
            </value>
            <value>
                <fullName>Las Palmas</fullName>
            </value>
            <value>
                <fullName>León</fullName>
            </value>
            <value>
                <fullName>Lérida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Videollamada__c.field-meta.xml
<CustomField>
    <fullName>Videollamada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Videollamada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Cita.recordType-meta.xml
<RecordType>
    <fullName>Cita</fullName>
    <active>true</active>
    <label>Cita</label>
</RecordType>

force-app/main/default/objects/PerfilesCallCenter__c/PerfilesCallCenter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IDs de los perfiles de Call Center, para asignar citas sin escoger usuarios y salas manualmente</description>
    <label>Perfiles Call Center</label>
</CustomObject>

force-app/main/default/objects/PerfilesCallCenter__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>Id del perfil en formato de 18 caracteres</description>
    <label>Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo id externo, el standard de Salesforce no permite realizar operaciones de upsert al no estar definido como externalId</description>
    <externalId>true</externalId>
    <label>Id externo</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SearchSetup__c/SearchSetup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains search setup values</description>
    <label>Search Setup</label>
</CustomObject>

force-app/main/default/objects/SearchSetup__c/fields/SearchByEvents__c.field-meta.xml
<CustomField>
    <fullName>SearchByEvents__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Search by events yet created istead of Calendar Timetable of Calendar Setting</description>
    <label>Search By Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SearchSetup__c/fields/SearchDaysForward__c.field-meta.xml
<CustomField>
    <fullName>SearchDaysForward__c</fullName>
    <defaultValue>7</defaultValue>
    <description>Days fordward to search from today</description>
    <label>Search days forward</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SchExtendedFeaturesImplementation.cls
/** 
 * Clic2Meet interface implementation for Arriaga 
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-07-02
 */
public without sharing class SchExtendedFeaturesImplementation implements SchExtendedFeatures{
    
    private static final Decimal STANDARD_DAYS_FORWARD = 7.0;

    /**
     * setInitParams overrides main scheduler inicializaton params. Included url params.
     * @param  attendeeId attendee id (lead, contact or person account Id)
     * @return            return map with params values
     */ 
     public static Map<String, Object> setInitParams (Id attendeeId){

        SearchSetup__c cs = SearchSetup__c.getInstance();
        
        if (cs.SearchDaysForward__c == null) cs.SearchDaysForward__c = STANDARD_DAYS_FORWARD;

        Map<String, Object> mParams = new Map<String, Object>();
        Date toDate = System.today().addDays((Integer)cs.SearchDaysForward__c);
        mParams.put('searchToDate', toDate.year() + '-' + toDate.month() + '-' + toDate.day());
        mParams.put('searchByEvents', cs.SearchByEvents__c != null && cs.SearchByEvents__c);
        // If the current profile is Call Center
        List<PerfilesCallCenter__c> lPcs = PerfilesCallCenter__c.getall().values();
        for (PerfilesCallCenter__c pcs : lPcs){
            if (pcs.Id__c == UserInfo.getProfileId()){
                mParams.put('isSummaryResult', true);
                break;
            }
        }

        List<String> lCustomValidation = new List<String>();

        // Oficina__c filter
        lCustomValidation.add('filterValues.Oficina__c');
        
        // Product validation (list not empty)
        lCustomValidation.add('extraParams.products');

        mParams.put('customValidation', lCustomValidation);
         

        return mParams;
     }

    
    /**
     * setInitFilterParams description
     * @mParams  params params passed from front-ent
     * @return   return description
     */ 
    public Map<String, Object> setInitFilterParams ( Map<Object, Object> mParams) {

        Map<String, Object> mReturn = new Map<String, Object>();

        // itinerantes use case
        if(mParams != null && mParams.containsKey('Oficina__c') && (String)mParams.get('Oficina__c') != '') {

            String officeId = (String)mParams.get('Oficina__c');
           
            List<Account> lOffice = [SELECT Id, Name, ShippingCity FROM Account WHERE Id = :officeId];
            if(!lOffice.isEmpty()) {
                LookupSearchResult initValues = new LookupSearchResult(lOffice[0].Id, 'Account', 'standard:account', lOffice[0].Name, ('Account • ' +lOffice[0].ShippingCity));
                mReturn.put('Oficina__c', initValues);
            }

        // standard init searching current calendar setting 
        } else {
            
            // Calendar setting retrieval
            List<Calendar> lCal = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() LIMIT 1];
    
            if (!lCal.isEmpty()) {

                // Calendar  Settings retrieval
                List<CalendarSetting__c> lSetting = [SELECT Id, Oficina__c, Provincia__c 
                                                    FROM CalendarSetting__c 
                                                    WHERE CalendarId__c = :lCal[0].Id LIMIT 1];
                if(!lSetting.isEmpty()) {
                    
                    if(lSetting[0].Provincia__c != null) {
                        mReturn.put('Provincia__c', lSetting[0].Provincia__c);
                    }
                    
                    if(lSetting[0].Oficina__c != null) {
                        // Recuperación de la cuenta asociada
                        List<Account> lAcc = [SELECT Id, Name, ShippingCity FROM Account WHERE Id = :lSetting[0].Oficina__c LIMIT 1];
                        if(!lAcc.isEmpty()) {
                            LookupSearchResult initValues = new LookupSearchResult(lAcc[0].Id, 'Account', 'standard:account', lAcc[0].Name, ('Account • ' +lAcc[0].ShippingCity));
                            mReturn.put('Oficina__c', initValues);
                        }
                    }  
                }
            }
        }

        
        return mReturn;
    } 


    /**
     * Fill event info with custom data, overrides standard event creation
     * @param  evt           event being created
     * @param  mParams       event info for event creation
     * @param  mCalendarUser calendar settings ids
     * @return               created event
     */ 
    public Event setEventParams (Event evt, Map<Object, Object> mParams, Map<Id, Id> mCalendarUser){


        Map<Object, Object> assignedTo = (Map<Object, Object>) mParams.get('assignedTo');
        Map<Object, Object> lResource = (Map<Object, Object>) mParams.get('lResource');
        Map<Object, Object> filterValues = (Map<Object, Object>) mParams.get('filterValues');
        Map<Object, Object> extraParams = (Map<Object, Object>) mParams.get('extraParams');
        String productosInteres = '';
        if(extraParams != null) {
            try {
                List<Object> lProduct = (List<Object>) extraParams.get('products'); 
                Set<String> sId = new Set<String>();
                Set<String> sIdPrincipal = new Set<String>();
                
                for(Object productInfo : lProduct) {
                    Map<Object, Object> wrapper = (Map<Object, Object>) productInfo;
                    String principal = (String)wrapper.get('name');
                    List<String> lSplit = principal.split('-');
                    if (lSplit[1].contains('true')){
                        sIdPrincipal.add(lSplit[0]);
                        sId.add(lSplit[0]);
                    }
                    else{
                        sId.add(lSplit[0]);
                    }
                }

                List<String> lProductId = new List<String>();
                List<String> lProductInteres = new List<String>();
                for(Product2 p : [SELECT Id, ExternalId__c,Name FROM Product2 WHERE Id IN :sId]) {
                    lProductId.add(p.ExternalId__c);
                    if(sIdPrincipal.contains(p.Id)){
                        lProductInteres.add(p.Name);
                    }
                }
                String productListConcat = String.join(lProductId, ';');
                productosInteres = String.join(lProductInteres,',');
                evt.Productos__c = productListConcat;
            } catch (Exception e) {
                System.debug('Exception related product: ' + e.getMessage() + e.getStackTraceString());
            }
        }

        // Standard Fields
        evt.StartDatetime = (Datetime) mParams.get('startDate');
        evt.EndDateTime = (Datetime) mParams.get('endDate');
        evt.Subject = 'Cita'; // todo, set this field in custom setting
        evt.WhoId = (Id) mParams.get('attendeeId');
        if (productosInteres != '') evt.Description = (String) mParams.get('comments') + ' Es producto principal ' + productosInteres;
        else evt.Description = (String) mParams.get('comments');
		
        
        // Custom Fields
        List<Object> videoMeeting = (List<Object>) extraParams.get('typeSelected');
        
        String attendeeId = String.valueOf(evt.WhoId);
        evt.Estado__c = 'Pendiente';
        evt.TipoCita__c = (String) mParams.get('appointmentType');
        if(!Test.isRunningTest() && videoMeeting != null && videoMeeting.size() != 0) {
        	evt.Videollamada__c = videoMeeting[0] == 'Videollamada' ? true : false;
        }
        
        List<Object> notSendMail = (List<Object>) extraParams.get('sendMail');
		if(!Test.isRunningTest() && notSendMail != null && notSendMail.size() != 0 && notSendMail[0]=='No enviar correo al cliente') {
        	evt.No_enviar_email_Confirmacion_de_Cita__c = true;
        }
        
        List<EventRelation> lRelation = new List<EventRelation>();

        // Asesor
        if(assignedTo.containsKey('Asesor')) {
            Id calendarAsesorId = (Id) assignedTo.get('Asesor');    
            evt.OwnerId = mCalendarUser.get(calendarAsesorId);
        }
        
        // Administrativo
        if(assignedTo.containsKey('Administrativo')) {
            Id calendarAdmId = (Id) assignedTo.get('Administrativo');
            Id userAdmId = mCalendarUser.get(calendarAdmId);

            // if not Asesor role present
            if( evt.OwnerId == null) {
                evt.OwnerId = userAdmId;
            
            // relation creation if asesor role is present
            } else {
                EventRelation rel = new EventRelation();   
                rel.RelationId = userAdmId;
                lRelation.add(rel);
            }
        }

        // Event relations
        for(Object resourceId : lResource.values()) {
            EventRelation rel = new EventRelation();
            rel.RelationId = (Id)resourceId;
            rel.Status = 'Accepted';
            lRelation.add(rel);
        }
		
        // Office
       	
        if(filterValues.containsKey('Oficina__c') && filterValues.get('Oficina__c') != null && filterValues.get('Oficina__c') != ''){
            evt.Oficina__c = (Id) filterValues.get('Oficina__c');
        }
       
        insert evt;
                
        for(EventRelation rel : lRelation) {
            rel.EventId = evt.Id;
        }

        insert lRelation;
        return evt;
    }

}