force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Oficina__c.field-meta.xml
<CustomField>
    <fullName>Oficina__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo test para los filtros</description>
    <label>Oficina</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>La oficina no pertenece a la provincia indicada</errorMessage>
        <filterItems>
            <field>Account.ShippingState</field>
            <operation>equals</operation>
            <valueField>$Source.Provincia__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calendar Settings</relationshipLabel>
    <relationshipName>CalendarSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Subtype__c.field-meta.xml
<CustomField>
    <fullName>Subtype__c</fullName>
    <description>Indicates a user or resource subtype</description>
    <label>Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asesor</fullName>
            </value>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Sala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchMainResourcesInterfaceImplementation.cls
/** 
 * Custom implementation for custom user/resource list retrieval.
 * @author Leadclic Solutions
 * @version 1.0
 * @since 2019-10-01
 */
public with sharing class SchMainResourcesInterfaceImplementation implements SchMainResourcesInterface {
   
    // ----------------------- control variables ----------------------
    public static Boolean GET_RESOURCE_LIST_CUSTOM_ACTIVE = true;


    public static List<CalendarSetting__c> getResourceListWithCustomCriteria (Set<String> sSubtype){

        List<CalendarSetting__c> lCS = new List<CalendarSetting__c>();

        // Query current user
        List<Calendar> lCurrentCalendar = [SELECT Id FROM Calendar WHERE UserId = :UserInfo.getUserId() LIMIT 1];

            if(!lCurrentCalendar.isEmpty()) {
                Set<Id> sOfficeId = new Set<Id>();
                
                // query current Calendar Setting
                for(CalendarSetting__C currentCalendar : [SELECT Id, Oficina__c, Subtype__c FROM CalendarSetting__c WHERE CalendarId__c = :lCurrentCalendar[0].Id]) {
                    if(currentCalendar.Oficina__c != null) {
                        sOfficeId.add(currentCalendar.Oficina__c);
                    }
                }

                if(!sOfficeId.isEmpty()) {
                    lCS = [SELECT Id, Subtype__c, CalendarId__c 
                            FROM CalendarSetting__c  
                            WHERE (Subtype__c IN :sSubtype) AND (Oficina__c IN :sOfficeId)];
                }
            }

        return lCS;
    }
}