force-app/main/default/objects/CalendarSetting__c/CalendarSetting__c.object-meta.xml
<CustomObject>
    <description>Calendar settings to customize calendars with additional data and timetables</description>
    <label>Configuración de Calendario</label>
    <nameField>
        <label>Calendar Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configuraciones de Calendario</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalendarSetting__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Referenced calendar Id</description>
    <externalId>true</externalId>
    <label>Calendar Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalendarSetting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Calendar type for resource or user requesting from the meeting scheduler</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Resource</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/HolidayAbsence__c.object-meta.xml
<CustomObject>
    <description>Object related with a Calendar Id, indicates the unavailable dates of an user or resource</description>
    <label>Vacaciones / Bloqueos</label>
    <nameField>
        <displayFormat>HA-{000000}</displayFormat>
        <label>Absence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacaciones / Bloqueos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HolidayAbsence__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <description>Calendar Id of user or resource</description>
    <label>Calendar Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <description>Aditional comments</description>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <description>End of unavailable date range of user or resource</description>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <description>Absence reason</description>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>CalendarSettingType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacaciones</fullName>
            </value>
            <value>
                <fullName>Baja</fullName>
            </value>
            <value>
                <fullName>Formación</fullName>
            </value>
            <value>
                <fullName>Avería</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HolidayAbsence__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>Start of unavailable date range of user or resource</description>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/HolidayAbsenceRelatedListController.cls
public with sharing class HolidayAbsenceRelatedListController {
    
    @AuraEnabled
    public static GetHolidayAbsenceResponse getHolidayAbsenceByCalendarId(Id calendarSettingId){
        system.debug('calendarSettingId: '+calendarSettingId);
        GetHolidayAbsenceResponse resp = new GetHolidayAbsenceResponse();

        List<HolidayAbsence__c> lHolidayAbsence = new List<HolidayAbsence__c>();
        Id calendarId = null;
        String calendarSettingType = '';
        Boolean canCreateRecords = false;
        try{

            CalendarSetting__c calendarSetting = [SELECT Id, CalendarId__c, Type__c FROM CalendarSetting__c WHERE Id = :calendarSettingId limit 1];
            calendarId = calendarSetting.CalendarId__c;
            calendarSettingType = calendarSetting.Type__c;

            lHolidayAbsence = [SELECT Id, Name, CalendarId__c, StartDate__c, EndDate__c, Comments__c, Reason__c FROM HolidayAbsence__c WHERE CalendarId__c = :calendarSetting.CalendarId__c];

            canCreateRecords = Schema.SObjectType.HolidayAbsence__c.isCreateable();
            
        }catch(Exception e){
            resp.status = false;
            resp.errorMsg = e.getMessage();
        }

        resp.lHolidayAbsence = lHolidayAbsence;
        resp.calendarId = calendarId;
        resp.calendarSettingType = calendarSettingType;
        resp.canCreateRecords = canCreateRecords;
        return resp;
    }

    public class GetHolidayAbsenceResponse {
        @auraEnabled public Boolean status;
        @auraEnabled public String errorMsg;
        @auraEnabled public List<HolidayAbsence__c> lHolidayAbsence;
        @auraEnabled public Id calendarId;
        @auraEnabled public String calendarSettingType;
        @auraEnabled public Boolean canCreateRecords;

        public GetHolidayAbsenceResponse() {
            status = true;
            errorMsg = '';
            lHolidayAbsence = new List<HolidayAbsence__c>();
            canCreateRecords = false;
        }
    }
}