force-app/main/default/objects/Activo__c/Activo__c.object-meta.xml
<CustomObject>
    <description>Entidad que modela los bienes asociados a un Expediente</description>
    <label>Activo</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Número de Activo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activo__c/recordTypes/Tarjeta.recordType-meta.xml
<RecordType>
    <fullName>Tarjeta</fullName>
    <active>true</active>
    <description>Tarjeta de crédito</description>
    <label>Tarjeta</label>
</RecordType>

force-app/main/default/objects/ArrMinervDatosWS__c/ArrMinervDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Minerva de Arriaga</description>
    <label>ArriagaMinerva_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrMinervDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check de control que indica si la configuración puede o no usarse</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrMinervDatosWS__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint para los servicios de Minerva</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/ArrProdDatosWS__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos para las llamadas a los WS de Producción de Arriaga</description>
    <label>ArriagaProduccion_DatosLlamadas</label>
</CustomObject>

force-app/main/default/objects/ArrProdDatosWS__c/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Casilla que marca si el entorno esta activo para realizar peticiones</description>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtContc__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtContc__c</fullName>
    <label>EndpointCrear</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointInsrtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointInsrtExp__c</fullName>
    <description>Endpoint del entorno de producción para crear expedientes</description>
    <label>EndpointCrearExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointUpdtContc__c.field-meta.xml
<CustomField>
    <fullName>EndpointUpdtContc__c</fullName>
    <label>EndpointActulizar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/EndpointUpdtExp__c.field-meta.xml
<CustomField>
    <fullName>EndpointUpdtExp__c</fullName>
    <description>Endpoint del entorno de producción para actualizar un expediente</description>
    <label>EndpointActulizarExp</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PrivateKey__c.field-meta.xml
<CustomField>
    <fullName>PrivateKey__c</fullName>
    <description>Clave privada generada por Producción de Arriaga</description>
    <label>PrivateKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ArrProdDatosWS__c/fields/PublicKey__c.field-meta.xml
<CustomField>
    <fullName>PublicKey__c</fullName>
    <description>Clave publica utilizada para llegar al WS</description>
    <label>PublicKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Datosexpedientederivado__c/Datosexpedientederivado__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Datos utilizados para la derivación del expediente</description>
    <label>Datos expediente derivado</label>
</CustomObject>

force-app/main/default/objects/Datosexpedientederivado__c/fields/TiposDeriv__c.field-meta.xml
<CustomField>
    <fullName>TiposDeriv__c</fullName>
    <description>Tipos separados por coma que utilizaremos en el componente para cargar el picklist</description>
    <label>Tipos de derivación</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/DatosFlujo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Datos que se utilizan en el flujo de Gastos Hipotecarios</description>
    <label>Datos Flujo</label>
</CustomObject>

force-app/main/default/objects/DatosFlujo__c/fields/EtapaFinalOportunidadContrOnline__c.field-meta.xml
<CustomField>
    <fullName>EtapaFinalOportunidadContrOnline__c</fullName>
    <description>Etapa final asignada a la oportunidad en el flujo de comunidad</description>
    <label>EtapaFinalOportunidadContrOnline</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DatosFlujo__c/fields/EtapaOEtapaOportuniportunidadContrOnline__c.field-meta.xml
<CustomField>
    <fullName>EtapaOEtapaOportuniportunidadContrOnline__c</fullName>
    <description>Etapa de creación de la oportunidad</description>
    <label>EtapaOportunidadContrOnline</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/IntegracionGD__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de los datos necesarios para la conexión con los WS de encamina</description>
    <label>IntegracionGD</label>
</CustomObject>

force-app/main/default/objects/IntegracionGD__c/fields/claveAddDelete__c.field-meta.xml
<CustomField>
    <fullName>claveAddDelete__c</fullName>
    <description>Clave utilizada para eliminar y crear tipos de documentos</description>
    <label>claveAddDelete</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/clientid__c.field-meta.xml
<CustomField>
    <fullName>clientid__c</fullName>
    <label>client id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/clientsecret__c.field-meta.xml
<CustomField>
    <fullName>clientsecret__c</fullName>
    <label>client secret</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/DebugMode__c.field-meta.xml
<CustomField>
    <fullName>DebugMode__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Con check, el componente estará en modo debug</description>
    <label>DebugMode</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/EndpointDoc__c.field-meta.xml
<CustomField>
    <fullName>EndpointDoc__c</fullName>
    <description>Endpoint para los servicios de los documentos</description>
    <label>EndpointDoc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/EndpointDocType__c.field-meta.xml
<CustomField>
    <fullName>EndpointDocType__c</fullName>
    <description>Endpoint para los Servicios correspondientes a &quot;Document Type&quot;</description>
    <label>EndpointDocType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/granttype__c.field-meta.xml
<CustomField>
    <fullName>granttype__c</fullName>
    <label>grant type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/LimiteDocs__c.field-meta.xml
<CustomField>
    <fullName>LimiteDocs__c</fullName>
    <description>Limite de documentos mostrados por página en pantalla. Máximo 999</description>
    <label>Limite de documentos en pantalla</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/resource__c.field-meta.xml
<CustomField>
    <fullName>resource__c</fullName>
    <label>resource</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionGD__c/fields/usuarioAddDelete__c.field-meta.xml
<CustomField>
    <fullName>usuarioAddDelete__c</fullName>
    <description>Usuario utilizado para eliminar y dar de alta tipos de documentos</description>
    <label>usuarioAddDelete</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/IntegracionSF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración encargada de guardar los datos necesarios para poder obtener el token de la instacia de SF y de esta manera poder conectarnos con la misma instancia</description>
    <label>IntegracionSF</label>
</CustomObject>

force-app/main/default/objects/IntegracionSF__c/fields/clientid__c.field-meta.xml
<CustomField>
    <fullName>clientid__c</fullName>
    <description>Clave pública de la aplicación conectada</description>
    <label>client_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/clientsecret__c.field-meta.xml
<CustomField>
    <fullName>clientsecret__c</fullName>
    <description>Clave privada de la aplicación conectada</description>
    <label>client_secret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/password__c.field-meta.xml
<CustomField>
    <fullName>password__c</fullName>
    <description>Contraseña del usuario indicado</description>
    <label>password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/UrlEndPoint__c.field-meta.xml
<CustomField>
    <fullName>UrlEndPoint__c</fullName>
    <label>UrlEndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSF__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <description>Nombre de usuario de un usuario de SF</description>
    <label>username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/ProductosContrt__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración donde se indicarán los productos que están activos para realizar la contratación. En esta configuración se añadirán aquellos productos que siguen el patrón de gratuitos</description>
    <label>Productos a contratar</label>
</CustomObject>

force-app/main/default/objects/ProductosContrt__c/fields/IdProduct__c.field-meta.xml
<CustomField>
    <fullName>IdProduct__c</fullName>
    <label>Id Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/NameProduct__c.field-meta.xml
<CustomField>
    <fullName>NameProduct__c</fullName>
    <label>Nombre Producto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/URLArriaga__c.field-meta.xml
<CustomField>
    <fullName>URLArriaga__c</fullName>
    <description>Url donde se encuentra la información del producto que se quiere contratar dentro de la web de Arriaga</description>
    <label>URLArriaga</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductosContrt__c/fields/URLContratacion__c.field-meta.xml
<CustomField>
    <fullName>URLContratacion__c</fullName>
    <label>URL Pagina contratacion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Redsys_CodigosRespuesta__c/Redsys_CodigosRespuesta__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Integracion Redsys : Códigos de respuesta</description>
    <label>Redsys_CodigosRespuesta</label>
</CustomObject>

force-app/main/default/objects/Redsys_CodigosRespuesta__c/fields/Descripcion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion__c</fullName>
    <description>Información del código de Redsys</description>
    <label>Descripción</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RedsysDatosLlamada__c/RedsysDatosLlamada__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Redsys_DatosLlamada</label>
</CustomObject>

force-app/main/default/objects/RedsysDatosLlamada__c/fields/ClaveCifrado__c.field-meta.xml
<CustomField>
    <fullName>ClaveCifrado__c</fullName>
    <description>Clave secreta utilizada para el cifrado a Redsys</description>
    <label>Clave Secreta Cifrado</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RedsysDatosLlamada__c/fields/Datocomercio__c.field-meta.xml
<CustomField>
    <fullName>Datocomercio__c</fullName>
    <description>Campo correspondiente a DS_MERCHANTDATA en la llamada a Redsys</description>
    <label>Dato del comercio</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RedsysDatosLlamada__c/fields/FUC__c.field-meta.xml
<CustomField>
    <fullName>FUC__c</fullName>
    <description>Número de comercio correspondiente a Arriaga</description>
    <label>Número de comercio</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RedsysDatosLlamada__c/fields/NombreComercio__c.field-meta.xml
<CustomField>
    <fullName>NombreComercio__c</fullName>
    <description>Nombre del comercio que recebirá el pago</description>
    <label>Nombre del Comercio</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAux.cls
/*
@author Leadclic Solutions S.L.
@date 23/08/2017
@description Clase auxiliar para crear los datos necesarios de las clases de test

<pre>
FECHA               AUTOR  
15/04/2019			LCS - RDM            Creación 
03/07/2019			LCS - RDM            Modificación. Se añade las configuraciones necesarias para la clase GDRestCallouts
04/07/2019			LCS - RDM            Modificación. Se añade las configuraciones necesarias para la clase UpdateGlobalPicklistValue  
11/09/2019			LCS - RDM            Modificación. Se añade las configuraciones necesarias para la clase Minerva 
*/
@isTest
public with sharing class TestAux {
    
    public static void crearDatosRedsys(){
        RedsysDatosLlamada__c DatosRedsys = new RedsysDatosLlamada__c();
            DatosRedsys.Name = 'General';
        	DatosRedsys.ClaveCifrado__c ='sq7HjrUOBfKmC576ILgskD5srU870gJ7';
            DatosRedsys.Datocomercio__c = 'Arriaga payment - Data';
            DatosRedsys.NombreComercio__c = 'ARRIAGA ASOCIADOS ASESORAMIENTO JURIDICO Y ECONOMICO S.L.';
            DatosRedsys.FUC__c = '349436543';
        insert DatosRedsys;
    }
    
    public static void crearDatosFlujo(){
        DatosFlujo__c configDatosflujo = new DatosFlujo__c();
        	configDatosflujo.EtapaOEtapaOportuniportunidadContrOnline__c = 'Calificación';
        	configDatosflujo.EtapaFinalOportunidadContrOnline__c = 'Cerrada ganada';
         insert configDatosflujo;
    }
    
    public static void crearProducto(){
        ProductosContrt__c configPro = new ProductosContrt__c();
        	configPro.Name = 'IRPH';
        	configPro.Activo__c = true;
        	configPro.IdProduct__c = '4513165468751354HHHJK';
        	configPro.NameProduct__c = 'IRPH';
        	configPro.URLArriaga__c = '/s/irph-contratacion';
        	configPro.URLContratacion__c = 'www.arriagaasociado.com';
         insert configPro;
    }
    
    public static void crearExpeDerivados(){
        Datosexpedientederivado__c configExpDer = new Datosexpedientederivado__c();
        	configExpDer.Name = 'General';
        	configExpDer.TiposDeriv__c = 'Reclamación por cantidad, Demanda independiente de cláusula suelo';
         insert configExpDer;
    }    

    public static void crearIntegracionGD(){
        IntegracionGD__c intGD = new IntegracionGD__c();
        	intGD.Name = 'General';
            intGD.claveAddDelete__c = '73bc3ed9-35a9-44ab-8642-dc43ebe64878';
            intGD.clientid__c = '998c0f65-cdc6-49e0-8a7e-ea1122d0ead0';
            intGD.clientsecret__c = '8KttlQ70CrgjLbt7EqWJx9mi7I5P/AAMfk7I2w2YGF0=';
            intGD.DebugMode__c = false;
            intGD.Endpoint__c = 'https://login.microsoftonline.com/73bc3ed9-35a9-44ab-8642-dc43ebe64878/oauth2/token';
            intGD.EndpointDoc__c = 'https://aa-pre-backend-api.azurewebsites.net/api/document';
            intGD.EndpointDocType__c = 'https://aa-pre-backend-api.azurewebsites.net/api/catalogs/documentType';
            intGD.granttype__c = 'client_credentials';
            intGD.LimiteDocs__c = 5;
            intGD.resource__c = '3e8ea5fe-aa21-4f79-af82-8f4ae132603c';
            intGD.usuarioAddDelete__c = 'user@arriaga.com';
        insert intGD;

    } 

    public static void crearIntegracionSF(){
        IntegracionSF__c intSF = new IntegracionSF__c();
        	intSF.Name = 'General';      
            intSF.clientid__c = '3MVG96mGXeuuwTZidMQsqDxgpszJMV8IjpVhWe1VxmKSN.ZXEC6zqJ0BsQcZfmUuGAvRr3cUFfUh3R1_DCzIn';
            intSF.clientsecret__c = '2519AAC4A5261BB7A72FB447559C2B51FD1040305D15397F032CF80683474F1A';
            intSF.password__c = 'crm4ever1';
            intSF.UrlEndPoint__c = 'https://test.salesforce.com/services/oauth2/token';
            intSF.username__c = 'rmoreira@arriaga.dev1'; 
        insert intSF;
    }
    
    public static void crearRedsysCodigoRespuesta(){
        list<Redsys_CodigosRespuesta__c> lcodesResp = new list<Redsys_CodigosRespuesta__c>();
        
    	Redsys_CodigosRespuesta__c codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = '0to99';
        codesResp.Descripcion__c = 'Transacción autorizada para pagos y preautorizaciones';
        
        lcodesResp.add(codesResp);
        
        
        codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = '0180';
        codesResp.Descripcion__c = 'Tarjeta ajena al servicio';
        lcodesResp.add(codesResp);
        
        
        codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = 'NonExistCode';
        codesResp.Descripcion__c = 'Error al realizar el pago. Realice de nuevo el pago al cabo de un instante';
        lcodesResp.add(codesResp);
        
        codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = 'OK';
        codesResp.Descripcion__c = 'Pago realizado con exito';
        lcodesResp.add(codesResp);
        
        codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = 'KO';
        codesResp.Descripcion__c = 'Hubo un problema con su pago. El error que produjo fue';
        lcodesResp.add(codesResp);
        
        codesResp = new Redsys_CodigosRespuesta__c();
        codesResp.Name = 'KOFirma';
        codesResp.Descripcion__c = 'Error de firma enviada por el servidor de REDSYS. Comuníquese con su administración.';
        lcodesResp.add(codesResp);
        
        
        insert lcodesResp;
    }    
    
    
    public static void crearDatosMinerva(){
        ArrMinervDatosWS__c configDatosflujo = new ArrMinervDatosWS__c();
        	configDatosflujo.Name = 'General';
        	configDatosflujo.Activo__c = true;
        	configDatosflujo.Endpoint__c = 'https://aa-pre-backend-api.azurewebsites.net';        	
        insert configDatosflujo;
    } 
    
    
    public static void crearDatosProd(){
        ArrProdDatosWS__c configDatosflujo = new ArrProdDatosWS__c();
        	configDatosflujo.Name = 'General';
        	configDatosflujo.Activo__c = true;
        	configDatosflujo.EndpointUpdtContc__c = 'https://sandbox-api.arriagaasociados.com/api/clients/clients/'; 
        	configDatosflujo.EndpointUpdtExp__c = 'https://sandbox-api.arriagaasociados.com/api/records/records/'; 
        	configDatosflujo.EndpointInsrtContc__c = 'https://sandbox-api.arriagaasociados.com/api/clients/clients.json'; 
        	configDatosflujo.EndpointInsrtExp__c = 'https://sandbox-api.arriagaasociados.com/api/records/records.json'; 
        	configDatosflujo.PrivateKey__c = 't2xO1SSQT9wkYLcoNQEWGFsZ41GATIDLxLhRvx2lFIJ1FHQJ'; 
        	configDatosflujo.PublicKey__c = 'kwadB10EqyFxZw3hFqkFFOzvm8BmEl56qCbHYxYx7nmjCKit'; 
         insert configDatosflujo;
    }

    /**
     *  Método que crea un nuevo registro de usuario
     */
    
    public static User createNewUser() {
        // Define los datos del nuevo usuario
        String firstName = 'Prueba';
        String lastName = 'Usuario';
        String email = 'puser@test.com';
        String username = 'puser' + UserInfo.getUserId() + '@test.com';
        
        // Crea el nuevo usuario
        User newUser = new User();
        newUser.FirstName = firstName;
        newUser.LastName = lastName;
        newUser.Email = email;
        newUser.Username = username;
        newUser.Alias = 'pUser';
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.EmailEncodingKey ='UTF-8';
        newUser.ProfileId = UserInfo.getProfileId();
        insert newUser;   
        
        return newUser;        
    }  
    

}